% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={The RJafroc Froc Book},
  pdfauthor={Dev P. Chakraborty, PhD},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{amsthm}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage[]{natbib}
\bibliographystyle{apalike}

\title{The RJafroc Froc Book}
\author{Dev P. Chakraborty, PhD}
\date{2021-12-20}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{preface}{%
\chapter*{Preface}\label{preface}}
\addcontentsline{toc}{chapter}{Preface}

\begin{itemize}
\tightlist
\item
  It is intended as an online update to my print book \citep{chakraborty2017observer}.
\item
  Since its publication in 2017 the \texttt{RJafroc} package, on which the \texttt{R} code examples in the book depend, has evolved considerably, causing many of the examples to ``break''.
\item
  This also gives me the opportunity to improve on the book and include additional material.
\item
  The online book is in 3 parts.
\item
  This part is devoted to the FROC paradigm.
\end{itemize}

\hypertarget{tba-how-much-finished}{%
\section*{TBA How much finished}\label{tba-how-much-finished}}
\addcontentsline{toc}{section}{TBA How much finished}

\begin{itemize}
\tightlist
\item
  HMF approximately 30\%
\item
  This book is currently (as of December 2021) in preparation.
\item
  Parts labeled TBA and TODOLAST need to be updated on final revision.
\item
  Un-comment links like \texttt{\textbackslash{}@ref(froc-paradigm-solar-analogy)} etc. Search for `@ref
\end{itemize}

\hypertarget{the-pdf-file-of-the-book}{%
\section*{The pdf file of the book}\label{the-pdf-file-of-the-book}}
\addcontentsline{toc}{section}{The pdf file of the book}

Go \href{https://github.com/dpc10ster/RJafrocFrocBook/blob/gh-pages/RJafrocFrocBook.pdf}{here} and then click on \texttt{Download} to get the \texttt{RJafrocFrocBook.pdf} file.

\hypertarget{the-html-version-of-the-book}{%
\section*{The html version of the book}\label{the-html-version-of-the-book}}
\addcontentsline{toc}{section}{The html version of the book}

Go \href{https://dpc10ster.github.io/RJafrocFrocBook/}{here} to view the \texttt{html} version of the book.

\hypertarget{a-note-on-the-online-distribution-mechanism-of-the-book}{%
\section*{A note on the online distribution mechanism of the book}\label{a-note-on-the-online-distribution-mechanism-of-the-book}}
\addcontentsline{toc}{section}{A note on the online distribution mechanism of the book}

\begin{itemize}
\tightlist
\item
  In the hard-copy version of my book \citep{chakraborty2017observer} the online distribution mechanism was \texttt{BitBucket}.
\item
  \texttt{BitBucket} allows code sharing within a \emph{closed} group of a few users (e.g., myself and a grad student).
\item
  Since the purpose of open-source code is to encourage collaborations, this was, in hindsight, an unfortunate choice. Moreover, as my experience with R-packages grew, it became apparent that the vast majority of R-packages are shared on \texttt{GitHub}, not \texttt{BitBucket}.
\item
  For these reasons I have switched to \texttt{GitHub}. All previous instructions pertaining to \texttt{BitBucket} are obsolete.
\item
  In order to access \texttt{GitHub} material one needs to create a (free) \texttt{GitHub} account.
\item
  Go to \href{https://github.com}{this link} and click on \texttt{Sign\ Up}.
\end{itemize}

\hypertarget{structure-of-the-book}{%
\section*{Structure of the book}\label{structure-of-the-book}}
\addcontentsline{toc}{section}{Structure of the book}

The book is divided into parts as follows:

\begin{itemize}
\tightlist
\item
  Part I: Quick Start: intended for existing Windows \texttt{JAFROC} users who are seeking a quick-and-easy transition from Windows \texttt{JAFROC} to \texttt{RJafroc}.
\item
  Part II: ROC paradigm: this covers the basics of the ROC paradigm
\item
  Part III: Significance Testing: The general procedure used to determine the significance level, and associated statistics, of the observed difference in figure of merit between pairs of treatments or readers
\item
  Part IV: FROC paradigm: TBA
\end{itemize}

\hypertarget{contributing-to-this-book}{%
\section*{Contributing to this book}\label{contributing-to-this-book}}
\addcontentsline{toc}{section}{Contributing to this book}

I appreciate constructive feedback on this document. To do this raise an \texttt{Issue} on the \texttt{GitHub} \href{https://github.com/dpc10ster/RJafrocFrocBook}{interface}. Click on the \texttt{Issues} tab under \texttt{dpc10ster/RJafrocFrocBook}, then click on \texttt{New\ issue}. When done this way, contributions from users automatically become part of the \texttt{GitHub} documentation/history of the book.

\hypertarget{is-this-book-relevant-to-you-and-what-are-the-alternatives}{%
\section*{Is this book relevant to you and what are the alternatives?}\label{is-this-book-relevant-to-you-and-what-are-the-alternatives}}
\addcontentsline{toc}{section}{Is this book relevant to you and what are the alternatives?}

\begin{itemize}
\tightlist
\item
  Diagnostic imaging system evaluation
\item
  Detection
\item
  Detection combined with localization
\item
  Detection combined with localization and classification
\item
  Optimization of Artificial Intelligence (AI) algorithms
\item
  CV
\item
  Alternatives
\end{itemize}

\hypertarget{chapters-needing-heavy-edits}{%
\section*{Chapters needing heavy edits}\label{chapters-needing-heavy-edits}}
\addcontentsline{toc}{section}{Chapters needing heavy edits}

\begin{itemize}
\tightlist
\item
  12-froc.
\item
  13-froc-empirical.
\item
  13-froc-empirical-examples.
\end{itemize}

\hypertarget{shelved-vs.-removed-vs.-parked-folders-needing-heavy-edits}{%
\section*{Shelved vs.~removed vs.~parked folders needing heavy edits}\label{shelved-vs.-removed-vs.-parked-folders-needing-heavy-edits}}
\addcontentsline{toc}{section}{Shelved vs.~removed vs.~parked folders needing heavy edits}

\begin{itemize}
\tightlist
\item
  replace functions with \text{}; eg. erf and exp in all of document
\item
  Also for TPF, FPF etc.
\item
  Temporarily shelved 17c-rsm-evidence.Rmd in removed folder
\item
  Now 17-b is breaking; possibly related to changes in RJafroc: had to do with recent changes to RJafroc code - RSM\_xFROC etc requiring intrinsic parameters; fixed 17-b
\item
  parked has dependence of ROC/FROC performance on threshold
\end{itemize}

\hypertarget{coding-aids-for-me}{%
\section*{Coding aids (for me)}\label{coding-aids-for-me}}
\addcontentsline{toc}{section}{Coding aids (for me)}

\begin{itemize}
\tightlist
\item
  weird error with knitr not responding to changes in Rmd file: traced to upper case lower case confusion: 13A-froc-empirical1.Rmd which should be 13a-froc-empirical1.Rmd
\end{itemize}

\hypertarget{formatting}{%
\subsection{formatting}\label{formatting}}

\begin{itemize}
\tightlist
\item
  sprintf(``\%.4f'', proper formatting of numbers
\item
  OpPtStr(, do:
\end{itemize}

\hypertarget{tables}{%
\subsection{tables}\label{tables}}

\begin{itemize}
\tightlist
\item
  \url{https://github.com/haozhu233/kableExtra/issues/624}
\item
  kbl(dfA, caption = ``\ldots.'', booktabs = TRUE, escape = FALSE) \%\textgreater\% collapse\_rows(columns = c(1, 3), valign = ``middle'') \%\textgreater\% kable\_styling(latex\_options = c(``basic'', ``scale\_down'', ``HOLD\_position''), row\_label\_position = ``c'')
\item
  ```\{r, attr.source = ``.numberLines''\}
\item
  kbl(x12, caption = ``Summary of optimization results using wAFROC-AUC.'', booktabs = TRUE, escape = FALSE) \%\textgreater\% collapse\_rows(columns = c(1), valign = ``middle'') \%\textgreater\% kable\_styling(latex\_options = c(``basic'', ``scale\_down'', ``HOLD\_position''), row\_label\_position = ``c'')
\item
  \(\text{exp} \left ( -\lambda' \right )\) space before dollar sign generates a pdf error
\item
  FP errors generated by GitHub actions due to undefined labels:
  Error: Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc\_available).
  In addition: Warning message:
  In verify\_rstudio\_version() :
  Please install or upgrade Pandoc to at least version 1.17.2; or if you are using RStudio, you can just install RStudio 1.0+.
  Execution halted
\end{itemize}

\hypertarget{tinytex-problems}{%
\subsection{tinytex problems}\label{tinytex-problems}}

\begin{itemize}
\tightlist
\item
  dont update in response to messages; breaks everything
\item
  DONT DO THIS: When tinytex::install\_tinytex() hangs up try
\item
  DONT DO THIS: tinytex::install\_tinytex(repository = ``\url{http://mirrors.tuna.tsinghua.edu.cn/CTAN/}'', version = ``latest'')
\item
  Getting very long builds: looping certain commands
\item
  First uninstall tinytex then reinstall:
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#uninstall_tinytex(force = FALSE, dir = tinytex_root())}
\CommentTok{#tinytex::install_tinytex()}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  get very long build first time with looping certain commands
\item
  fixed on subsequent pdf builds
\end{itemize}

\hypertarget{froc-empirical}{%
\chapter{Empirical plots from FROC data}\label{froc-empirical}}

\hypertarget{froc-empirical-how-much-finished}{%
\section{TBA How much finished}\label{froc-empirical-how-much-finished}}

90\%

\hypertarget{froc-empirical-intro}{%
\section{TBA Introduction}\label{froc-empirical-intro}}

FROC data consists of mark-rating pairs. In this chapter a distinction is made between latent and actual marks. This is followed by a table summarizing FROC notation. This is a key table which will be used in later chapters. Section \texttt{\textbackslash{}@ref(froc-paradigm-froc-plot)} introduced the empirical FROC plot. This chapter presents mathematical expressions for this and other empirical plots possible with FROC data: the inferred-ROC, the alternative FROC, the weighted alternative FROC, and others. Operating characteristics are \emph{visual} depicters of performance. Scalar quantities, typically area measures derived from operating characteristics, are \emph{quantitative} measures of performance, termed \emph{figures of merit} (FOMs). This chapter defines an area measure for each empirical operating characteristic. An FROC dataset is used to illustrate the plots and area measures. With the exception of the FROC, all empirical plots include a straight line extension from the observed end-point to (1,1). The correlation between the area measures is qualitatively examined via plots. It is shown that for this dataset the FROC area measure correlates poorly with that under the ROC curve, whereas the other measures correlate better. This is explained by the fact that, unlike the other measures, the FROC plot is not contained within the unit square.

\hypertarget{froc-empirical-mark-rating-pairs}{%
\section{Mark rating pairs}\label{froc-empirical-mark-rating-pairs}}

\emph{FROC data consists of mark-rating pairs}. Each mark indicates the location of a region suspicious enough to warrant reporting and the rating is the associated confidence level. A mark is recorded as \emph{lesion localization} (LL) if it is sufficiently close to a true lesion, according to the adopted proximity criterion, and otherwise it is recorded as \emph{non-lesion localization} (NL).

\emph{In an FROC study the number of marks on an image is an a-priori unknown modality-reader-case dependent non-negative random integer.} It is incorrect and naive to estimate it by dividing the image area by the lesion area because not all regions of the image are equally likely to have lesions, lesions do not have the same size, and perhaps most important, clinicians don't assign equal attention units to all areas of the image. The best insight into the number of marks per case is obtained from eye-tracking studies \citep{RN1490}, but even here the information is incomplete, as eye-tracking studies can only measure foveal gaze and not lesions found by peripheral vision, and such studies are very difficult to conduct in a clinical setting.

\hypertarget{latent-vs.-actual-marks}{%
\subsection{Latent vs.~actual marks}\label{latent-vs.-actual-marks}}

To distinguish between suspicious regions that were considered for marking and regions that were actually marked, it is necessary to introduce the distinction between \emph{latent} marks and \emph{actual} marks.

\begin{itemize}
\tightlist
\item
  A \emph{latent} mark is defined as a suspicious region, regardless of whether or not it was marked. A latent mark becomes an \emph{actual} mark if it is marked.
\item
  A latent mark is a latent LL if it is close to a true lesion and otherwise it is a latent NL.
\item
  A non-diseased case can only have latent NLs. A diseased case can have latent NLs and latent LLs.
\item
  If marked, a latent NL is recorded as an actual NL.
\item
  If not marked, a latent NL is an \emph{unobservable event}.
\item
  In contrast, unmarked lesions are observable events -- one knows (trivially) which lesions were not marked.
\end{itemize}

\hypertarget{binning-rule}{%
\subsection{Binning rule}\label{binning-rule}}

Recall that ROC data modeling requires the existence of a \emph{case-dependent} decision variable, or z-sample \(z\), and case-independent decision thresholds \(\zeta_r\), where \(r = 0, 1, ..., R_{ROC}-1\) and \(R_{ROC}\) is the number of ROC study bins \footnote{The subscript is used to make explicit the paradigm used.} and a binning rule that if \(\zeta_r \leq z < \zeta_{r+1}\) the case is rated \(r + 1\). Dummy cutoffs are defined as \(\zeta_0 = -\infty\) and \(\zeta_{R_{ROC}} = \infty\). The z-sample applies to the whole case. To summarize:

\begin{equation}
\left.
\begin{aligned}  
\text{if} \left (\zeta_r \le z < \zeta_{r+1}  \right )\Rightarrow \text {rating} = r+1\\
r = 0, 1, ..., R_{ROC}-1\\
\zeta_0 = -\infty\\
\zeta_{R_{ROC}} = \infty\\
\end{aligned}
\right \}
\label{eq:binning-rule-roc}
\end{equation}

Analogously, FROC data modeling requires the existence of a \emph{case and location dependent} z-sample for each latent mark and \emph{case and location independent} reporting thresholds \(\zeta_r\), where \(r = 1, ..., R_{FROC}\) and \(R_{FROC}\) is the number of FROC study bins, and the rule that a latent mark is marked and rated \(r\) if \(\zeta_r \leq z < \zeta_{r+1}\). Dummy cutoffs are defined as \(\zeta_0 = -\infty\) and \(\zeta_{R_{FROC}+1} = \infty\). For the same numbers of non-dummy cutoffs, the number of FROC bins is one less than the number of ROC bins. For example, 4 non-dummy cutoffs \(\zeta_1, \zeta_2, \zeta_3, \zeta_4\) can correspond to a 5-rating ROC study or to a 4-rating FROC study. To summarize:

\begin{equation}
\left.
\begin{aligned}  
\text{if} \left (\zeta_r \le z < \zeta_{r+1}  \right )\Rightarrow \text {rating} = r\\
r = 1, 2, ..., R_{FROC}\\
\zeta_0 = -\infty\\
\zeta_{R_{FROC}+1} = \infty\\
\end{aligned}
\right \}
\label{eq:binning-rule-froc}
\end{equation}

\hypertarget{froc-empirical-notation}{%
\section{Notation}\label{froc-empirical-notation}}

\emph{Clear notation is vital to understanding this paradigm.} The notation needs to account for case and location dependencies of ratings and the distinction between case-level and location-level ground truth. The notation also has to account for cases with no marks.

FROC notation is summarized in Table \ref{tab:froc-empirical-notation}, in which \emph{marks refer to latent marks}. The table is organized into three columns, the first column is the row number, the second column has the symbol(s), and the third column has the meaning(s) of the symbol(s).

\begin{table}

\caption{\label{tab:froc-empirical-notation}FROC notation; all marks refer to latent marks.}
\centering
\begin{tabular}[t]{l|l|l}
\hline
Row & Symbol & Meaning\\
\hline
1 & t & Case-level truth: 1 for non-diseased and 2 for diseased\\
\hline
2 & $K_t$ & Number of cases with case-level truth t\\
\hline
3 & $k_t t$ & Case $k_t$ in case-level truth t\\
\hline
4 & s & Location-level truth: 1 for NL and 2 for LL\\
\hline
5 & $l_s s$ & Mark $l_s$ in location-level truth s\\
\hline
6 & $N_{k_t t}$ & Number of NLs in case $k_t t$\\
\hline
7 & $L_{k_2 2}$ & Number of lesions in case $k_2 2$\\
\hline
8 & $z_{k_t t l_1 1}$ & z-sample for case $k_t t$ and mark $l_1 1$\\
\hline
9 & $z_{k_2 2 l_2 2}$ & z-sample for case $k_2 2$ and mark $l_2 2$\\
\hline
10 & $R_{FROC}$ & Number of FROC bins\\
\hline
11 & $\zeta_1$ & Lowest reporting threshold\\
\hline
12 & $\zeta_r$ & r = 2, 3, ... the other non-dummy reporting thresholds\\
\hline
13 & $\zeta_0, \zeta_{R_{FROC}+1}$ & Dummy thresholds\\
\hline
14 & $W_{k_2 l_2}$ & Weight of lesion $l_2 2$ in case $k_2 2$\\
\hline
15 & $L_{max}$ & Maximum number of lesions per case in dataset\\
\hline
16 & $L_T$ & Total number of lesions in dataset\\
\hline
\end{tabular}
\end{table}

\hypertarget{comments-on-table-reftabfroc-empirical-notation}{%
\subsection{Comments on Table \ref{tab:froc-empirical-notation}}\label{comments-on-table-reftabfroc-empirical-notation}}

\begin{itemize}
\item
  Row 1: The case-truth index \(t\) refers to the case (or patient), with \(t = 1\) for non-diseased and \(t = 2\) for diseased cases. As a useful mnemonic, \(t\) is for \emph{truth}.
\item
  Row 2: \(K_t\) is the number of cases with truth state \(t\); specifically, \(K_1\) is the number of non-diseased cases and \(K_2\) the number of diseased cases.
\item
  Row 3: Two indices \(k_t t\) are needed to select case \(k_t\) in truth state \(t\). As a useful mnemonic, \(k\) is for \emph{case}.
\item
  Row 4: \(s\) location-level truth state: 1 for non-diseased and 2 for diseased.
\item
  Row 5: Similar to row 3, two indices \(l_s s\) are needed to select latent mark \(l_s\) in location-level truth state \(s\). As a useful mnemonic, \(l\) is for \emph{location}.
\item
  Row 6: \(N_{k_t t}\) is the total number of latent NL marks in case \(k_t t\).
\item
  Row 7: \(L_{k_2 2}\) is the number of lesions in diseased case \(k_2 2\).
\item
  Row 8: The z-sample for case \(k_t t\) and NL mark \(l_1 1\) is denoted \(z_{k_t t l_1 1}\). Latent NL marks are possible on non-diseased and diseased cases (both values of \(t\) are allowed). The range of a z-sample is \(-\infty < z_{k_t t l_1 1} < \infty\), provided \(l_1 \neq \varnothing\); otherwise, it is an unobservable event.
\item
  Row 9: The z-sample of a latent LL is \(z_{k_2 2 l_2 2}\). Unmarked lesions are observable events and are therefore assigned negative infinity ratings (the null-set notation is unnecessary for them).
\item
  Row 10: \(R_{FROC}\) is the number of bins in the FROC study.
\item
  Rows 11, 12 and 13: The cutoffs in the FROC study. The lowest threshold is \(\zeta_1\). The other non-dummy thresholds are \(\zeta_r\) where \(r=2,3,...,R_{FROC}\). The dummy thresholds are \(\zeta_0 = -\infty\) and \(\zeta_{R_{FROC}+1} = \infty\).
\item
  Row 14: \(W_{k_2 l_2}\) is the weight (i.e., clinical importance) of lesion \(l_2 2\) in diseased case \(k_2 2\). The weights of lesions in a case sum to unity: \(\sum_{l_2 = 1}^{L_{k_2 2}}W_{k_2 l_2} = 1\).
\item
  Row 15: \(L_{max}\) is the maximum number of lesions per case in the dataset.
\item
  Row 16: \(L_T\) is the total number of lesions in the dataset.
\end{itemize}

\hypertarget{froc-empirical-indexing-marks}{%
\subsection{A conceptual and notatonal issue}\label{froc-empirical-indexing-marks}}

An aspect of FROC data, \emph{that there could be cases with no NL marks, no matter how low the reporting threshold}, has created problems both from conceptual and notational viewpoints. Taking the conceptual issue first, my thinking (prior to 2004) was that as the reporting threshold \(\zeta_1\) is lowered, the number of NL marks per case increases almost indefinitely. I visualized this process as each case ``filling up'' with NL marks \footnote{I expected the number of NL marks per image to be limited only by the ratio of image size to lesion size, i.e., larger values for smaller lesions.}. In fact the first model of FROC data \citep{chakraborty1989maximum} predicts that, as the reporting threshold is lowered to \(\zeta_1 = -\infty\), the number of NL marks per case approaches \(\infty\) as does \(\text{NLF}_{max}\). However, observed FROC curves end at a finite value of \(\text{NLF}_{max}\). This is one reason I introduced the radiological search model (RSM) \citep{chakraborty2006search}. I will have much more to say about this in Chapter \texttt{\textbackslash{}@ref(rsm)}, but for now I state one assumption of the RSM: the number of latent NL marks is a Poisson distributed random integer with a finite value for the mean parameter of the distribution. This means that the actual number of latent NL marks per case can be 0, 1, 2, .., whose average (over all cases) is a finite number.

With this background, let us return to the conceptual issue: why does the observer not keep ``filling-up'' the image with NL marks? The answer is that \emph{the observer can only mark regions that have a non-zero chance of being a lesion}. For example, if the actual number of latent NLs on a particular case is 2, then, as the reporting threshold is lowered, the observer will make at most two NL marks. Having exhausted these two regions the observer will not mark any more regions because there are no more regions to be marked - \emph{all other regions in the image have, in the perception of the observer, zero chance of being a lesion}.

The notational issue is how to handle images with no latent NL marks. Basically it involves restricting summations over cases \(k_ t t\) to those cases which have at least one latent NL mark, i.e., \(N_{k_t t} \neq 0\), as in the following:

\begin{itemize}
\item
  \(l_1 = \{1, 2, ..., N_{k_t t}\}\) indexes latent NL marks, provided the case has at least one latent NL mark, and otherwise \(N_{k_t t} = 0\) and \(l_1 = \varnothing\), the null set. The possible values of \(l_1\) are \(l_1 = \left \{ \varnothing \right \}\oplus \left \{ 1,2,...N_{k_t t} \right \}\). The null set applies when the case has no latent NL marks and \(\oplus\) is the ``exclusive-or'' symbol (``exclusive-or'' is used in the English sense: ``one or the other, but not neither nor both''). In other words, \(l_1\) can \emph{either} be the null set or take on values \(1,2,...N_{k_t t}\).
\item
  Likewise, \(l_2 = \left \{ 1,2,...,L_{k_2 2} \right \}\) indexes latent LL marks. Unmarked LLs are assigned negative infinity ratings. The null set notation is not needed for latent LLs.
\end{itemize}

\hypertarget{froc-empirical-froc-plot}{%
\section{The empirical FROC plot}\label{froc-empirical-froc-plot}}

The FROC, Chapter \texttt{\textbackslash{}@ref(froc-paradigm-froc-plot)}, is the plot of LLF (along the ordinate) vs.~NLF (along the abscissa).

Using the notation of Table \ref{tab:froc-empirical-notation} and assuming binned data\footnote{This is not a limiting assumption: if the data is continuous, for finite numbers of cases, no ordering information is lost if the number of ratings is chosen large enough. This is analogous to Bamber's theorem in Chapter 05, where a proof, although given for binned data, is applicable to continuous data.}, then, corresponding to the operating point determined by threshold \(\zeta_r\), the FROC abscissa is \(\text{NLF}_r \equiv \text{NLF}\left ( \zeta_r \right )\), the total number of NLs rated \(\geq\) threshold \(\zeta_r\) divided by the total number of cases, and the corresponding ordinate is \(\text{LLF}_r \equiv \text{LLF}\left ( \zeta_r \right )\), the total number of LLs rated \(\geq\) threshold \(\zeta_r\) divided by the total number of lesions:

\begin{equation}
\text{NLF}_r  = \frac{n\left ( \text{NLs rated} \geq \zeta_r\right )}{n\left ( \text{cases} \right )}
\label{eq:froc-empirical-NLF1}
\end{equation}

and

\begin{equation}
\text{LLF}_r  = \frac{n\left ( \text{LLs rated} \geq \zeta_r\right )}{n\left ( \text{lesions} \right )}
\label{eq:froc-empirical-LLF1}
\end{equation}

The observed operating points correspond to the following values of \(r\):

\begin{equation}
r = 1, 2, ...,R_{FROC} 
\label{eq:froc-empirical-range-r}
\end{equation}

Due to the ordering of the thresholds, i.e., \(\zeta_1 < \zeta_2 ... < \zeta_{R_{FROC}}\), higher values of \(r\) correspond to lower operating points. The uppermost operating point, i.e., that defined by \(r = 1\), is referred to the as the \emph{observed end-point}.

Equations \eqref{eq:froc-empirical-NLF1} and \eqref{eq:froc-empirical-LLF1} is are equivalent to:

\begin{equation}
\text{NLF}_r  = \frac{1}{K_1+K_2} \sum_{t=1}^{2} \sum_{k_t=1}^{K_t} \mathbb{I} \left ( N_{k_t t} \neq 0 \right )\sum_{l_1=1}^{N_{k_t t}} \mathbb{I} \left ( z_{k_t t l_1 1} \geq \zeta_r \right ) 
\label{eq:froc-empirical-NLFr}
\end{equation}

and

\begin{equation}
\text{LLF}_r  = \frac{1}{L_T} \sum_{k_2=1}^{K_2} \sum_{l_2=1}^{L_{k_2 2}} \mathbb{I} \left ( z_{k_2 2 l_2 2} \geq \zeta_r  \right ) 
\label{eq:froc-empirical-LLFr}
\end{equation}

Each indicator function, \(\mathbb{I}()\), yields unity if the argument is true and zero otherwise.

In Eqn. \eqref{eq:froc-empirical-NLFr} \(\mathbb{I} \left ( N_{k_t t} \neq 0 \right )\) ensures that \emph{only cases with at least one latent NL} are counted. Recall that \(N_{k_t t}\) is the total number of latent NLs in case \(k_t t\). The term \(\mathbb{I} \left ( z_{k_t t l_1 1} \geq \zeta_r \right )\) counts over all NL marks with ratings \(\geq \zeta_r\). The three summations yield the total number of NLs in the dataset with z-samples \(\geq \zeta_r\) and dividing by the total number of cases yields \(\text{NLF}_r\). This equation also shows explicitly that NLs on both non-diseased (\(t=1\)) and diseased (\(t=2\)) cases contribute to NLF.

In Eqn. \eqref{eq:froc-empirical-LLFr} a summation over \(t\) is not needed as only diseased cases contribute to LLF. Analogous to the first indicator function term in Eqn. \eqref{eq:froc-empirical-NLFr}, a term like \(\mathbb{I} \left ( L_{k_2 2} \neq 0 \right )\) would be superfluous since \(L_{k_2 2} > 0\) as each diseased case must have at least one lesion. The term \(\mathbb{I} \left ( z_{k_2 2 l_2 2} \geq \zeta_r \right )\) counts over all LL marks with ratings \(\geq \zeta_r\). Dividing by \(L_T\), the total number of lesions in the dataset, yields \(\text{LLF}_r\).

\hypertarget{froc-empirical-definition-empirical-auc-froc}{%
\subsection{Definition empirical plot and AUC}\label{froc-empirical-definition-empirical-auc-froc}}

The empirical FROC plot connects adjacent operating points \(\left (\text{NLF}_r, \text{LLF}_r \right )\), including the origin (0,0) and the observed end-point, with straight lines. The area under this plot is the empirical FROC AUC, denoted \(A_{\text{FROC}}\).

\hypertarget{froc-empirical-origin-trivial-point}{%
\subsection{The origin, a trivial point}\label{froc-empirical-origin-trivial-point}}

Since \(\zeta_{R_{FROC}+1} = \infty\) according to Eqn. \eqref{eq:froc-empirical-NLFr} and Eqn. \eqref{eq:froc-empirical-LLFr}, \(r = R_{FROC}+1\) yields the trivial operating point (0,0).

\hypertarget{froc-empirical-end-point}{%
\subsection{The observed end-point and its semi-constrained property}\label{froc-empirical-end-point}}

The abscissa of the observed end-point \(NLF_1\), is defined by:

\begin{equation}
\text{NLF}_1 = \frac{1}{K_1+K_2} \sum_{t=1}^{2} \sum_{k_t=1}^{K_t} \mathbb{I} \left ( N_{k_t t} \neq 0 \right ) \sum_{l_1=1}^{N_{k_t t}} \mathbb{I} \left ( z_{k_t t l_1 1} \geq \zeta_1 \right ) 
\label{eq:froc-empirical-NLF11}
\end{equation}

Since each case could have an arbitrary number of NLs, \(NLF_1\) need not equal unity, except fortuitously.

The ordinate of the observed end-point \(LLF_1\), is defined by:

\begin{equation}
\left.
\begin{aligned}
\text{LLF}_1 =& \frac{ \sum_{k_2=1}^{K_2} \sum_{l_2=1}^{L_{k_2 2}} \mathbb{I} \left ( z_{k_2 2 l_2 2} \geq  \zeta_1  \right ) }{L_T}\\
\leq& 1
\end{aligned}
\right \}
\label{eq:froc-empirical-LLF1a}
\end{equation}

The numerator is the total number of lesions that were actually marked. The ratio is the fraction of lesions that are marked, which is \(\leq 1\).

This is the \textbf{semi-constrained property of the observed end-point}, namely, while the observed end-point \emph{ordinate} is constrained to the range (0,1) the corresponding \emph{abscissa} is not so constrained.

\hypertarget{froc-empirical-froc-plot-futility-extrapolation}{%
\subsection{Futility of extrapolation outside the observed end-point}\label{froc-empirical-froc-plot-futility-extrapolation}}

To understand this consider the expression for \(NLF_0\), i.e., using Eqn. \eqref{eq:froc-empirical-NLFr} with \(r = 0\):

\begin{equation}
\text{NLF}_0 = \frac{1}{K_1+K_2} \sum_{t=1}^{2} \sum_{k_t=1}^{K_t} \mathbb{I} \left ( N_{k_t t} \neq 0 \right ) \sum_{l_1=1}^{N_{k_t t}} \mathbb{I} \left ( z_{k_t t l_1 1} \geq -\infty \right ) 
\end{equation}

The right hand side of this equation can be separated into two terms, the contribution of latent NLs with z-samples in the range \(z \geq \zeta_1\) and those in the range \(-\infty \leq z < \zeta_1\). The first term yields the abscissa of the observed end-point, Eqn. \eqref{eq:froc-empirical-NLF11}. The 2nd term is:

\begin{equation}
\left. 
\begin{aligned} 
\text{2nd term}=&\left (\frac{1}{K_1+K_2} \right )\sum_{t=1}^{2} \sum_{k_t=1}^{K_t} \mathbb{I} \left ( N_{k_t t} \neq 0 \right ) \sum_{l_1=1}^{N_{k_t t}} \mathbb{I} \left ( -\infty \leq z_{k_t t l_1 1} < \zeta_1 \right )\\
=&\frac{\text{unknown number}}{K_1+K_2}
\end{aligned}
\right \} 
\label{eq:froc-empirical-NLF0a}
\end{equation}

It represents the contribution of unmarked NLs, i.e., latent NLs whose z-samples were below \(\zeta_1\). It determines how much further to the right the observer's NLF would have moved, relative to \(NLF_1\), if one could get the observer to lower the reporting criterion to \(-\infty\). \emph{Since the observer may not oblige, this term cannot, in general, be evaluated.} Therefore \(NLF_0\) cannot be evaluated. The basic problem is that \emph{unmarked latent NLs represent unobservable events}.

Turning our attention to \(LLF_0\):

\begin{equation}
\left.
\begin{aligned}
\text{LLF}_0 =& \frac{ \sum_{k_2=1}^{K_2} \sum_{l_2=1}^{L_{k_2 2}} \mathbb{I} \left ( z_{k_2 2 l_2 2} \geq  -\infty  \right ) }{L_T}\\
=& 1
\end{aligned}
\right \}
\label{eq:froc-empirical-LLF0}
\end{equation}

Unlike unmarked latent NLs, **unmarked lesions can safely be assigned the \(-\infty\) rating, because an unmarked lesion is an observable event*. The right hand side of Eqn. \eqref{eq:froc-empirical-LLF0} evaluates to unity. However, since the corresponding abscissa \(NLF_0\) is undefined, one cannot plot this point. It follows that one cannot extrapolate outside the observed end-point.

The formalism should not obscure the fact that the futility of extrapolation outside the observed end-point of the FROC is a fairly obvious property: one does not know how far to the right the abscissa of the observed end-point might extend if one could get the observer to report every latent NL.

\hypertarget{froc-empirical-froc-plot-illustration}{%
\subsection{Illustration with a dataset}\label{froc-empirical-froc-plot-illustration}}

The following code uses \texttt{dataset04} \citep{zanca2009evaluation} in the \texttt{RJafroc} package to illustrate an empirical FROC plot. The dataset has 5-treatments and 4 readers, so in principle one can generate 20 plots. In this example I have selected treatment 1 and reader 1 to produce the plot. The reader should experiment by running \texttt{PlotEmpiricalOperatingCharacteristics(dataset04,\ trts\ =\ 1,\ rdrs\ =\ 1,\ opChType\ =\ "FROC")\$Plot} with different treatments and readers specified.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ret <-}\StringTok{ }\KeywordTok{PlotEmpiricalOperatingCharacteristics}\NormalTok{(}
\NormalTok{  dataset04, }
  \DataTypeTok{trts =} \DecValTok{1}\NormalTok{, }\DataTypeTok{rdrs =} \DecValTok{1}\NormalTok{, }\DataTypeTok{opChType =} \StringTok{"FROC"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(ret}\OperatorTok{$}\NormalTok{Plot)}
\end{Highlighting}
\end{Shaded}

\includegraphics{03-froc-empirical_files/figure-latex/unnamed-chunk-1-1.pdf}

The study in question was a 5 rating FROC study. The lowest non-trivial point corresponds to the marks rating 5, the next higher one corresponds to marks rated 4 or 5, etc. The FROC plots vary widely but share the common characteristic that the operating points cannot move downward-left as one cumulates lower confidence level marks.

Shown next is calculation of the figure of merit for this dataset. All 20 values are shown. The value for \texttt{trt1} and \texttt{rdr1} is the area under the FROC plot shown above.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{UtilFigureOfMerit}\NormalTok{(dataset04, }\DataTypeTok{FOM =} \StringTok{"FROC"}\NormalTok{)}
\CommentTok{#>           rdr1      rdr3      rdr4       rdr5}
\CommentTok{#> trt1 0.2361972 0.1085035 0.2268486 0.09922535}
\CommentTok{#> trt2 0.2192077 0.2231338 0.4793310 0.18450704}
\CommentTok{#> trt3 0.1947359 0.1063028 0.2543662 0.15137324}
\CommentTok{#> trt4 0.2198768 0.1307394 0.3293662 0.13882042}
\CommentTok{#> trt5 0.1800528 0.1097535 0.3015141 0.16563380}
\end{Highlighting}
\end{Shaded}

\hypertarget{froc-empirical-ROC}{%
\section{The inferred-ROC plot}\label{froc-empirical-ROC}}

By adopting a rational rule for converting the mark-rating data per case to a single rating per case, and commonly the highest rating rule is used \footnote{The highest rating method was used in early FROC modeling in \citep{bunch1977free} and in \citep{swensson1996unified}, the latter in the context of LROC paradigm modeling.}, it is possible to infer ROC data from FROC mark-rating data.

\hypertarget{the-inferred-roc-rating}{%
\subsection{The inferred-ROC rating}\label{the-inferred-roc-rating}}

The rating of the highest rated mark in a case, or \(-\infty\) if the case has no marks, is defined as the inferred-ROC rating for the case. Inferred-ROC ratings on non-diseased cases are referred to as inferred-FP ratings and those on diseased cases as inferred-TP ratings.

When there is little possibility for confusion, the prefix ``inferred'' is suppressed. Using the by now familiar cumulation procedure, FP counts are cumulated to calculate FPF and likewise TP counts are cumulated to calculate TPF.

Definitions:

\begin{itemize}
\tightlist
\item
  \(FPF(\zeta)\) = cumulated inferred FP counts with z-sample \(\geq\) threshold \(\zeta\) divided by total number of non-diseased cases.
\item
  \(TPF(\zeta)\) = cumulated inferred TP counts with z-sample \(\geq\) threshold \(\zeta\) divided by total number of diseased cases
\end{itemize}

Definition of ROC plot:

\begin{itemize}
\tightlist
\item
  The ROC is the plot of inferred \(TPF(\zeta)\) vs.~inferred \(FPF(\zeta)\).
\item
  \emph{The plot includes a straight line extension from the observed end-point to (1,1)}.
\end{itemize}

\hypertarget{inferred-fpf}{%
\subsection{Inferred FPF}\label{inferred-fpf}}

The highest z-sample ROC false positive (FP) rating for non-diseased case \(k_1 1\) is defined by:

\begin{equation}
\left.
\begin{aligned}
FP_{k_1 1}=&\max_{l1} \left ( z_{k_1 1 l_1 1 } \mid l_1 \neq \varnothing \right ) \\
=& -\infty \mid l_1 = \varnothing  
 \end{aligned}
\right \}
\label{eq:froc-empirical-FP}
\end{equation}

If the case has at least one latent NL mark, then \(l_1 \neq \varnothing\), where \(\varnothing\) is the null set, and the first definition applies. If the case has no latent NL marks, then \(l_1 = \varnothing\), and the second definition applies. \(FP_{k_1 1}\) is the maximum z-sample over all latent marks occurring on non-diseased case \(k_1 1\), or \(-\infty\) if the case has no latent marks (this is allowed because a non-diseased case with no marks is an observable event). The corresponding false positive fraction is defined by:

\begin{equation}
\text{FPF}_r \equiv \text{FPF} \left ( \zeta_r \right ) = \frac{1}{K_1} \sum_{k_1=1}^{K_1} \mathbb{I} \left ( FP_{k_1 1} \geq \zeta_r\right )
\label{eq:froc-empirical-FPF}
\end{equation}

\hypertarget{inferred-tpf}{%
\subsection{Inferred TPF}\label{inferred-tpf}}

The inferred true positive (TP) z-sample for diseased case \(k_2 2\) is defined by:

\begin{equation}
TP_{k_2 2} = \text{max}_{l_1 l_2}\left ( z_{k_2 2 l_1 1} ,z_{k_2 2 l_2 2} \mid l_1 \neq \varnothing \right )
\label{eq:froc-empirical-TP1}
\end{equation}

or

\begin{equation}
TP_{k_2 2} = \textstyle\max_{l_2}  \left ( z_{k_2 2 l_2 2} \mid\left ( l_1 = \varnothing \land \left (\textstyle\max_{l_2}{\left (z_{k_2 2 l_2 2}  \right )} \neq -\infty  \right )  \right ) \right ) 
\label{eq:froc-empirical-TP2}
\end{equation}

or

\begin{equation}
TP_{k_2 2} = = -\infty \mid \left ( l_1 = \varnothing \land\left ( \textstyle\max_{l_2}{\left (z_{k_2 2 l_2 2}  \right )} = -\infty  \right )  \right )
\label{eq:froc-empirical-TP3}
\end{equation}

Here \(\land\) is the logical AND operator. An explanation is in order. Consider Eqn. \eqref{eq:froc-empirical-TP1}. There are two z-samples inside the \(\text{max}\) operator: \(z_{k_2 2 l_1 1} ,z_{k_2 2 l_2 2}\). The first z-sample is from a NL on a diseased case, as per the \(l_1 1\) subscripts, while the second is from a LL on the same diseased case, as per the \(l_2 2\) subscripts.

\begin{itemize}
\item
  If \(l_1 \neq \varnothing\) then Eqn. \eqref{eq:froc-empirical-TP1} applies, i.e., one takes the maximum over all z-samples, NLs and LLs, whichever is higher, on the diseased case.
\item
  If \(l_1 = \varnothing\) and at least one lesion is marked, then Eqn. \eqref{eq:froc-empirical-TP2} applies, i.e., one takes the maximum z-sample over all marked LLs.
\item
  If \(l_1 = \varnothing\) and no lesions are marked, then Eqn. \eqref{eq:froc-empirical-TP3} applies; this represents an unmarked diseased case; the \(-\infty\) rating assignment is justified because an unmarked diseased case is an observable event.
\end{itemize}

The inferred true positive fraction \(\text{TPF}_r\) is defined by:

\begin{equation}
\text{TPF}_r \equiv \text{TPF}(\zeta_r) = \frac{1}{K_2}\sum_{k_2=1}^{K_2} \mathbb{I}\left ( TP_{k_2 2} \geq \zeta_r \right )
\label{eq:froc-empirical-TPF}
\end{equation}

\hypertarget{froc-empirical-definition-empirical-auc-roc}{%
\subsection{Definition empirical plot and AUC}\label{froc-empirical-definition-empirical-auc-roc}}

The inferred empirical ROC plot connects adjacent points \(\left( \text{FPF}_r, \text{TPF}_r \right )\), including the origin (0,0), with straight lines plus a straight-line segment connecting the observed end-point to (1,1). Like a real ROC, this plot is constrained to lie within the unit square. The area under this plot is the empirical inferred ROC AUC, denoted \(A_{\text{ROC}}\).

\hypertarget{froc-empirical-roc-plot-illustration}{%
\subsection{Illustration with a dataset}\label{froc-empirical-roc-plot-illustration}}

The following code uses \texttt{dataset04} to illustrate an empirical ROC plot. The reader should experiment by running \texttt{PlotEmpiricalOperatingCharacteristics(dataset04,\ trts\ =\ 1,\ rdrs\ =\ 1,\ opChType\ =\ "ROC")\$Plot} with different treatments and readers specified.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ret <-}\StringTok{ }\KeywordTok{PlotEmpiricalOperatingCharacteristics}\NormalTok{(}
\NormalTok{  dataset04, }
  \DataTypeTok{trts =} \DecValTok{1}\NormalTok{, }\DataTypeTok{rdrs =} \DecValTok{1}\NormalTok{, }\DataTypeTok{opChType =} \StringTok{"ROC"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(ret}\OperatorTok{$}\NormalTok{Plot)}
\end{Highlighting}
\end{Shaded}

\includegraphics{03-froc-empirical_files/figure-latex/unnamed-chunk-4-1.pdf}

Shown next is calculation of the figure of merit for this dataset \footnote{In function \texttt{UtilFigureOfMerit} the \texttt{FOM} argument has to be set to \texttt{HrAuc}, which denotes the highest rating inferred-ROC AUC.}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{UtilFigureOfMerit}\NormalTok{(dataset04, }\DataTypeTok{FOM =} \StringTok{"HrAuc"}\NormalTok{)}
\CommentTok{#>         rdr1    rdr3    rdr4    rdr5}
\CommentTok{#> trt1 0.90425 0.79820 0.81175 0.86645}
\CommentTok{#> trt2 0.86425 0.84470 0.82050 0.87160}
\CommentTok{#> trt3 0.81295 0.81635 0.75275 0.85730}
\CommentTok{#> trt4 0.90235 0.83150 0.78865 0.87980}
\CommentTok{#> trt5 0.84140 0.77300 0.77115 0.84800}
\end{Highlighting}
\end{Shaded}

\hypertarget{froc-empirical-AFROC}{%
\section{The alternative FROC (AFROC) plot}\label{froc-empirical-AFROC}}

\begin{itemize}
\tightlist
\item
  Fig. 4 in \citep{bunch1977free} anticipated another way of visualizing FROC data. I subsequently termed\footnote{The late Prof.~Richard Swensson did not like my choice of the word ``alternative'' in naming this operating characteristic. I had no idea in 1989 how important this operating characteristic would later turn out to be, otherwise a more meaningful name might have been proposed.} this the \emph{alternative FROC (AFROC)} plot \citep{chakraborty1989maximum}.
\item
  The empirical AFROC is defined as the plot of \(\text{LLF}(\zeta_r)\) along the ordinate vs.~\(\text{FPF}(\zeta_r)\) along the abscissa.
\item
  \(\text{LLF}_r \equiv \text{LLF}(\zeta_r)\) was defined in Eqn. \eqref{eq:froc-empirical-LLFr}.
\item
  \(\text{FPF}_r \equiv \text{FPF}(\zeta_r)\) was defined in Eqn. \eqref{eq:froc-empirical-FPF}.
\end{itemize}

\hypertarget{froc-empirical-definition-empirical-auc-afroc}{%
\subsection{Definition empirical plot and AUC}\label{froc-empirical-definition-empirical-auc-afroc}}

The empirical AFROC plot connects adjacent operating points \(\left( \text{FPF}_r, \text{LLF}_r \right )\), including the origin (0,0) and (1,1), with straight lines. The area under this plot is the empirical AFROC AUC, denoted \(A_{\text{AFROC}}\).

Key points:

\begin{itemize}
\tightlist
\item
  The ordinates (LLF) of the FROC and AFROC are identical.
\item
  The abscissa (FPF) of the ROC and AFROC are identical.
\item
  The AFROC is, in this sense, a hybrid plot, incorporating aspects of both ROC and FROC plots.
\item
  Unlike the empirical FROC, whose observed end-point has the semi-constrained property, \emph{the AFROC end-point is constrained to within the unit square}, as detailed next.
\end{itemize}

\hypertarget{froc-empirical-AFROC-constrained}{%
\subsection{The constrained observed end-point of the AFROC}\label{froc-empirical-AFROC-constrained}}

Since \(\zeta_{R_{FROC}+1} = \infty\), according to Eqn. \eqref{eq:froc-empirical-LLFr} and Eqn. \eqref{eq:froc-empirical-FPF}, \(r = R_{FROC}+1\) yields the trivial operating point (0,0). Likewise, since \(\zeta_0 = -\infty\), \(r = 0\) yields the trivial point (1,1):

\begin{equation}
\left.
\begin{aligned} 
\text{FPF}_{R_{FROC}+1} =& \frac{1}{K_1} \sum_{k_1=1}^{K_1} \mathbb{I} \left ( FP_{k_1 1} \geq \infty \right )\\
=& 0\\
\text{LLF}_{R_{FROC}+1} =& \frac{1}{L_T} \sum_{k_2=1}^{K_2} \sum_{l_2=1}^{L_{k_2 2}}\mathbb{I} \left ( LL_{k_2 2 l_2 2} \geq \infty \right )\\
=& 0
\end{aligned}
\right \}
\label{eq:froc-empirical-FPF-LLF-last}
\end{equation}

and

\begin{equation}
\left.
\begin{aligned} 
\text{FPF}_0 =& \frac{1}{K_1} \sum_{k_1=1}^{K_1} \mathbb{I} \left ( FP_{k_1 1} \geq -\infty \right )\\
=& 1\\
\text{LLF}_0 =& \frac{1}{L_T} \sum_{k_2=1}^{K_2} \sum_{l_2=1}^{L_{k_2 2}}\mathbb{I} \left ( LL_{k_2 2 l_2 2} \geq -\infty \right )\\
=& 1
\end{aligned}
\right \}
\label{eq:froc-empirical-FPF0-LLF0}
\end{equation}

Because every non-diseased case is assigned a rating, and is therefore counted, the right hand side of the first equation in \eqref{eq:froc-empirical-FPF0-LLF0} evaluates to unity. This is obvious for marked cases. Since each unmarked case also gets a rating, albeit a \(-\infty\) rating, it is also counted (the argument of the indicator function in Eqn. \eqref{eq:froc-empirical-FPF0-LLF0} is true even when the inferred-FP rating is \(-\infty\)).

\hypertarget{froc-empirical-afroc-plot-illustration}{%
\subsection{Illustration with a dataset}\label{froc-empirical-afroc-plot-illustration}}

The following code uses \texttt{dataset04} to illustrate an empirical AFROC plot. The reader should experiment by running \texttt{PlotEmpiricalOperatingCharacteristics(dataset04,\ trts\ =\ 1,\ rdrs\ =\ 1,\ opChType\ =\ "AFROC")\$Plot} with different treatments and readers specified.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ret <-}\StringTok{ }\KeywordTok{PlotEmpiricalOperatingCharacteristics}\NormalTok{(}
\NormalTok{  dataset04, }
  \DataTypeTok{trts =} \DecValTok{1}\NormalTok{, }\DataTypeTok{rdrs =} \DecValTok{1}\NormalTok{, }\DataTypeTok{opChType =} \StringTok{"AFROC"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(ret}\OperatorTok{$}\NormalTok{Plot)}
\end{Highlighting}
\end{Shaded}

\includegraphics{03-froc-empirical_files/figure-latex/unnamed-chunk-7-1.pdf}

Shown next is calculation of the figure of merit for this dataset.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{UtilFigureOfMerit}\NormalTok{(dataset04, }\DataTypeTok{FOM =} \StringTok{"AFROC"}\NormalTok{)}
\CommentTok{#>           rdr1      rdr3      rdr4      rdr5}
\CommentTok{#> trt1 0.7427113 0.7104930 0.7003169 0.7909859}
\CommentTok{#> trt2 0.7586972 0.7161620 0.7225352 0.7927465}
\CommentTok{#> trt3 0.6983451 0.6955282 0.6777817 0.7547535}
\CommentTok{#> trt4 0.7817606 0.7234507 0.7132746 0.8136268}
\CommentTok{#> trt5 0.7169718 0.6690845 0.6587324 0.7682042}
\end{Highlighting}
\end{Shaded}

\hypertarget{froc-empirical-wAFROC}{%
\section{The weighted-AFROC plot (wAFROC) plot}\label{froc-empirical-wAFROC}}

The AFROC ordinate defined in Eqn. \eqref{eq:froc-empirical-LLFr} gives equal importance to every lesion in a case. Therefore, a case with more lesions will have more influence on the AFROC (see TBA Chapter 14 for an explicit demonstration of this fact). This is undesirable since each case (i.e., patient) should get equal importance in the analysis -- as with ROC analysis, one wishes to draw conclusions about the population of cases and each case is regarded as an equally valid sample from the population. In particular, one does not want the analysis to be skewed towards cases with greater than the average number of lesions. \footnote{Historical note: I became aware of how serious this issue could be when a researcher contacted me about using FROC methodology for nuclear medicine bone scan images, where the number of lesions on diseased cases can vary from a few to a hundred!}

Another issue is that the AFROC assigns equal \emph{clinical} importance to each lesion in a case. Lesion weights were introduced \citep{RN1385} to allow for the possibility that the clinical importance of finding a lesion might be lesion-dependent \citep{RN1966}. For example, it is possible that a diseased cases has lesions of two types with differing clinical importance; the figure-of-merit should give more credit to finding the more clinically important one. Clinical importance could be defined as the mortality associated with the specific lesion type; these can be obtained from epidemiological studies \citep{desantis2011breast}.

Let \(W_{k_2 l_2} \geq 0\) denote the \emph{weight} (i.e., short for clinical importance) of lesion \(l_2\) in diseased case \(k_2\) (since weights are only applicable to diseased cases one can, without ambiguity, drop the case-level and location-level truth subscripts, i.e., the notation \(W_{k_2 2 l_2 2}\) would be superfluous). For each diseased case \(k_2 2\) the weights are subject to the constraint:

\begin{equation}
\sum_{l_2 =1 }^{L_{k_2 2}} W_{k_2 l_2} = 1
\label{eq:froc-empirical-weights-constraint}
\end{equation}

The constraint assures that the each diseased case exerts equal importance in determining the weighted-AFROC (wAFROC) operating characteristic, regardless of the number of lesions in it (see TBA Chapter 14 for a demonstration of this fact).

The weighted lesion localization fraction \(\text{wLLF}_r\) is defined by \citep{RN2484}:

\begin{equation}
\text{wLLF}_r \equiv \text{wLLF}\left ( \zeta_r \right ) = \frac{1}{K_2}\sum_{k_2=1}^{K_2}\sum_{l_2=1}^{L_{k_2 2}}W_{k_2 l_2} \mathbb{I}\left ( z_{k_2 l_2 2} \geq \zeta_r \right )
\label{eq:froc-empirical-wLLFr}
\end{equation}

\hypertarget{froc-empirical-definition-empirical-auc-wafroc}{%
\subsection{Definition empirical plot and AUC}\label{froc-empirical-definition-empirical-auc-wafroc}}

The empirical wAFROC plot connects adjacent operating points \(\left ( \text{FPF}_r, \text{wLLF}_r \right )\), including the origin (0,0), with straight lines plus a straight-line segment connecting the observed end-point to (1,1). The area under this plot is the empirical weighted-AFROC AUC, denoted \(A_{\text{wAFROC}}\).

\hypertarget{froc-empirical-wafroc-plot-illustration}{%
\subsection{Illustration with a dataset}\label{froc-empirical-wafroc-plot-illustration}}

The following code uses \texttt{dataset04} to illustrate an empirical ROC plot. The reader should experiment by running \texttt{PlotEmpiricalOperatingCharacteristics(dataset04,\ trts\ =\ 1,\ rdrs\ =\ 1,\ opChType\ =\ "wAFROC")\$Plot} with different treatments and readers specified.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ret <-}\StringTok{ }\KeywordTok{PlotEmpiricalOperatingCharacteristics}\NormalTok{(}
\NormalTok{  dataset04, }\DataTypeTok{trts =} \DecValTok{1}\NormalTok{, }\DataTypeTok{rdrs =} \DecValTok{1}\NormalTok{, }\DataTypeTok{opChType =} \StringTok{"wAFROC"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(ret}\OperatorTok{$}\NormalTok{Plot)}
\end{Highlighting}
\end{Shaded}

\includegraphics{03-froc-empirical_files/figure-latex/unnamed-chunk-10-1.pdf}

Shown next is calculation of the figure of merit for this dataset.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{UtilFigureOfMerit}\NormalTok{(dataset04, }\DataTypeTok{FOM =} \StringTok{"wAFROC"}\NormalTok{)}
\CommentTok{#>           rdr1      rdr3      rdr4      rdr5}
\CommentTok{#> trt1 0.7792667 0.7248917 0.7036250 0.8050917}
\CommentTok{#> trt2 0.7870000 0.7269000 0.7226167 0.8037833}
\CommentTok{#> trt3 0.7296917 0.7157583 0.6723083 0.7726583}
\CommentTok{#> trt4 0.8101333 0.7431167 0.6943583 0.8294083}
\CommentTok{#> trt5 0.7488000 0.6822750 0.6551750 0.7712500}
\end{Highlighting}
\end{Shaded}

\hypertarget{froc-empirical-numerical-illustration}{%
\section{AFROC vs.~wAFROC}\label{froc-empirical-numerical-illustration}}

The wAFROC and AFROC, particularly the concept that the wAFROC gives equal importance to each diseased case while the AFROC gives more important to diseased cases with more lesions, are perhaps best illustrated with a numerical example. The dataset consists of \(K_1 = 4\) non-diseased and \(K_2 = 4\) diseased cases. The first two diseased cases have one lesion each, and the remaining two have two lesions each.

Shown next is the \texttt{NL} ratings array which has 8 rows, corresponding to the total number of cases, and 2 columns, corresponding to the maximum number of NLs and LLs per case (notice there are two entries for case \#3). The negative infinities represent unmarked locations.

\begin{verbatim}
#> 
#> NL ratings:
#>      [,1] [,2]
#> [1,] -Inf -Inf
#> [2,]  0.5 -Inf
#> [3,]  0.7  0.6
#> [4,] -0.3 -Inf
#> [5,]  1.5 -Inf
#> [6,] -Inf -Inf
#> [7,] -Inf -Inf
#> [8,] -Inf -Inf
\end{verbatim}

Shown next is the \texttt{FP} ratings array. Since FPs are only possible on non-diseased cases, this is a length 4 row-vector. Each value is the maximum of the two \texttt{NL} ratings for the corresponding non-diseased case. As an example, for case \#3 the maximum of the two \texttt{NL} values is 0.7.

\begin{verbatim}
#> 
#> FP ratings:
#> [1] -Inf  0.5  0.7 -0.3
\end{verbatim}

Show next is the sorted \texttt{FP} ratings.

\begin{verbatim}
#> [1] -Inf -0.3  0.5  0.7
\end{verbatim}

The sorting makes it easy to construct the \texttt{FPF} values, shown next.

\begin{verbatim}
#> 
#> FPF values:
#>  0.000 0.000 0.000 0.000 0.000 0.250 0.500 0.500 0.750 1.000
\end{verbatim}

The first non-zero \texttt{FPF} value is 0.25, which occurs when the sliding threshold is lowered past the highest \texttt{FP} value, namely 0.7. The 0.25 comes from 1 \texttt{FP} case divided by 4 non-diseased cases. The next \texttt{FPF} value is 0.5, which occurs when the sliding threshold is lowered past the next-highest \texttt{FP} value, namely 0.5. The 0.5 comes from 2 divided by 4. The next \texttt{FPF} value is 0.75 and the last \texttt{FPF} value is unity.

Shown next is the \texttt{LL} ratings array:

\begin{verbatim}
#> 
#> LL ratings:
#>      [,1] [,2]
#> [1,]  0.9 -Inf
#> [2,] -0.2 -Inf
#> [3,]  1.6 -Inf
#> [4,]  3.0    2
\end{verbatim}

Show next is the sorted \texttt{LL} ratings.

\begin{verbatim}
#> [1] -Inf -Inf -Inf -0.2  0.9  1.6  2.0  3.0
\end{verbatim}

The sorting makes it easy to construct the \texttt{LLF} values, shown next.

\begin{verbatim}
#> 
#> LLF values:
#>  0.000 0.167 0.333 0.500 0.667 0.667 0.667 0.833 0.833 1.000
\end{verbatim}

The first non-zero \texttt{LLF} value is 0.167, which occurs when the sliding threshold is lowered past the highest \texttt{LL} value, namely 3. The 0.167 comes from 1 LL divided by 6 lesions. The next \texttt{LLF} value is 0.333, which occurs when the sliding threshold is lowered past the next-highest \texttt{LL} value, namely 2 (2/6 = 0.333). The next \texttt{LLF} value is 0.5, which occurs when the sliding threshold is lowered past 1.6 (3/6 = 0.5), and so on.

Show next is the lesion weights array:

\begin{verbatim}
#> 
#> lesion weights:
#>      [,1] [,2]
#> [1,]  1.0 -Inf
#> [2,]  1.0 -Inf
#> [3,]  0.1  0.9
#> [4,]  0.9  0.1
\end{verbatim}

Since the first two diseased cases have one lesion each, the {[}1,1{]} and {[}2,1{]} elements of the the weight array are each equal to unity and the {[}1,2{]} and {[}2,2{]} elements are each equal to negative infinity, which is being used as a missing value. For diseased case \#3 the first lesion has weight 0.1 while the second lesion has weight 0.9 (the weights must sum to unity). For diseased case \#4 the weights are reversed.

The sorted \texttt{LL} ratings array and the weights are used to construct the \texttt{wLLF} values shown next.

\begin{verbatim}
#> 
#> wLLF values:
#>  0.000 0.225 0.250 0.275 0.525 0.525 0.525 0.775 0.775 1.000
\end{verbatim}

The first non-zero \texttt{wLLF} value is 0.225, which occurs when the sliding threshold is lowered past the highest \texttt{LL} value, namely 3. Since this comes from the first lesion on diseased case \#4, whose weight is 0.9, the corresponding incremental vertical jump is 1 divided by 4 (\emph{sic}) times 0.9. Notice that we are dividing by 4, the total number of diseased cases, not 6 as in the \texttt{LLF} example.

The next \texttt{wLLF} value is 0.25, which occurs when the sliding threshold is lowered past the next-highest \texttt{LL} value, namely 2, which comes from the 2nd lesion on the fourth diseased case with weight 0.1. The incremental jump in \texttt{wLLF} is 1 divided by 4 times 0.1, which is 0.025. The net \texttt{wLLF} value corresponding to these two lesions is \(1/4*0.9 + 1/4*0.1 = 1/4 = 0.25\). The two lesions on diseased case \#4 contribute 0.25 in \texttt{wLLF} increment. In contrast, they contribute \(2/6 = 0.333\) in \texttt{LLF} increment, showing explicitly that the AFROC gives greater importance to diseased cases with more lesions while the wAFROC does not.

The next \texttt{wLLF} value is 0.275, which occurs when the sliding threshold is lowered past 1.6, which ratings comes from the first lesion on diseased case \#3, with weight 0.1, \(1/4*0.9 + 1/4*0.1 + 1/4*0.1 = 0.275\), and so on.

The reader should complete these hand-calculations to reproduce all of the \texttt{wLLF} values shown above.

Shown in Fig. \ref{fig:plots-afrocPlot-wafrocPlot} are the empirical AFROC and wAFROC plots.

\begin{figure}
\centering
\includegraphics{03-froc-empirical_files/figure-latex/plots-afrocPlot-wafrocPlot-1.pdf}
\caption{\label{fig:plots-afrocPlot-wafrocPlot}Left: AFROC plot; Right: corresponding wAFROC plot.}
\end{figure}

The operating points can be used to numerically calculate the AUCs under the empirical AFROC and wAFROC plots, as done in the following code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{afroc_auc <-}\StringTok{ }\FloatTok{0.5} \OperatorTok{*}\StringTok{ }\DecValTok{4} \OperatorTok{/}\StringTok{ }\DecValTok{6} \OperatorTok{+}\StringTok{ }\FloatTok{0.25} \OperatorTok{*}\StringTok{ }\DecValTok{5} \OperatorTok{/}\DecValTok{6} \OperatorTok{+}\StringTok{ }
\StringTok{ }\DecValTok{5} \OperatorTok{/}\DecValTok{6} \OperatorTok{*}\StringTok{ }\FloatTok{0.25} \OperatorTok{+}\StringTok{  }\NormalTok{(}\DecValTok{1} \OperatorTok{-}\StringTok{ }\DecValTok{5} \OperatorTok{/}\DecValTok{6}\NormalTok{) }\OperatorTok{*}\StringTok{ }\FloatTok{0.25} \OperatorTok{/}\DecValTok{2}

\NormalTok{wafroc_auc <-}\StringTok{ }\FloatTok{0.5} \OperatorTok{*}\StringTok{ }\FloatTok{0.525} \OperatorTok{+}\StringTok{ }\FloatTok{0.25} \OperatorTok{*}\StringTok{ }\FloatTok{0.775} \OperatorTok{+}\StringTok{ }
\StringTok{  }\FloatTok{0.775} \OperatorTok{*}\StringTok{ }\FloatTok{0.25} \OperatorTok{+}\StringTok{  }\NormalTok{(}\DecValTok{1} \OperatorTok{-}\StringTok{ }\FloatTok{0.775}\NormalTok{) }\OperatorTok{*}\StringTok{ }\FloatTok{0.25} \OperatorTok{/}\DecValTok{2}

\NormalTok{afroc_auc}
\CommentTok{#> [1] 0.7708333}
\NormalTok{wafroc_auc}
\CommentTok{#> [1] 0.678125}
\end{Highlighting}
\end{Shaded}

The same AUC results are obtained using the function \texttt{UtilFigureOfMerit}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cat}\NormalTok{(}\StringTok{"}\CharTok{\textbackslash{}n}\StringTok{AFROC AUC = "}\NormalTok{, }\KeywordTok{as.numeric}\NormalTok{(}\KeywordTok{UtilFigureOfMerit}\NormalTok{(frocData, }\DataTypeTok{FOM =} \StringTok{"AFROC"}\NormalTok{)),}\StringTok{"}\CharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\CommentTok{#> }
\CommentTok{#> AFROC AUC =  0.7708333}
\KeywordTok{cat}\NormalTok{(}\StringTok{"wAFROC AUC = "}\NormalTok{, }\KeywordTok{as.numeric}\NormalTok{(}\KeywordTok{UtilFigureOfMerit}\NormalTok{(frocData, }\DataTypeTok{FOM =} \StringTok{"wAFROC"}\NormalTok{)),}\StringTok{"}\CharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\CommentTok{#> wAFROC AUC =  0.678125}
\end{Highlighting}
\end{Shaded}

\hypertarget{froc-empirical-AFROC1}{%
\section{The AFROC1 plot}\label{froc-empirical-AFROC1}}

Historically the AFROC originally used a different definition of FPF, which is retrospectively termed the AFROC1 plot. Since NLs can occur on diseased cases, it is possible to define an inferred-``FP'' rating on a \emph{diseased case} as the maximum of all NL ratings on the case, or \(-\infty\) if the case has no NLs. The quotes emphasize that this is non-standard usage of ROC terminology: in an ROC study, a FP can only occur on a \emph{non-diseased case}. Since both case-level truth states are allowed, the highest false positive (FP) z-sample for case \(k_t t\) is {[}the ``1'' superscript below is necessary to distinguish it from Eqn. \eqref{eq:froc-empirical-FP}{]}:

\begin{equation}
\left.
\begin{aligned}
FP_{k_t t}^1 =& \max_{l_1} \left ( z_{k_t t l_1 1 } \mid  l_1 \neq \varnothing \right )\\
=& -\infty \mid l_1 = \varnothing
\end{aligned}
\right \}
\label{eq:froc-empirical-FP1}
\end{equation}

\(FP_{k_t t}^1\) is the maximum over all latent NL marks, labeled by the location index \(l_1\), occurring in case \(k_t t\), or \(-\infty\) if \(l_1 = \varnothing\). The corresponding false positive fraction \(FPF_r^1\) is defined by {[}the ``1'' superscript is necessary to distinguish it from Eqn. \eqref{eq:froc-empirical-FPF}{]}:

\begin{equation}
FPF_r^1 \equiv FPF_r^1\left ( \zeta_r \right ) = \frac{1}{K_1+K_2}\sum_{t=1}^{2}\sum_{k_t=1}^{K_t} \mathbb{I}\left ( FP_{k_t t}^1 \geq \zeta_r \right )
\label{eq:froc-empirical-FPF1}
\end{equation}

Note the subtle differences between Eqn. \eqref{eq:froc-empirical-FPF} and Eqn. \eqref{eq:froc-empirical-FPF1}. The latter counts ``FPs'' on non-diseased and diseased cases while Eqn. \eqref{eq:froc-empirical-FPF} counts FPs on non-diseased cases only, and for that reason the denominators in the two equations are different. The advisability of allowing a diseased case to be both a TP and a FP is questionable from both clinical and statistical considerations. However, this operating characteristic can be useful in applications where all or almost all cases are diseased.

\hypertarget{froc-empirical-definition-empirical-auc-afroc1}{%
\subsection{Definition empirical plot and AUC}\label{froc-empirical-definition-empirical-auc-afroc1}}

The empirical AFROC1 plot connects adjacent operating points \(\left ( FPF_r^1, \text{LLF}_r \right )\), including the origin (0,0) and (1,1), with straight lines. The only difference between AFROC1 and the AFROC plot is in the x-axis. The area under this plot is the empirical AFROC1 AUC, denoted \(A_{\text{AFROC1}}\).

\hypertarget{froc-empirical-afroc1-plot-illustration}{%
\subsection{Illustration with a dataset}\label{froc-empirical-afroc1-plot-illustration}}

The following code uses \texttt{dataset04} to illustrate an empirical ROC plot. The reader should experiment by running \texttt{PlotEmpiricalOperatingCharacteristics(dataset04,\ trts\ =\ 1,\ rdrs\ =\ 1,\ opChType\ =\ "AFROC1")\$Plot} with different treatments and readers specified.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ret <-}\StringTok{ }\KeywordTok{PlotEmpiricalOperatingCharacteristics}\NormalTok{(}
\NormalTok{  dataset04, }
  \DataTypeTok{trts =} \DecValTok{1}\NormalTok{, }\DataTypeTok{rdrs =} \DecValTok{1}\NormalTok{, }\DataTypeTok{opChType =} \StringTok{"AFROC1"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(ret}\OperatorTok{$}\NormalTok{Plot)}
\end{Highlighting}
\end{Shaded}

\includegraphics{03-froc-empirical_files/figure-latex/unnamed-chunk-24-1.pdf}

Shown next is calculation of the figure of merit for this dataset.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{UtilFigureOfMerit}\NormalTok{(dataset04, }\DataTypeTok{FOM =} \StringTok{"AFROC1"}\NormalTok{)}
\CommentTok{#>           rdr1      rdr3      rdr4      rdr5}
\CommentTok{#> trt1 0.7744718 0.7157218 0.7229225 0.7913908}
\CommentTok{#> trt2 0.7826585 0.7278169 0.7364437 0.7897887}
\CommentTok{#> trt3 0.7412852 0.6868310 0.6946303 0.7573415}
\CommentTok{#> trt4 0.8087852 0.7346831 0.7343486 0.8155634}
\CommentTok{#> trt5 0.7580810 0.6825704 0.6643662 0.7742782}
\end{Highlighting}
\end{Shaded}

\hypertarget{froc-empirical-wAFROC1}{%
\section{The weighted-AFROC1 (wAFROC1) plot}\label{froc-empirical-wAFROC1}}

\hypertarget{froc-empirical-definition-empirical-auc-wafroc1}{%
\subsection{Definition empirical plot and AUC}\label{froc-empirical-definition-empirical-auc-wafroc1}}

The empirical weighted-AFROC1 (wAFROC1) plot connects adjacent operating points \(\left ( FPF_r^1, \text{wLLF}_r \right )\), including the origin (0,0) and (1,1), with straight lines. The only difference between it and the wAFROC plot is in the x-axis. The area under this plot is the empirical weighted-AFROC AUC, denoted \(A_{\text{wAFROC1}}\).

\hypertarget{froc-empirical-wafroc1-plot-illustration}{%
\subsection{Illustration with a dataset}\label{froc-empirical-wafroc1-plot-illustration}}

The following code uses \texttt{dataset04} to illustrate an empirical wAFROC plot1. The reader should experiment by running \texttt{PlotEmpiricalOperatingCharacteristics(dataset04,\ trts\ =\ 1,\ rdrs\ =\ 1,\ opChType\ =\ wAFROC1")\$Plot} with different treatments and readers specified.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ret <-}\StringTok{ }\KeywordTok{PlotEmpiricalOperatingCharacteristics}\NormalTok{(}
\NormalTok{  dataset04, }
  \DataTypeTok{trts =} \DecValTok{1}\NormalTok{, }\DataTypeTok{rdrs =} \DecValTok{1}\NormalTok{, }\DataTypeTok{opChType =} \StringTok{"wAFROC1"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(ret}\OperatorTok{$}\NormalTok{Plot)}
\end{Highlighting}
\end{Shaded}

\includegraphics{03-froc-empirical_files/figure-latex/unnamed-chunk-27-1.pdf}

Shown next is calculation of the figure of merit for this dataset.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{UtilFigureOfMerit}\NormalTok{(dataset04, }\DataTypeTok{FOM =} \StringTok{"wAFROC1"}\NormalTok{)}
\CommentTok{#>           rdr1      rdr3      rdr4      rdr5}
\CommentTok{#> trt1 0.8068333 0.7298917 0.7262042 0.8058542}
\CommentTok{#> trt2 0.8084625 0.7379917 0.7363083 0.8010167}
\CommentTok{#> trt3 0.7680875 0.7075583 0.6890208 0.7743875}
\CommentTok{#> trt4 0.8348750 0.7533917 0.7160250 0.8308333}
\CommentTok{#> trt5 0.7857708 0.6953292 0.6605167 0.7774000}
\end{Highlighting}
\end{Shaded}

\hypertarget{froc-empirical-plots}{%
\section{Plots of FROC, AFROC and wAFROC AUCs vs.~ROC AUC}\label{froc-empirical-plots}}

Plots of \(A_{\text{FROC}}\), \(A_{\text{AFROC}}\) and \(A_{\text{wAFROC}}\) vs.~\(A_{\text{ROC}}\) were generated for the dataset used in the previous illustrations.

The following is the plot of \(A_{\text{FROC}}\) vs.~\(A_{\text{ROC}}\). There are 20 points on the plot corresponding to 5 treatments and 4 readers. The straight line is a least squares fit. \(A_{\text{ROC}}\) is assumed to be the gold standard. Note the poor correlation between \(A_{\text{FROC}}\) and \(A_{\text{ROC}}\). The slope is negative and there is much scatter.

\includegraphics{03-froc-empirical_files/figure-latex/unnamed-chunk-30-1.pdf}

Evidently \(A_{\text{FROC}}\) does not correlate well with \(A_{\text{ROC}}\). The reason should be fairly obvious. The FROC is unconstrained in the NLF direction and the area under the plot rewards an observer who generates more and more NLs while not generating more LLs, i.e., as the operating point moves further to the right along the flat part of the plot. In fact the perfect observer, Section \texttt{\textbackslash{}@ref(froc-paradigm-solar-analogy)}, whose FROC plot is the vertical line connecting (0,0) and (0,1) has zero \(A_{\text{FROC}}\)! One can try ot avoid this problem by limiting the area under the FROC to that between \(\text{NLF} = 0\) and \(\text{NLF} = x\) where \(x\) is some arbitrarily chosen fixed value -- indeed this procedure has been used by many CAD algorithm designers. Since the choice of \(x\) is arbitrary the procedure would be subjective and totally dependent on the algorithm designer. Moreover it would not solve the problem that the perfect observer would still yield \(A_{\text{FROC}} = 0\). The perfect observer problem is not academic as the method would fail for any observer with \(\text{NLF}_{max} < x\). For such an observer the partial area would be undefined. This would force the algorithm designer to chose \(x\) as the minimum of all \(\text{NLF}_{max}\) values over all observers and treatments, which would exclude a lot of data from the analysis leading to a severe statistical power penalty.

The basic problem is that the FROC plot is unconstrained in the NLF direction.

The following is the plot of \(A_{\text{AFROC}}\) vs.~\(A_{\text{ROC}}\). This time there is a strong positive correlation between the two. The reason is that the AFROC is fully contained in the unit square. An observer who generates more NL marks would in fact yield smaller \(A_{\text{AFROC}}\) - this is explained in a later section TBA .

\includegraphics{03-froc-empirical_files/figure-latex/unnamed-chunk-31-1.pdf}

The following is the plot of \(A_{\text{wAFROC}}\) vs.~\(A_{\text{ROC}}\). Again, there is a strong positive correlation between the two. The wAFROC is also fully contained in the unit square.

\includegraphics{03-froc-empirical_files/figure-latex/unnamed-chunk-32-1.pdf}

\hypertarget{froc-empirical-Discussion}{%
\section{TBA Discussion}\label{froc-empirical-Discussion}}

TBA This chapter started with the difference between latent and actual marks and the notation to describe FROC data. The notation is used in deriving formulae for FROC, inferred-ROC, AFROC, wAFROC, AFROC1, wAFROC1 and EFROC operating characteristics. In each case an area measure was defined. With the exception of the FROC plot, all operating characteristics defined in this chapter are contained in the unit square. Discussion of the preferred operating characteristic is deferred to a subsequent chapter TBA.

FROC data consists of mark-rating pairs. In this chapter a distinction is made between latent and actual marks. This is followed by a table summarizing FROC notation. This is a key table which will be used in later chapters. Section \texttt{\textbackslash{}@ref(froc-paradigm-froc-plot)} introduced the empirical FROC plot. This chapter presents mathematical expressions for this and other empirical plots possible with FROC data: the inferred-ROC, the alternative FROC, the weighted alternative FROC, and others. Operating characteristics are \emph{visual} depicters of performance. Scalar quantities, typically area measures derived from operating characteristics, are \emph{quantitative} measures of performance, termed \emph{figures of merit} (FOMs). This chapter defines an area measure for each empirical operating characteristic. An FROC dataset is used to illustrate the plots and area measures. With the exception of the FROC, all empirical plots include a straight line extension from the observed end-point to (1,1). The correlation between the area measures is qualitatively examined via plots. It is shown that for this dataset the FROC area measure correlates poorly with that under the ROC curve, whereas the other measures correlate better. This is explained by the fact that, unlike the other measures, the FROC plot is not contained within the unit square.

\hypertarget{froc-empirical-references}{%
\section{References}\label{froc-empirical-references}}

\hypertarget{froc-meanings}{%
\chapter{Meanings of FROC figures of merit}\label{froc-meanings}}

\hypertarget{froc-meanings-how-much-finished}{%
\section{TBA How much finished}\label{froc-meanings-how-much-finished}}

50\%

\hypertarget{froc-meanings-intro}{%
\section{Introduction}\label{froc-meanings-intro}}

Chapter TBA \texttt{\textbackslash{}@ref(froc-empirical)} focused on empirical plots possible with FROC data, for example, the FROC, AFROC, wAFROC and inferred ROC plots. Expressions were given for computing \emph{operating points} for each plot from z-samples. Because of the ambiguity in ordering the two values associated with each operating points (e.g., sensitivity-specificity pairs in ROC plots), operating points should not be used as figures of merit. Rather one should use \emph{area measures} derived from operating characteristics. This chapter is devoted to a number of such measures for FROC data.

A generic empirical area under a plot is denoted \(\text{A}_{oc}\) where the ``oc'' subscript denotes the applicable operating characteristic. For example, the area under the empirical wAFROC is denoted \(\text{A}_{wAFROC}\). Calculating areas from operating points using planimetry or geometry is tedious at best. Needed are formulae for calculating them directly from ratings. In this sense this chapter is the extension to the FROC paradigm of Chapter TBA (empirical-auc) where it was shown that the area under the empirical ROC plot \(\text{A}_{ROC}\) equaled the Wilcoxon statistic calculated directly from the ratings, i.e., the Bamber theorem \citep{RN2174}.

I make a distinction between \emph{empirical AUC under a plot}, i.e., an area measure, and a \emph{FOM-statistic}, generically denoted \(\theta\), that can be computed directly from the ratings. While any function of the ratings is a possible FOM-statistic, whether it is useful depends upon whether it can be related to the area under an operating characteristic. This chapter derives formulas for FOM-statistics \(\theta_{oc}\), which yield the same values as the areas \(\text{A}_{oc}\) under the corresponding empirical operating characteristics. The meanings of these FOM-statistics are discussed \citep{RN2484}.

Here is the organization of the chapter.

\begin{itemize}
\item
  Expressions for the empirical AFROC FOM-statistic \(\theta_{AFROC}\) and the empirical weighted-AFROC FOM-statistic \(\theta_{wAFROC}\) are presented and their limiting values for chance-level and perfect performances are explored.
\item
  Two important theorems are stated, whose proofs are in {[}TBA Online Appendix 14.A{]}.
\item
  The first theorem proves the equality between the empirical wAFROC FOM-statistic \(\theta_{wAFROC}\) and the area \(\text{A}_{wAFROC}\) under the empirical wAFROC plot. {[}A similar equality applies to the empirical AFROC FOM-statistic \(\theta_{wAFROC}\) and the area \(\text{A}_{wAFROC}\) under the empirical AFROC plot.{]}
\item
  The second theorem derives an expression for the area under the straight-line extension of the wAFROC from the observed end-point to (1,1), and explains why it is essential to include this area.
\item
  A small simulated-dataset is used to illustrate how NL and LL ratings and lesion weights determine the wAFROC empirical plot.
\item
  It demonstrates that the wAFROC gives equal importance to all diseased cases, a desirable statistical characteristic.
\item
  Corresponding results, but ignoring the weights, show that the AFROC gives excessive importance to cases with more lesions.
\item
  A physical interpretation of the AUC or FOM-statistics is given. It shows explicitly how the ratings comparisons implied in FOM-statistic properly credit and penalize the observer for correct and incorrect decisions, respectively. The probabilistic meanings of the AFROC and wAFROC AUCs are given.
\item
  Detailed derivations of FOM-statistics, applicable to the areas under the empirical FROC plot, the AFROC1 and wAFROC1 plots are not given. Instead, the results for all plots are summarized in {[}TBA Online Appendix 14.C{]}, which shows that the definitions ``work'', i.e., the FOM-statistics yield the correct areas as determined by numerical integration of the relevant curves.
\end{itemize}

\hypertarget{froc-meanings-afroc}{%
\section{Empirical AFROC FOM-statistic}\label{froc-meanings-afroc}}

\(\text{A}_{wAFROC}\) was defined in TBA \texttt{\textbackslash{}@ref(froc-empirical-wAFROC)} as the area under the empirical AFROC. The corresponding FOM-statistic \(\theta_{wAFROC}\) is defined as follows: one calculates the rating of the highest rated NL mark \(\text{FP}_{k_1 1}\) on each non-diseased case \(k_1 1\) (or \(-\infty\) if the case has no NL marks) and compares it to each LL rating using the kernel function \(\psi(x,y)\) defined in Eqn. TBA (eq:empirical-auc-PsiFunction) \footnote{The kernel function comparison yields 1 if the LL rating is higher, 0.5 if the ratings are identical and zero otherwise.}. A summation is performed over all cases and all lesions.

The highest rating \(\text{FP}_{k_1 1}\) on non-diseased case \(k_1 1\) is defined as:

\begin{equation}
\left.
\begin{aligned}
\text{FP}_{k_1 1}  =&  \max_{l_1} \left ( z_{k_1 1 l_1 1} \mid  l_1 \neq \varnothing \right )\\
\text{FP}_{k_1 1}  =&  -\infty\mid l_1 = \varnothing
\end{aligned}
\right \}
\label{eq:froc-meanings-R-k1}
\end{equation}

If the case has at least one latent NL mark, then \(l_1 \neq \varnothing\), where \(\varnothing\) is the null set, and the first definition applies. If the case has no marks, then \(l_1 = \varnothing\), and the second definition applies.

The following equation sums over all cases and lesions:

\begin{equation}
\begin{aligned} 
\theta_{wAFROC} =& \frac{1}{K_1 L_T}\sum_{k_1=1}^{K_1}\sum_{k_2=1}^{K_2}\sum_{l_2=1}^{L_{k_2}}\psi\left ( \text{FP}_{k_1 1}, z_{k_2 2 l_2 2} \right )\\
\end {aligned}
\label{eq:froc-meanings-theta-afroc}
\end{equation}

Since every lesion is assigned a rating, albeit negative infinity for an unmarked lesion, the null set conditioning is not needed.

\hypertarget{upper-limit-for-afroc-fom-statistic}{%
\subsection{Upper limit for AFROC FOM-statistic}\label{upper-limit-for-afroc-fom-statistic}}

The FOM-statistic \(\theta_{wAFROC}\) achieves its highest value, unity, if and only if every lesion is rated higher than any mark on non-diseased cases, for then the \(\psi\) function always yields unity, and the summations yield :

\begin{equation}
\left. 
\begin{aligned}
\theta_{wAFROC}=& \frac{1}{K_1 \sum_{k_2=1}^{K_2}L_{k_2}}\sum_{k_1=1}^{K_1}\sum_{k_2=1}^{K_2}\sum_{l_2=1}^{L_{k_2}}  1 \\
= & \frac{1}{K_1 \sum_{k_2=1}^{K_2}L_{k_2}}\sum_{k_1=1}^{K_1}\sum_{k_2=1}^{K_2}L_{k_2} \\
= & \frac{1}{K_1}\sum_{k_1=1}^{K_1}1\\
= & 1
\end{aligned}
\right \}
\label{eq:froc-meanings-theta-afroc-unity}
\end{equation}

\hypertarget{range-of-afroc-fom-statistic}{%
\subsection{Range of AFROC FOM-statistic}\label{range-of-afroc-fom-statistic}}

If, on the other hand, every lesion is rated lower than every mark on every non-diseased case, the \(\psi\) function always yields zero, and the FOM-statistic is zero. Therefore,

\begin{equation}
0 \leq \theta_{wAFROC} \leq 1
\label{eq:froc-meanings-theta-afroc-limits}
\end{equation}

Eqn. \eqref{eq:froc-meanings-theta-afroc-limits} shows that \(\theta_{wAFROC}\) behaves like a probability but its range is \emph{twice} that of \(\theta_{ROC}\); recall that \(0.5 \leq \theta_{ROC} \leq 1\) (assuming the observer has equal or better than random performance and the observer does not have the direction of the rating scale accidentally reversed). This has the consequence that treatment related differences between \(\theta_{wAFROC}\) (i.e., effect sizes) are larger relative to the corresponding ROC effect sizes (just as temperature differences in the Fahrenheit scale are larger than the same differences expressed in the Celsius scale). This has important implications for FROC sample size estimation, Chapter TBA.

Eqn. \eqref{eq:froc-meanings-theta-afroc-limits} is one reason why the ``chance diagonal'' of the AFROC, corresponding to AUC = 0.5, does not, in fact, reflect chance-level performance. An area under the AFROC equal to 0.5 is actually reasonable performance, being smack in the middle of the allowed range. An example of this was given in TBA §13.4.2.2 for the case of an expert radiologist who does not mark any cases.

\hypertarget{froc-meanings-wafroc}{%
\section{Empirical weighted-AFROC FOM-statistic}\label{froc-meanings-wafroc}}

The empirical weighted-AFROC plot and lesion weights were defined in SectionTBA \texttt{\textbackslash{}@ref(froc-empirical-wAFROC)}. The empirical weighted-AFROC FOM-statistic \citep{RN1385} is defined by including the lesion weights \(W_{k_2 l_2}\) inside the summations (but outside the kernel function):

\begin{equation}
\begin{aligned} 
\theta_{\text{wAFROC}} =& \frac{1}{K_1 K_2}\sum_{k_1=1}^{K_1}\sum_{k_2=1}^{K_2}\sum_{l_2=1}^{L_{k_2}}W_{k_2 l_2}\psi\left ( \text{FP}_{k_1 1}, z_{k_2 2 l_2 2} \right )\\
\end {aligned}
\label{eq:froc-meanings-theta-wafroc}
\end{equation}

The weights obey the constraint:

\begin{equation} 
\sum_{l_2=1}^{L_{k_2}}W_{k_2 l_2} = 1
\label{eq:froc-meanings-theta-constraint-weights}
\end{equation}

This ensures, as will be shown shortly, that each diseased case contributes equally to the FOM, regardless of how many lesions are in it. In the special case of one lesion per diseased case, \(\theta_{wAFROC}\) and \(\theta_{\text{wAFROC}}\) are identical. For equally weighted lesions,

\begin{equation} 
W_{k_2 l_2} = \frac{1}{L_{k_2}}
\label{eq:froc-meanings-theta-equal-weights}
\end{equation}

For example, for equally weighted lesions and a case with three lesions, each weight equals one-third (1/3) \footnote{The \texttt{RJafroc} function \texttt{DfReadDataFile()} checks that the weights sum to unity to a precision of about 5 decimal places. The easy way to assign equal weights to all lesions on a diseased case is to set the corresponding \texttt{lesionWeights} field in the Excel file \texttt{Truth} worksheet to zeroes.}.

\hypertarget{froc-meanings-two-theorems}{%
\section{Two Theorems}\label{froc-meanings-two-theorems}}

The area \(A_{\text{wAFROC}}\) under the wAFROC plot is obtained by summing the areas of individual trapezoids defined by drawing vertical lines from each pair of adjacent operating points to the x-axis. A sample plot is shown Fig. \ref{fig:froc-meanings-theorems}.

\begin{figure}
\centering
\includegraphics{14-meanings-foms_files/figure-latex/froc-meanings-theorems-1.pdf}
\caption{\label{fig:froc-meanings-theorems}An example wAFROC plot; from left to right, the two shaded areas correspond to \(A_i\) and \(A_0\), respectively, defined below.}
\end{figure}

The operating point labeled \(i\) has coordinates \(\left ( \text{FPF}_i, \text{wLLF}_i \right )\) given by Eqn. TBA \texttt{\textbackslash{}@ref(eq:froc-empirical-FPF)} and Eqn. TBA \texttt{\textbackslash{}@ref(eq:froc-empirical-wLLFr)}, respectively, reproduced here for convenience:

\begin{equation}
FPF_i \equiv FPF \left ( \zeta_i \right ) = \frac{1}{K_1} \sum_{k_1=1}^{K_1} \mathbb{I} \left ( FP_{k_1 1} \geq \zeta_i\right )
\label{eq:froc-meanings-FPF}
\end{equation}

\begin{equation}
\text{wLLF}_i \equiv \text{wLLF}_{\zeta_i} = \frac{1}{K_2}\sum_{k_2=1}^{K_2}\sum_{l_2=1}^{L_{k_2}}W_{k_2 l_2} \mathbb{I}\left ( z_{k_2 l_2 2} \geq \zeta_i \right )
\label{eq:froc-meanings-wLLFi}
\end{equation}

TBA Online Appendix 14.A proves the following theorems:

\hypertarget{froc-meanings-two-theorems-1}{%
\subsection{Theorem 1}\label{froc-meanings-two-theorems-1}}

The area \(A_{\text{wAFROC}}\) under the empirical wAFROC plot equals the weighted-AFROC FOM-statistic \(\theta_{\text{wAFROC}}\) defined by Eqn. \eqref{eq:froc-meanings-theta-wafroc}:

\begin{equation}
\theta_{\text{wAFROC}} = A_{\text{wAFROC}}
\label{eq:froc-meanings-theorem1}
\end{equation}

This is the FROC counterpart of Bamber's Wilcoxon vs.~empirical ROC area equivalence theorem \citep{RN2174}, derived in Section TBA (empirical-auc-wilcoxon-bamber-theorem).

\hypertarget{froc-meanings-two-theorems-2}{%
\subsection{Theorem 2}\label{froc-meanings-two-theorems-2}}

The area \(A_0\) under the straight-line extension of the wAFROC from the observed end-point \(\left ( \text{FPF}_1, \text{wLLF}_1 \right )\) to (1,1) is given by:

\begin{equation}
A_0 = \frac{\left ( 1 - \text{FPF}_1 \right )\left ( 1 + \text{wLLF}_1 \right )}{2}
\label{eq:froc-meanings-A0}
\end{equation}

According to Eqn. \eqref{eq:froc-meanings-A0}, \(A_0\) increases as \(\text{FPF}_1\) decreases, i.e., as more non-diseased cases are \emph{not marked} and as \(\text{wLLF}_1\) increases, i.e., as more lesions, especially those with greater weights, \emph{are marked}. Both observations are in keeping with the behavior of a valid FOM.

\begin{itemize}
\tightlist
\item
  Failure to include the area under the straight-line extension results in not counting the full positive contribution to the FOM of unmarked non-diseased cases and marked lesions.
\item
  Each unmarked non-diseased case represents a perfect decision.
\item
  For a perfect observer whose operating characteristic is the vertical line from (0,0) to (0,1) followed by the horizontal line from (0,1) to (1,1), \emph{the area under the straight-line extension comprises the entire AUC}. Excluding it would yield zero AUC for a perfect observer, which is obviously incorrect.
\item
  Stated equivalently, for the perfect observer \(\text{FPF}_1 = 0\) and \(\text{wLLF}_1 = 1\) and then, according to Eqn. \eqref{eq:froc-meanings-A0}, the area under the straight line extension is \(A_0 = 1\).
\end{itemize}

\hypertarget{froc-meanings-physical-interpretions}{%
\section{Physical interpretations}\label{froc-meanings-physical-interpretions}}

From the preceding sections, it is seen that the AFROC-based trapezoidal plots consist of upward and rightward jumps, starting from the origin (0,0) and ending at (1,1). This is true regardless of whether the z-samples are binned or not: i.e., at the ``microscopic'' level the jumps always exist. Each upward jump is associated with a LL rating exceeding a virtual threshold. Each rightward jump is associated with a FP rating exceeding the threshold. Upward jumps tend to increase the area under the AFROC-based plots and rightward jumps tend to decrease it. This makes physical sense in terms of correct decisions being rewarded and incorrect ones being penalized, and can be seen from two extreme-case examples. If there are only upward jumps, then the trapezoidal plot rises from the origin to (0,1), where all lesions are correctly localized without any generating FPs and performance is perfect -- the straight-line extension to (1,1) ensures that the net area is unity. If there are only horizontal jumps, that takes the operating point from the origin to (1,0), where none of the lesions are localized and every non-diseased image has at least one NL mark, representing worst possible performance. Here, despite the straight line extension to (1,1), the net area is zero.

\hypertarget{physical-interpretation-of-area-under-afroc}{%
\subsection{Physical interpretation of area under AFROC}\label{physical-interpretation-of-area-under-afroc}}

The area under the AFROC has the following physical interpretation: it is the fraction of LL vs.~FP z-sample comparisons where the LL sample is equal (counting as half a comparison) or greater (counting as a full comparison) than the FP z-sample. From Tables 1 and 2, there are four FPs and six LLs for 24 possible comparisons. Inspection of the tables reveals that there are 4 x 4 = 16 comparisons contributing ones, two comparisons (from the 2nd diseased case) contributing ones, and one comparison (from the 2nd lesion on the 3rd diseased case) contributing 0.5, which sum to 18.5. Dividing by 24 yields 18.5/24 = 0.7708, the empirical TBA AFROC-AUC, §14.5.1. In probabilistic terms:

\emph{The area under the AFROC is the probability that a lesion is rated higher than any mark on a non-diseased case.}

\hypertarget{physical-interpretation-of-area-under-wafroc}{%
\subsection{Physical interpretation of area under wAFROC}\label{physical-interpretation-of-area-under-wafroc}}

The area under the wAFROC has the following physical interpretation: it is the lesion-weight adjusted fraction of diseased cases vs.~non-diseased case comparisons where LL z-samples are equal (counting as half a comparison times the weight of the lesion in question) or greater (counting as a full comparison times the weight of the lesion) than FP z-samples. Note that there are still 24 LL vs.~FP comparisons but the counting proceeds differently. The fourth diseased case contributes 0.9 x 4 + 0.1 x 4, i.e., 4 (compared to 8 in the preceding example). The third diseased case contributes 0.1 x 4 + 0.9 x 0.5, i.e., 2.6 (compared to 4.5 in the preceding example). The second diseased case contributes 1 x 2 = 2 (compared to 2 in the preceding example), and the first diseased case contributes 1 x 4 = 4 (compared to 4 in the preceding example). Summing these values and dividing by 16 (the total number of diseased cases vs.~non-diseased cases comparisons) one gets 12.6/16 = 0.7875, which is the area under the wAFROC, §14.5.1. In probabilistic terms:

\emph{The area under the weighted-AFROC is the lesion-weight adjusted probability that a lesion is rated higher than any mark on a non-diseased case.}

\hypertarget{froc-meanings-Discussion}{%
\section{Discussion}\label{froc-meanings-Discussion}}

TBA
TODOLAST

The primary aim of this chapter was to develop expressions for FOMs (i.e., functions of ratings) and show their equivalences to the empirical AUCs under corresponding operating characteristics. Unlike the ROC, the AFROC and wAFROC figures of merit are represented by quasi-Wilcoxon like constructs, not the well-known Wilcoxon statistic5.

I am aware from users of my software that their manuscript submissions have sometimes been held up with the critique that the meaning of the AFROC FOM-statistic is ``not intuitively clear''6 TBA. Any critique based on intuitive clarity or lack thereof suffers from a fundamental flaw: it is un-falsifiable. What is ``intuitively not clear'' to one could be ``intuitively very clear'' to another, and there is no way of testing either viewpoint. Un-falsifiable claims have no place in science.

An example was given in a previous chapter. This is one reason I have tried to make the meaning clear, perhaps at the risk of making it painfully clear. Clinical interpretations do not always fit into convenient easy to analyze paradigms. Not understanding something is not a reason for preferring a simpler method. Use of the simpler ROC paradigm to analyze location specific tasks results in loss of statistical power and sacrifices better understanding of what is limiting performance. It is unethical to analyze a study with a method with lower statistical power when one with greater power is available7-9. The title of the paper by Halpern et al is ``The continuing unethical conduct of under-powered clinical trials''. The AFROC FOM-statistic was proposed in 1989 and it has been used, at the time of writing, in over 107 publications .

The subject material of this chapter is not that difficult. However, it does require the researcher to be receptive an unbiased. Dirac addressed an analogous then-existing concern about quantum mechanics, namely it did not provide a satisfying ``picture'' of what is going on, as did classical mechanics . To paraphrase him, the purpose of science (quantum physics in his case) is not to provide satisfying pictures but to explain data. FROC data is inherently more complex than the ROC paradigm and one should not expect a simple FOM-statistic. The detailed explanations given in this chapter should allow one to understand the wAFROC and AFROC FOMs.

A misconception regarding the wAFROC FOM-statistic is that the weighting may sacrifice statistical power and render the method equivalent to ROC analysis in terms of statistical power. Analysis of clinical datasets and simulation studies suggests that this is not the case; loss of power is minimal. As noted earlier, the highest rating carries more information than a randomly selected rating.

Bamber's equivalence theorem led to much progress in non-parametric analysis of ROC data. The proofs of the equivalences between the areas under the AFROC and wAFROC and the corresponding quasi-Wilcoxon statistics provide a starting point. To realize the full potential of these proofs, similar work like that conducted by DeLong et al10 is needed for the FROC paradigm. This work is not going to be easy; one reason being the relative dearth of researchers working in this area, but it is possible. Indeed work has been published by Popescu11 on non-parametric analysis of the exponentially transformed FROC (EFROC) plot which, like the AFROC and wAFROC, is completely contained within the unit square. This work should be extended to the wAFROC. For reasons stated in Chapter 13, non-parametric analysis of FROC curves12-14 is not expected to be fruitful.

Current terminology prefixes each of the AFROC-based FOMs with the letter ``J'' for Jackknife. The author recommends dropping this prefix, which has to do with significance testing procedure rather than the actual definition of the FOM-statistic. For example, the correct way is to refer to the AFROC figure of merit, not the JAFROC figure of merit. For continuity, the software packages implementing the methods are still referred to as JAFROC (Windows) or RJAfroc (cross-platform, open-source).

To gain deeper insight into the FROC paradigm, it is necessary to look at methods used to measure visual search, the subject of the next chapter.

\hypertarget{froc-meanings-references}{%
\section{References}\label{froc-meanings-references}}

  \bibliography{packages.bib,myRefs.bib}

\end{document}
