<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 ROC predictions of the RSM | The RJafroc Froc Book</title>
  <meta name="description" content="Artificial intelligence and observer performance book based on RJafroc." />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 ROC predictions of the RSM | The RJafroc Froc Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Artificial intelligence and observer performance book based on RJafroc." />
  <meta name="github-repo" content="dpc10ster/RJafrocFrocBook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 ROC predictions of the RSM | The RJafroc Froc Book" />
  
  <meta name="twitter:description" content="Artificial intelligence and observer performance book based on RJafroc." />
  

<meta name="author" content="Dev P. Chakraborty, PhD" />


<meta name="date" content="2022-10-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="rsm.html"/>
<link rel="next" href="rsm-pred2.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">RJafroc documentation</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="preface.html"><a href="preface.html#rationale-and-organization"><i class="fa fa-check"></i><b>0.1</b> Rationale and Organization</a></li>
<li class="chapter" data-level="0.2" data-path="preface.html"><a href="preface.html#tba-acknowledgements"><i class="fa fa-check"></i><b>0.2</b> TBA Acknowledgements</a></li>
</ul></li>
<li class="part"><span><b>FROC paradigm</b></span></li>
<li class="chapter" data-level="1" data-path="froc-paradigm.html"><a href="froc-paradigm.html"><i class="fa fa-check"></i><b>1</b> The FROC paradigm and search</a><ul>
<li class="chapter" data-level="1.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-how-much-finished"><i class="fa fa-check"></i><b>1.1</b> How much finished</a></li>
<li class="chapter" data-level="1.2" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-intro"><i class="fa fa-check"></i><b>1.2</b> Introduction</a><ul>
<li class="chapter" data-level="1.2.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-outline"><i class="fa fa-check"></i><b>1.2.1</b> Chapter outline</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-location-specific-paradigms"><i class="fa fa-check"></i><b>1.3</b> Location specific paradigms</a></li>
<li class="chapter" data-level="1.4" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-vis-search"><i class="fa fa-check"></i><b>1.4</b> Visual search</a><ul>
<li class="chapter" data-level="1.4.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-scoring-the-data"><i class="fa fa-check"></i><b>1.4.1</b> Proximity criterion and scoring the data</a></li>
<li class="chapter" data-level="1.4.2" data-path="froc-paradigm.html"><a href="froc-paradigm.html#multiple-marks-in-the-same-vicinity"><i class="fa fa-check"></i><b>1.4.2</b> Multiple marks in the same vicinity</a></li>
<li class="chapter" data-level="1.4.3" data-path="froc-paradigm.html"><a href="froc-paradigm.html#historical-context"><i class="fa fa-check"></i><b>1.4.3</b> Historical context</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-froc-plot"><i class="fa fa-check"></i><b>1.5</b> The FROC plot</a><ul>
<li class="chapter" data-level="1.5.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-plot-illustration"><i class="fa fa-check"></i><b>1.5.1</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-solar-analogy"><i class="fa fa-check"></i><b>1.6</b> The “solar” analogy</a></li>
<li class="chapter" data-level="1.7" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-discussion"><i class="fa fa-check"></i><b>1.7</b> Discussion</a></li>
<li class="chapter" data-level="1.8" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-references"><i class="fa fa-check"></i><b>1.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="empirical.html"><a href="empirical.html"><i class="fa fa-check"></i><b>2</b> Empirical plots from FROC data</a><ul>
<li class="chapter" data-level="2.1" data-path="empirical.html"><a href="empirical.html#empirical-how-much-finished"><i class="fa fa-check"></i><b>2.1</b> How much finished</a></li>
<li class="chapter" data-level="2.2" data-path="empirical.html"><a href="empirical.html#empirical-intro"><i class="fa fa-check"></i><b>2.2</b> Introduction</a></li>
<li class="chapter" data-level="2.3" data-path="empirical.html"><a href="empirical.html#empirical-mark-rating-pairs"><i class="fa fa-check"></i><b>2.3</b> FROC data and notation</a><ul>
<li class="chapter" data-level="2.3.1" data-path="empirical.html"><a href="empirical.html#lls-vs.-nls"><i class="fa fa-check"></i><b>2.3.1</b> LLs vs. NLs</a></li>
<li class="chapter" data-level="2.3.2" data-path="empirical.html"><a href="empirical.html#latent-vs.-actual-marks"><i class="fa fa-check"></i><b>2.3.2</b> Latent vs. actual marks</a></li>
<li class="chapter" data-level="2.3.3" data-path="empirical.html"><a href="empirical.html#z-samples-vs.-ratings"><i class="fa fa-check"></i><b>2.3.3</b> z-samples vs. ratings</a></li>
<li class="chapter" data-level="2.3.4" data-path="empirical.html"><a href="empirical.html#binning-rule"><i class="fa fa-check"></i><b>2.3.4</b> Binning rule</a></li>
<li class="chapter" data-level="2.3.5" data-path="empirical.html"><a href="empirical.html#empirical-notation"><i class="fa fa-check"></i><b>2.3.5</b> Notation</a></li>
<li class="chapter" data-level="2.3.6" data-path="empirical.html"><a href="empirical.html#comments"><i class="fa fa-check"></i><b>2.3.6</b> Comments</a></li>
<li class="chapter" data-level="2.3.7" data-path="empirical.html"><a href="empirical.html#empirical-indexing-marks"><i class="fa fa-check"></i><b>2.3.7</b> A conceptual and notatonal issue</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="empirical.html"><a href="empirical.html#empirical-froc-plot-1"><i class="fa fa-check"></i><b>2.4</b> The FROC plot</a><ul>
<li class="chapter" data-level="2.4.1" data-path="empirical.html"><a href="empirical.html#empirical-end-point"><i class="fa fa-check"></i><b>2.4.1</b> The observed FROC end-point and its semi-constrained property</a></li>
<li class="chapter" data-level="2.4.2" data-path="empirical.html"><a href="empirical.html#empirical-froc-plot-futility-extrapolation"><i class="fa fa-check"></i><b>2.4.2</b> Futility of extrapolation outside the observed end-point</a></li>
<li class="chapter" data-level="2.4.3" data-path="empirical.html"><a href="empirical.html#empirical-froc-plot-illustration"><i class="fa fa-check"></i><b>2.4.3</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="empirical.html"><a href="empirical.html#empirical-ROC"><i class="fa fa-check"></i><b>2.5</b> The inferred-ROC plot</a><ul>
<li class="chapter" data-level="2.5.1" data-path="empirical.html"><a href="empirical.html#empirical-ROC-fpf"><i class="fa fa-check"></i><b>2.5.1</b> The inferred-ROC z-sample</a></li>
<li class="chapter" data-level="2.5.2" data-path="empirical.html"><a href="empirical.html#empirical-ROC-tpf"><i class="fa fa-check"></i><b>2.5.2</b> Inferred TPF</a></li>
<li class="chapter" data-level="2.5.3" data-path="empirical.html"><a href="empirical.html#empirical-definition-empirical-auc-roc"><i class="fa fa-check"></i><b>2.5.3</b> The empirical ROC plot and AUC</a></li>
<li class="chapter" data-level="2.5.4" data-path="empirical.html"><a href="empirical.html#empirical-ROC-constrained"><i class="fa fa-check"></i><b>2.5.4</b> The observed end-point of the ROC and its constrained property</a></li>
<li class="chapter" data-level="2.5.5" data-path="empirical.html"><a href="empirical.html#empirical-roc-plot-illustration"><i class="fa fa-check"></i><b>2.5.5</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="empirical.html"><a href="empirical.html#empirical-AFROC"><i class="fa fa-check"></i><b>2.6</b> The alternative FROC (AFROC) plot</a><ul>
<li class="chapter" data-level="2.6.1" data-path="empirical.html"><a href="empirical.html#empirical-definition-empirical-auc-afroc"><i class="fa fa-check"></i><b>2.6.1</b> Definition: empirical AFROC plot and AUC</a></li>
<li class="chapter" data-level="2.6.2" data-path="empirical.html"><a href="empirical.html#empirical-AFROC-constrained"><i class="fa fa-check"></i><b>2.6.2</b> The observed end-point of the AFROC and its constrained property</a></li>
<li class="chapter" data-level="2.6.3" data-path="empirical.html"><a href="empirical.html#empirical-afroc-plot-illustration"><i class="fa fa-check"></i><b>2.6.3</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="empirical.html"><a href="empirical.html#empirical-wAFROC"><i class="fa fa-check"></i><b>2.7</b> The weighted-AFROC plot (wAFROC) plot</a><ul>
<li class="chapter" data-level="2.7.1" data-path="empirical.html"><a href="empirical.html#empirical-definition-empirical-auc-wafroc"><i class="fa fa-check"></i><b>2.7.1</b> The empirical wAFROC plot and AUC</a></li>
<li class="chapter" data-level="2.7.2" data-path="empirical.html"><a href="empirical.html#empirical-wafroc-plot-illustration"><i class="fa fa-check"></i><b>2.7.2</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="empirical.html"><a href="empirical.html#empirical-numerical-understanding"><i class="fa fa-check"></i><b>2.8</b> AFROC vs. wAFROC</a><ul>
<li class="chapter" data-level="2.8.1" data-path="empirical.html"><a href="empirical.html#nl-and-ll-z-samples"><i class="fa fa-check"></i><b>2.8.1</b> NL and LL z-samples</a></li>
<li class="chapter" data-level="2.8.2" data-path="empirical.html"><a href="empirical.html#lesion-weights"><i class="fa fa-check"></i><b>2.8.2</b> Lesion weights</a></li>
<li class="chapter" data-level="2.8.3" data-path="empirical.html"><a href="empirical.html#fpf"><i class="fa fa-check"></i><b>2.8.3</b> FPF</a></li>
<li class="chapter" data-level="2.8.4" data-path="empirical.html"><a href="empirical.html#llf"><i class="fa fa-check"></i><b>2.8.4</b> LLF</a></li>
<li class="chapter" data-level="2.8.5" data-path="empirical.html"><a href="empirical.html#wllf"><i class="fa fa-check"></i><b>2.8.5</b> wLLF</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="empirical.html"><a href="empirical.html#empirical-meanings"><i class="fa fa-check"></i><b>2.9</b> Interpretation of AUCs</a></li>
<li class="chapter" data-level="2.10" data-path="empirical.html"><a href="empirical.html#empirical-instructive-cases"><i class="fa fa-check"></i><b>2.10</b> Instructive examples</a><ul>
<li class="chapter" data-level="2.10.1" data-path="empirical.html"><a href="empirical.html#empirical-instructive-cases-FROC"><i class="fa fa-check"></i><b>2.10.1</b> The FROC</a></li>
<li class="chapter" data-level="2.10.2" data-path="empirical.html"><a href="empirical.html#empirical-instructive-cases-ROC"><i class="fa fa-check"></i><b>2.10.2</b> The ROC</a></li>
<li class="chapter" data-level="2.10.3" data-path="empirical.html"><a href="empirical.html#empirical-instructive-cases-AFROC"><i class="fa fa-check"></i><b>2.10.3</b> The AFROC</a></li>
<li class="chapter" data-level="2.10.4" data-path="empirical.html"><a href="empirical.html#empirical-instructive-cases-wAFROC"><i class="fa fa-check"></i><b>2.10.4</b> The wAFROC</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="empirical.html"><a href="empirical.html#empirical-froc-auc-poor"><i class="fa fa-check"></i><b>2.11</b> FROC-AUC is a poor measure</a><ul>
<li class="chapter" data-level="2.11.1" data-path="empirical.html"><a href="empirical.html#plot-of-froc-auc-vs.-roc-auc"><i class="fa fa-check"></i><b>2.11.1</b> Plot of FROC AUC vs. ROC AUC</a></li>
<li class="chapter" data-level="2.11.2" data-path="empirical.html"><a href="empirical.html#plot-of-afroc-auc-vs.-roc-auc"><i class="fa fa-check"></i><b>2.11.2</b> Plot of AFROC AUC vs. ROC AUC</a></li>
<li class="chapter" data-level="2.11.3" data-path="empirical.html"><a href="empirical.html#plot-of-wafroc-auc-vs.-roc-auc"><i class="fa fa-check"></i><b>2.11.3</b> Plot of wAFROC AUC vs. ROC AUC</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="empirical.html"><a href="empirical.html#empirical-AFROC1"><i class="fa fa-check"></i><b>2.12</b> The AFROC1 plot</a><ul>
<li class="chapter" data-level="2.12.1" data-path="empirical.html"><a href="empirical.html#empirical-definition-empirical-auc-afroc1"><i class="fa fa-check"></i><b>2.12.1</b> Empirical AFROC1 plot and AUC</a></li>
<li class="chapter" data-level="2.12.2" data-path="empirical.html"><a href="empirical.html#empirical-afroc1-plot-illustration"><i class="fa fa-check"></i><b>2.12.2</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="empirical.html"><a href="empirical.html#empirical-wAFROC1"><i class="fa fa-check"></i><b>2.13</b> The weighted-AFROC1 (wAFROC1) plot</a><ul>
<li class="chapter" data-level="2.13.1" data-path="empirical.html"><a href="empirical.html#empirical-definition-empirical-auc-wafroc1"><i class="fa fa-check"></i><b>2.13.1</b> Empirical wAFROC1 plot and AUC</a></li>
<li class="chapter" data-level="2.13.2" data-path="empirical.html"><a href="empirical.html#empirical-wafroc1-plot-illustration"><i class="fa fa-check"></i><b>2.13.2</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="2.14" data-path="empirical.html"><a href="empirical.html#empirical-summary"><i class="fa fa-check"></i><b>2.14</b> Summary</a></li>
<li class="chapter" data-level="2.15" data-path="empirical.html"><a href="empirical.html#empirical-theorem-1"><i class="fa fa-check"></i><b>2.15</b> Appendix 1: Proof of formula for wAFROC-AUC</a></li>
<li class="chapter" data-level="2.16" data-path="empirical.html"><a href="empirical.html#empirical-theorem-2"><i class="fa fa-check"></i><b>2.16</b> Appendix 2: Interpretation of area under straight line extension of wAFROC</a></li>
<li class="chapter" data-level="2.17" data-path="empirical.html"><a href="empirical.html#empirical-summary-computational-formulae"><i class="fa fa-check"></i><b>2.17</b> Appendix 3: Summary of computational formulae</a><ul>
<li class="chapter" data-level="2.17.1" data-path="empirical.html"><a href="empirical.html#froc"><i class="fa fa-check"></i><b>2.17.1</b> FROC</a></li>
<li class="chapter" data-level="2.17.2" data-path="empirical.html"><a href="empirical.html#roc"><i class="fa fa-check"></i><b>2.17.2</b> ROC</a></li>
<li class="chapter" data-level="2.17.3" data-path="empirical.html"><a href="empirical.html#afroc"><i class="fa fa-check"></i><b>2.17.3</b> AFROC</a></li>
<li class="chapter" data-level="2.17.4" data-path="empirical.html"><a href="empirical.html#wafroc"><i class="fa fa-check"></i><b>2.17.4</b> wAFROC</a></li>
<li class="chapter" data-level="2.17.5" data-path="empirical.html"><a href="empirical.html#afroc1"><i class="fa fa-check"></i><b>2.17.5</b> AFROC1</a></li>
<li class="chapter" data-level="2.17.6" data-path="empirical.html"><a href="empirical.html#wafroc1"><i class="fa fa-check"></i><b>2.17.6</b> wAFROC1</a></li>
</ul></li>
<li class="chapter" data-level="2.18" data-path="empirical.html"><a href="empirical.html#empirical-references"><i class="fa fa-check"></i><b>2.18</b> References</a></li>
</ul></li>
<li class="part"><span><b>The radiological search model (RSM)</b></span></li>
<li class="chapter" data-level="3" data-path="visual-search.html"><a href="visual-search.html"><i class="fa fa-check"></i><b>3</b> Visual Search</a><ul>
<li class="chapter" data-level="3.1" data-path="visual-search.html"><a href="visual-search.html#visual-search-how-much-finished"><i class="fa fa-check"></i><b>3.1</b> How much finished</a></li>
<li class="chapter" data-level="3.2" data-path="visual-search.html"><a href="visual-search.html#visual-search-intro"><i class="fa fa-check"></i><b>3.2</b> Introduction</a></li>
<li class="chapter" data-level="3.3" data-path="visual-search.html"><a href="visual-search.html#visual-search-grouping-labeling-rois"><i class="fa fa-check"></i><b>3.3</b> Grouping and labeling ROIs</a></li>
<li class="chapter" data-level="3.4" data-path="visual-search.html"><a href="visual-search.html#visual-search-recognition-detection"><i class="fa fa-check"></i><b>3.4</b> Search vs. detection</a></li>
<li class="chapter" data-level="3.5" data-path="visual-search.html"><a href="visual-search.html#visual-search-search-classification"><i class="fa fa-check"></i><b>3.5</b> Search vs. classification</a></li>
<li class="chapter" data-level="3.6" data-path="visual-search.html"><a href="visual-search.html#visual-search-kundel-nodine-model"><i class="fa fa-check"></i><b>3.6</b> The Kundel - Nodine search model</a><ul>
<li class="chapter" data-level="3.6.1" data-path="visual-search.html"><a href="visual-search.html#visual-search-glancing-global-impression"><i class="fa fa-check"></i><b>3.6.1</b> Stage 1: Search</a></li>
<li class="chapter" data-level="3.6.2" data-path="visual-search.html"><a href="visual-search.html#visual-search-scanning-local-feature-analysis"><i class="fa fa-check"></i><b>3.6.2</b> Stage 2: Feature analysis</a></li>
<li class="chapter" data-level="3.6.3" data-path="visual-search.html"><a href="visual-search.html#visual-search-example"><i class="fa fa-check"></i><b>3.6.3</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="visual-search.html"><a href="visual-search.html#visual-search-references"><i class="fa fa-check"></i><b>3.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rsm.html"><a href="rsm.html"><i class="fa fa-check"></i><b>4</b> The radiological search model (RSM)</a><ul>
<li class="chapter" data-level="4.1" data-path="rsm.html"><a href="rsm.html#rsm-how-much-finished"><i class="fa fa-check"></i><b>4.1</b> How much finished</a></li>
<li class="chapter" data-level="4.2" data-path="rsm.html"><a href="rsm.html#rsm-intro"><i class="fa fa-check"></i><b>4.2</b> Introduction</a></li>
<li class="chapter" data-level="4.3" data-path="rsm.html"><a href="rsm.html#rsm-details"><i class="fa fa-check"></i><b>4.3</b> The radiological search model</a></li>
<li class="chapter" data-level="4.4" data-path="rsm.html"><a href="rsm.html#rsm-assumptions"><i class="fa fa-check"></i><b>4.4</b> RSM assumptions</a></li>
<li class="chapter" data-level="4.5" data-path="rsm.html"><a href="rsm.html#rsm-parameter-physical-meanings"><i class="fa fa-check"></i><b>4.5</b> Physical meanings of the RSM parameters</a><ul>
<li class="chapter" data-level="4.5.1" data-path="rsm.html"><a href="rsm.html#rsm-mu-parameter"><i class="fa fa-check"></i><b>4.5.1</b> The <span class="math inline">\(\mu\)</span> parameter</a></li>
<li class="chapter" data-level="4.5.2" data-path="rsm.html"><a href="rsm.html#rsm-summary-lambda-parameter"><i class="fa fa-check"></i><b>4.5.2</b> The <span class="math inline">\(\lambda\)</span> parameter</a></li>
<li class="chapter" data-level="4.5.3" data-path="rsm.html"><a href="rsm.html#rsm-summary-nu-parameter"><i class="fa fa-check"></i><b>4.5.3</b> The <span class="math inline">\(\nu\)</span> parameter</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="rsm.html"><a href="rsm.html#rsm-intrinsic-parameters"><i class="fa fa-check"></i><b>4.6</b> Intrinsic RSM parameters</a></li>
<li class="chapter" data-level="4.7" data-path="rsm.html"><a href="rsm.html#rsm-discussion-summary"><i class="fa fa-check"></i><b>4.7</b> Discussion / Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="rsm-pred.html"><a href="rsm-pred.html"><i class="fa fa-check"></i><b>5</b> ROC predictions of the RSM</a><ul>
<li class="chapter" data-level="5.1" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-how-much-finished"><i class="fa fa-check"></i><b>5.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="5.2" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-intro"><i class="fa fa-check"></i><b>5.2</b> TBA Introduction</a></li>
<li class="chapter" data-level="5.3" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-inferred-roc"><i class="fa fa-check"></i><b>5.3</b> Inferred ROC z-sample</a></li>
<li class="chapter" data-level="5.4" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-end-point"><i class="fa fa-check"></i><b>5.4</b> End-point of the ROC</a><ul>
<li class="chapter" data-level="5.4.1" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-constrained-end-point-abscissa"><i class="fa fa-check"></i><b>5.4.1</b> The abscissa of the ROC end-point</a></li>
<li class="chapter" data-level="5.4.2" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-constrained-end-point-ordinate"><i class="fa fa-check"></i><b>5.4.2</b> The ordinate of the ROC end-point</a></li>
<li class="chapter" data-level="5.4.3" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-end-point-variable-number-lesions"><i class="fa fa-check"></i><b>5.4.3</b> Variable number of lesions per case</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-roc-curve"><i class="fa fa-check"></i><b>5.5</b> ROC curve</a><ul>
<li class="chapter" data-level="5.5.1" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-roc-curve-fpf"><i class="fa fa-check"></i><b>5.5.1</b> Derivation of FPF</a></li>
<li class="chapter" data-level="5.5.2" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-roc-curve-tpf"><i class="fa fa-check"></i><b>5.5.2</b> Derivation of TPF</a></li>
<li class="chapter" data-level="5.5.3" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-tpf-varying-lesions"><i class="fa fa-check"></i><b>5.5.3</b> Variable number of lesions per case</a></li>
<li class="chapter" data-level="5.5.4" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-roc-curve-pdfs"><i class="fa fa-check"></i><b>5.5.4</b> ROC decision variable pdfs</a></li>
<li class="chapter" data-level="5.5.5" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-roc-curve-auc"><i class="fa fa-check"></i><b>5.5.5</b> ROC AUC</a></li>
<li class="chapter" data-level="5.5.6" data-path="rsm-pred.html"><a href="rsm-pred.html#comparing-tpf-formula-to-rjafroc-functions"><i class="fa fa-check"></i><b>5.5.6</b> Comparing TPF formula to <code>RJafroc</code> functions</a></li>
<li class="chapter" data-level="5.5.7" data-path="rsm-pred.html"><a href="rsm-pred.html#effect-on-operating-point-of-varying-rsm-parameters"><i class="fa fa-check"></i><b>5.5.7</b> Effect on operating point of varying RSM parameters</a></li>
<li class="chapter" data-level="5.5.8" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-roc-curves"><i class="fa fa-check"></i><b>5.5.8</b> Sample ROC curves</a></li>
<li class="chapter" data-level="5.5.9" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-pdf-curves"><i class="fa fa-check"></i><b>5.5.9</b> Sample RSM pdf curves</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-roc-curve-proper"><i class="fa fa-check"></i><b>5.6</b> Proper ROC curve</a></li>
<li class="chapter" data-level="5.7" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-roc-curve-aucs-zeta1"><i class="fa fa-check"></i><b>5.7</b> <span class="math inline">\(\zeta\)</span> dependence of ROC AUC</a></li>
<li class="chapter" data-level="5.8" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-discussion-summary"><i class="fa fa-check"></i><b>5.8</b> TBA Discussion / Summary</a></li>
<li class="chapter" data-level="5.9" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-appendix1"><i class="fa fa-check"></i><b>5.9</b> Appendix 1: Proof of continuity of slope at the end-point</a></li>
<li class="chapter" data-level="5.10" data-path="rsm-pred.html"><a href="rsm-pred.html#rsm-pred-appendix2"><i class="fa fa-check"></i><b>5.10</b> Appendix 2: Numerical illustration of continuity</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="rsm-pred2.html"><a href="rsm-pred2.html"><i class="fa fa-check"></i><b>6</b> RSM FROC/AFROC/wAFROC predictions</a><ul>
<li class="chapter" data-level="6.1" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-how-much-finished"><i class="fa fa-check"></i><b>6.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="6.2" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-intro"><i class="fa fa-check"></i><b>6.2</b> TBA Introduction</a></li>
<li class="chapter" data-level="6.3" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-froc-curve"><i class="fa fa-check"></i><b>6.3</b> RSM-predicted FROC curve</a><ul>
<li class="chapter" data-level="6.3.1" data-path="rsm-pred2.html"><a href="rsm-pred2.html#froc-plots-using-intrinsic-lambda_i-nu_i-parameters"><i class="fa fa-check"></i><b>6.3.1</b> FROC plots using intrinsic <span class="math inline">\(\lambda_i, \nu_i\)</span> parameters</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-froc-afroc-curve"><i class="fa fa-check"></i><b>6.4</b> RSM-predicted AFROC curve</a><ul>
<li class="chapter" data-level="6.4.1" data-path="rsm-pred2.html"><a href="rsm-pred2.html#afroc-plots-using-intrinsic-lambda_i-nu_i-parameters"><i class="fa fa-check"></i><b>6.4.1</b> AFROC plots using intrinsic <span class="math inline">\(\lambda_i, \nu_i\)</span> parameters</a></li>
<li class="chapter" data-level="6.4.2" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-no-marks"><i class="fa fa-check"></i><b>6.4.2</b> Case of the reader who does not make any marks</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-wafroc-curve"><i class="fa fa-check"></i><b>6.5</b> RSM-predicted wAFROC curve</a><ul>
<li class="chapter" data-level="6.5.1" data-path="rsm-pred2.html"><a href="rsm-pred2.html#wafroc-plots-intrinsic-lambda_i-nu_i-parameters"><i class="fa fa-check"></i><b>6.5.1</b> wAFROC plots intrinsic <span class="math inline">\(\lambda_i, \nu_i\)</span> parameters</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-discussion-summary"><i class="fa fa-check"></i><b>6.6</b> Discussion / Summary</a></li>
<li class="chapter" data-level="6.7" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-appendix"><i class="fa fa-check"></i><b>6.7</b> Appendix</a><ul>
<li class="chapter" data-level="6.7.1" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-froc-physical-parameters"><i class="fa fa-check"></i><b>6.7.1</b> Slope of the FROC curve</a></li>
<li class="chapter" data-level="6.7.2" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-afroc-physical-parameters"><i class="fa fa-check"></i><b>6.7.2</b> Slope of the AFROC curve</a></li>
<li class="chapter" data-level="6.7.3" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-wafroc-physical-parameters"><i class="fa fa-check"></i><b>6.7.3</b> wAFROC plots using physical <span class="math inline">\(\lambda, \nu\)</span> parameters</a></li>
<li class="chapter" data-level="6.7.4" data-path="rsm-pred2.html"><a href="rsm-pred2.html#rsm-pred2-wafroc-above-afroc"><i class="fa fa-check"></i><b>6.7.4</b> wAFROC curves are generally above the AFROC curves</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="rsm-sc.html"><a href="rsm-sc.html"><i class="fa fa-check"></i><b>7</b> Search and classification performances</a><ul>
<li class="chapter" data-level="7.1" data-path="rsm-sc.html"><a href="rsm-sc.html#rsm-sc-how-much-finished"><i class="fa fa-check"></i><b>7.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="7.2" data-path="rsm-sc.html"><a href="rsm-sc.html#rsm-sc-intro"><i class="fa fa-check"></i><b>7.2</b> TBA Introduction</a></li>
<li class="chapter" data-level="7.3" data-path="rsm-sc.html"><a href="rsm-sc.html#rsm-sc-end-point"><i class="fa fa-check"></i><b>7.3</b> Location of ROC end-point</a></li>
<li class="chapter" data-level="7.4" data-path="rsm-sc.html"><a href="rsm-sc.html#rsm-sc-quantifying"><i class="fa fa-check"></i><b>7.4</b> Quantifying search performance</a></li>
<li class="chapter" data-level="7.5" data-path="rsm-sc.html"><a href="rsm-sc.html#rsm-sc-performance"><i class="fa fa-check"></i><b>7.5</b> Quantifying lesion-classification performance</a></li>
<li class="chapter" data-level="7.6" data-path="rsm-sc.html"><a href="rsm-sc.html#rsm-sc-search-classification-2afc-lke"><i class="fa fa-check"></i><b>7.6</b> TBA Lesion-classification performance and the 2AFC LKE task</a></li>
<li class="chapter" data-level="7.7" data-path="rsm-sc.html"><a href="rsm-sc.html#rsm-sc-search-classification-significance"><i class="fa fa-check"></i><b>7.7</b> Significance</a></li>
<li class="chapter" data-level="7.8" data-path="rsm-sc.html"><a href="rsm-sc.html#rsm-sc-discussion-summary"><i class="fa fa-check"></i><b>7.8</b> Discussion / Summary</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="rsm-fitting.html"><a href="rsm-fitting.html"><i class="fa fa-check"></i><b>8</b> RSM fitting</a><ul>
<li class="chapter" data-level="8.1" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-how-much-finished"><i class="fa fa-check"></i><b>8.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="8.2" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-intro"><i class="fa fa-check"></i><b>8.2</b> TBA Introduction</a></li>
<li class="chapter" data-level="8.3" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-roc-likelihood"><i class="fa fa-check"></i><b>8.3</b> ROC Likelihood function</a></li>
<li class="chapter" data-level="8.4" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-fitrsmroc-implementation"><i class="fa fa-check"></i><b>8.4</b> <code>FitRsmROC</code> implementation</a></li>
<li class="chapter" data-level="8.5" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-fitrsmroc-usage-example"><i class="fa fa-check"></i><b>8.5</b> <code>FitRsmROC</code> usage example</a></li>
<li class="chapter" data-level="8.6" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-discussion-summary"><i class="fa fa-check"></i><b>8.6</b> TBA Discussion / Summary</a></li>
<li class="chapter" data-level="8.7" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-froc-likelihood"><i class="fa fa-check"></i><b>8.7</b> Appendix 1: FROC likelihood function</a><ul>
<li class="chapter" data-level="8.7.1" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-froc-nls"><i class="fa fa-check"></i><b>8.7.1</b> Contribution of NLs</a></li>
<li class="chapter" data-level="8.7.2" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-froc-lls"><i class="fa fa-check"></i><b>8.7.2</b> Contribution of LLs</a></li>
<li class="chapter" data-level="8.7.3" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-froc-degeneracy"><i class="fa fa-check"></i><b>8.7.3</b> Degeneracy problems</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-froc-idca"><i class="fa fa-check"></i><b>8.8</b> Appendix 2: IDCA Likelihood function</a></li>
<li class="chapter" data-level="8.9" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-references"><i class="fa fa-check"></i><b>8.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html"><i class="fa fa-check"></i><b>9</b> Three proper ROC fits</a><ul>
<li class="chapter" data-level="9.1" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-how-much-finished"><i class="fa fa-check"></i><b>9.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="9.2" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-intro"><i class="fa fa-check"></i><b>9.2</b> TBA Introduction</a></li>
<li class="chapter" data-level="9.3" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-applications"><i class="fa fa-check"></i><b>9.3</b> Application to two datasets</a></li>
<li class="chapter" data-level="9.4" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-composite-plots"><i class="fa fa-check"></i><b>9.4</b> Composite plots</a></li>
<li class="chapter" data-level="9.5" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-rsm-parameters"><i class="fa fa-check"></i><b>9.5</b> RSM parameters</a></li>
<li class="chapter" data-level="9.6" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-cbm-parameters"><i class="fa fa-check"></i><b>9.6</b> CBM parameters</a></li>
<li class="chapter" data-level="9.7" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-proproc-parameters"><i class="fa fa-check"></i><b>9.7</b> PROPROC parameters</a></li>
<li class="chapter" data-level="9.8" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-overview"><i class="fa fa-check"></i><b>9.8</b> Overview of findings</a><ul>
<li class="chapter" data-level="9.8.1" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-slopes"><i class="fa fa-check"></i><b>9.8.1</b> Slopes</a></li>
<li class="chapter" data-level="9.8.2" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-confidence-intervals"><i class="fa fa-check"></i><b>9.8.2</b> Confidence intervals</a></li>
<li class="chapter" data-level="9.8.3" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-slopes-confidence-intervals-summary"><i class="fa fa-check"></i><b>9.8.3</b> Summary of slopes and confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-discussion-summary"><i class="fa fa-check"></i><b>9.9</b> TBA Discussion / Summary</a></li>
<li class="chapter" data-level="9.10" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-appendices"><i class="fa fa-check"></i><b>9.10</b> Appendices</a><ul>
<li class="chapter" data-level="9.10.1" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-one-dataset-proproc"><i class="fa fa-check"></i><b>9.10.1</b> Location of PROPROC files</a></li>
<li class="chapter" data-level="9.10.2" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-pre-analyzed-results"><i class="fa fa-check"></i><b>9.10.2</b> Location of pre-analyzed results</a></li>
<li class="chapter" data-level="9.10.3" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-representative-plots-van-dyke"><i class="fa fa-check"></i><b>9.10.3</b> Plots for Van Dyke dataset</a></li>
</ul></li>
<li class="chapter" data-level="9.11" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-references"><i class="fa fa-check"></i><b>9.11</b> References</a></li>
</ul></li>
<li class="part"><span><b>CAD applications</b></span></li>
<li class="chapter" data-level="10" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html"><i class="fa fa-check"></i><b>10</b> Standalone CAD vs. Radiologists</a><ul>
<li class="chapter" data-level="10.1" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-how-much-finished"><i class="fa fa-check"></i><b>10.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="10.2" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-abstract"><i class="fa fa-check"></i><b>10.2</b> Abstract</a></li>
<li class="chapter" data-level="10.3" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-ker-words"><i class="fa fa-check"></i><b>10.3</b> Keywords</a></li>
<li class="chapter" data-level="10.4" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-introduction"><i class="fa fa-check"></i><b>10.4</b> Introduction</a></li>
<li class="chapter" data-level="10.5" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-methods"><i class="fa fa-check"></i><b>10.5</b> Methods</a><ul>
<li class="chapter" data-level="10.5.1" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-two-previous-studies"><i class="fa fa-check"></i><b>10.5.1</b> Studies assessing performance of CAD vs. radiologists</a></li>
<li class="chapter" data-level="10.5.2" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#the-1t-rrfc-analysis-model"><i class="fa fa-check"></i><b>10.5.2</b> The 1T-RRFC analysis model</a></li>
<li class="chapter" data-level="10.5.3" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-2TRRRC-anlaysis"><i class="fa fa-check"></i><b>10.5.3</b> The 2T-RRRC analysis model</a></li>
<li class="chapter" data-level="10.5.4" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-1TRRRC-anlaysis"><i class="fa fa-check"></i><b>10.5.4</b> The 1T-RRRC analysis model</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-computational-details"><i class="fa fa-check"></i><b>10.6</b> Software implementation</a></li>
<li class="chapter" data-level="10.7" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-results"><i class="fa fa-check"></i><b>10.7</b> Results</a></li>
<li class="chapter" data-level="10.8" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-discussion"><i class="fa fa-check"></i><b>10.8</b> Discussion</a></li>
<li class="chapter" data-level="10.9" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-appendix1"><i class="fa fa-check"></i><b>10.9</b> Appendix 1</a><ul>
<li class="chapter" data-level="10.9.1" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#example-1"><i class="fa fa-check"></i><b>10.9.1</b> Example 1</a></li>
<li class="chapter" data-level="10.9.2" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#example-2"><i class="fa fa-check"></i><b>10.9.2</b> Example 2</a></li>
<li class="chapter" data-level="10.9.3" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#example-3"><i class="fa fa-check"></i><b>10.9.3</b> Example 3</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-appendix2"><i class="fa fa-check"></i><b>10.10</b> Appendix 2</a></li>
<li class="chapter" data-level="10.11" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-references"><i class="fa fa-check"></i><b>10.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="optim-op-point.html"><a href="optim-op-point.html"><i class="fa fa-check"></i><b>11</b> Optimal operating point</a><ul>
<li class="chapter" data-level="11.1" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-how-much-finished"><i class="fa fa-check"></i><b>11.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="11.2" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-intro"><i class="fa fa-check"></i><b>11.2</b> Introduction</a></li>
<li class="chapter" data-level="11.3" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-methods"><i class="fa fa-check"></i><b>11.3</b> Methods</a></li>
<li class="chapter" data-level="11.4" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-vary-lambda"><i class="fa fa-check"></i><b>11.4</b> Varying <span class="math inline">\(\lambda\)</span> optimizations</a><ul>
<li class="chapter" data-level="11.4.1" data-path="optim-op-point.html"><a href="optim-op-point.html#summary-table"><i class="fa fa-check"></i><b>11.4.1</b> Summary table</a></li>
<li class="chapter" data-level="11.4.2" data-path="optim-op-point.html"><a href="optim-op-point.html#froc-1"><i class="fa fa-check"></i><b>11.4.2</b> FROC</a></li>
<li class="chapter" data-level="11.4.3" data-path="optim-op-point.html"><a href="optim-op-point.html#wafroc-1"><i class="fa fa-check"></i><b>11.4.3</b> wAFROC</a></li>
<li class="chapter" data-level="11.4.4" data-path="optim-op-point.html"><a href="optim-op-point.html#roc-1"><i class="fa fa-check"></i><b>11.4.4</b> ROC</a></li>
<li class="chapter" data-level="11.4.5" data-path="optim-op-point.html"><a href="optim-op-point.html#why-not-maximize-roc-auc"><i class="fa fa-check"></i><b>11.4.5</b> Why not maximize ROC-AUC?</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-vary-nu-mu"><i class="fa fa-check"></i><b>11.5</b> Varying <span class="math inline">\(\nu\)</span> and <span class="math inline">\(\mu\)</span> optimizations</a></li>
<li class="chapter" data-level="11.6" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-vary-nu-limiting-situations"><i class="fa fa-check"></i><b>11.6</b> Very high or very low performance</a></li>
<li class="chapter" data-level="11.7" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-how-to-use-method"><i class="fa fa-check"></i><b>11.7</b> Using the method</a></li>
<li class="chapter" data-level="11.8" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-application"><i class="fa fa-check"></i><b>11.8</b> A CAD application</a><ul>
<li class="chapter" data-level="11.8.1" data-path="optim-op-point.html"><a href="optim-op-point.html#summary-table-1"><i class="fa fa-check"></i><b>11.8.1</b> Summary table</a></li>
<li class="chapter" data-level="11.8.2" data-path="optim-op-point.html"><a href="optim-op-point.html#froc-2"><i class="fa fa-check"></i><b>11.8.2</b> FROC</a></li>
<li class="chapter" data-level="11.8.3" data-path="optim-op-point.html"><a href="optim-op-point.html#wafroc-2"><i class="fa fa-check"></i><b>11.8.3</b> wAFROC</a></li>
<li class="chapter" data-level="11.8.4" data-path="optim-op-point.html"><a href="optim-op-point.html#roc-2"><i class="fa fa-check"></i><b>11.8.4</b> ROC</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-discussion"><i class="fa fa-check"></i><b>11.9</b> TBA Discussion</a></li>
<li class="chapter" data-level="11.10" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-references"><i class="fa fa-check"></i><b>11.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html"><i class="fa fa-check"></i><b>12</b> Optimal operating point appendices</a><ul>
<li class="chapter" data-level="12.1" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#optim-op-point-vary-nu"><i class="fa fa-check"></i><b>12.1</b> Appendix I: Varying <span class="math inline">\(\nu\)</span> optimizations</a><ul>
<li class="chapter" data-level="12.1.1" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#summary-table-2"><i class="fa fa-check"></i><b>12.1.1</b> Summary table</a></li>
<li class="chapter" data-level="12.1.2" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#froc-3"><i class="fa fa-check"></i><b>12.1.2</b> FROC</a></li>
<li class="chapter" data-level="12.1.3" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#wafroc-3"><i class="fa fa-check"></i><b>12.1.3</b> wAFROC</a></li>
<li class="chapter" data-level="12.1.4" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#roc-3"><i class="fa fa-check"></i><b>12.1.4</b> ROC</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#optim-op-point-vary-mu"><i class="fa fa-check"></i><b>12.2</b> Appendix II: Varying <span class="math inline">\(\mu\)</span> optimizations</a><ul>
<li class="chapter" data-level="12.2.1" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#summary-table-3"><i class="fa fa-check"></i><b>12.2.1</b> Summary table</a></li>
<li class="chapter" data-level="12.2.2" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#froc-4"><i class="fa fa-check"></i><b>12.2.2</b> FROC</a></li>
<li class="chapter" data-level="12.2.3" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#wafroc-4"><i class="fa fa-check"></i><b>12.2.3</b> wAFROC</a></li>
<li class="chapter" data-level="12.2.4" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#roc-4"><i class="fa fa-check"></i><b>12.2.4</b> ROC</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#optim-op-point-limiting-situations"><i class="fa fa-check"></i><b>12.3</b> Appendix III: Limiting situations</a><ul>
<li class="chapter" data-level="12.3.1" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#optim-op-point-high-performance-vary-mu"><i class="fa fa-check"></i><b>12.3.1</b> High performance vary mu</a></li>
<li class="chapter" data-level="12.3.2" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#optim-op-point-low-performance-vary-mu"><i class="fa fa-check"></i><b>12.3.2</b> Low performance vary mu</a></li>
<li class="chapter" data-level="12.3.3" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#optim-op-point-high-performance-vary-lambda"><i class="fa fa-check"></i><b>12.3.3</b> High performance vary lambda</a></li>
<li class="chapter" data-level="12.3.4" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#optim-op-point-low-performance-vary-lambda"><i class="fa fa-check"></i><b>12.3.4</b> Low performance vary lambda</a></li>
<li class="chapter" data-level="12.3.5" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#optim-op-point-high-performance-vary-nu"><i class="fa fa-check"></i><b>12.3.5</b> High performance vary nu</a></li>
<li class="chapter" data-level="12.3.6" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#optim-op-point-low-performance-vary-nu"><i class="fa fa-check"></i><b>12.3.6</b> Low performance vary nu</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="optim-op-point-appendices.html"><a href="optim-op-point-appendices.html#optim-op-point-appendices-references"><i class="fa fa-check"></i><b>12.4</b> References</a></li>
</ul></li>
<li class="part"><span><b>DATASETS</b></span></li>
<li class="chapter" data-level="13" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>13</b> Datasets</a><ul>
<li class="chapter" data-level="13.1" data-path="datasets.html"><a href="datasets.html#datasets-datasets"><i class="fa fa-check"></i><b>13.1</b> Datasets</a></li>
<li class="chapter" data-level="13.2" data-path="datasets.html"><a href="datasets.html#datasets-references"><i class="fa fa-check"></i><b>13.2</b> References</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>REFERENCES</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The RJafroc Froc Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="rsm-pred" class="section level1 hasAnchor">
<h1><span class="header-section-number">Chapter 5</span> ROC predictions of the RSM<a href="rsm-pred.html#rsm-pred" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="rsm-pred-how-much-finished" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.1</span> TBA How much finished<a href="rsm-pred.html#rsm-pred-how-much-finished" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>90%</p>
</div>
<div id="rsm-pred-intro" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.2</span> TBA Introduction<a href="rsm-pred.html#rsm-pred-intro" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The preceding chapter described the radiological search model (RSM) for FROC data. This chapter describes the ROC curve and related predictions of the RSM. The next chapter will describe the FROC and wAFROC curve predictions.</p>
<p>The inferred-ROC z-sample and the end-point of the ROC are defined and expressions in terms of RSM parameters are derived. Derived next is the predicted <em>inferred ROC</em> curve and the probability density functions of the inferred-ROC z-samples for non-diseased and diseased cases. Integrating the total area under the predicted ROC yields ROC-AUC.</p>
<p>Since the ROC is a basic measure of performance, numerical examples are given showing the behavior of the operating point as parameters of the RSM are varied.</p>
<p>In this chapter formulae for RSM quantities are given in terms of the RSM search parameters <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(\nu\)</span>.</p>
</div>
<div id="rsm-pred-inferred-roc" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.3</span> Inferred ROC z-sample<a href="rsm-pred.html#rsm-pred-inferred-roc" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><em>The inferred ROC z-sample of a case, denoted <span class="math inline">\(h_t\)</span>, where <span class="math inline">\(t = 1\)</span> for non-diseased cases and <span class="math inline">\(t = 2\)</span> for diseased cases, is the z-sample of the highest rated latent mark on the case or <span class="math inline">\(-\infty\)</span> if the case has no latent marks.</em> The difference from the previous chapter is that in this chapter we are concerned with statistical/probabilistic modeling of the continuous z-samples instead of describing observed ratings for a finite dataset.</p>
<p>Definitions:</p>
<blockquote>
<ul>
<li><span class="math inline">\(\text{FPF}(\zeta)\)</span> = probability that <span class="math inline">\(h_1 \ge \zeta\)</span>.</li>
<li><span class="math inline">\(\text{TPF}(\zeta)\)</span> = probability that <span class="math inline">\(h_2 \ge \zeta\)</span>.</li>
</ul>
</blockquote>
<p>Accordingly, FPF and TPF are defined by:</p>
<p><span class="math display" id="eq:rsm-pred-fpf-def">\[\begin{equation}
\text{FPF}\left( \zeta \right) = \text{P} \left ( h_1 \geq \zeta\right )
\tag{5.1}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:rsm-pred-tpf-def">\[\begin{equation}
\text{TPF}\left( \zeta \right) = \text{P} \left ( h_2 \geq \zeta\right )
\tag{5.2}
\end{equation}\]</span></p>
<p>Definition of ROC plot:</p>
<blockquote>
<ul>
<li>The ROC is the plot of <span class="math inline">\(\text{TPF}(\zeta)\)</span> vs. <span class="math inline">\(\text{FPF}(\zeta)\)</span>.</li>
<li><em>The plot includes a straight line extension from the theoretical end-point to (1,1)</em>.</li>
<li>The theoretical end-point corresponds to <span class="math inline">\(\zeta = -\infty\)</span>.</li>
</ul>
</blockquote>
</div>
<div id="rsm-pred-end-point" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.4</span> End-point of the ROC<a href="rsm-pred.html#rsm-pred-end-point" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A consequence of the possibility that some cases have no marks is that the ROC curve has the <em>constrained end-point property</em>, namely the full range of ROC space, i.e., <span class="math inline">\(0 \leq \text{FPF} \leq 1\)</span> and <span class="math inline">\(0 \leq \text{TPF} \leq 1\)</span>, is not continuously accessible to the observer. In fact, <span class="math inline">\(0 \leq \text{FPF} \leq \text{FPF}_{\text{max}}\)</span> and <span class="math inline">\(0 \leq \text{TPF} \leq \text{TPF}_{\text{max}}\)</span> where <span class="math inline">\(\text{FPF}_{\text{max}}\)</span> and <span class="math inline">\(\text{TPF}_{\text{max}}\)</span> are generally less than unity.</p>
<p>Starting from <span class="math inline">\(\infty\)</span> as <span class="math inline">\(\zeta\)</span> is lowered to <span class="math inline">\(-\infty\)</span> some of the cases that had at least one latent site but whose z-sample did not exceed <span class="math inline">\(\zeta\)</span> will now generate marks and contribute to <span class="math inline">\(\text{FPF}\)</span> and <span class="math inline">\(\text{TPF}\)</span> resulting in upward and rightward movement of the theoretical operating point until eventually <em>only cases with no latent sites</em> remain. These cases cannot generate marks. The finite number of cases with no marks has the consequence that the uppermost continuously accessible operating point is below-left of (1,1). The (1,1) point is “trivially” reached when one cumulates cases with no marks, i.e., those rated <span class="math inline">\(-\infty\)</span>.</p>
<p>This behavior is distinct from conventional ROC models where the entire curve, extending from (0, 0) to (1, 1), is continuously accessible. This is because every case yields a finite decision variable, no matter how small. The number of cases with <span class="math inline">\(-\infty\)</span> rating is zero. When <span class="math inline">\(\zeta = -\infty\)</span> the operating point reaches (1,1).</p>
<div id="rsm-pred-constrained-end-point-abscissa" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.4.1</span> The abscissa of the ROC end-point<a href="rsm-pred.html#rsm-pred-constrained-end-point-abscissa" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Consider the probability that a non-diseased case has at least one latent NL. Such a case will generate a finite value of <span class="math inline">\(h_1\)</span> and with an appropriately low <span class="math inline">\(\zeta\)</span> it will be marked. The probability of <em>zero</em> latent NLs, see Eqn. <a href="rsm.html#eq:rsm-poisson-PMF">(4.2)</a>, is:</p>
<p><span class="math display">\[\text{PMF}_{Pois} \left (0,\lambda \right ) = \text{exp} \left ( -\lambda \right )\]</span>.</p>
<p>The probability that the case has <em>at least one</em> latent NL is the complement of the above probability. At sufficiently low <span class="math inline">\(\zeta\)</span> each of these cases yields a marked non-disease case. Therefore, the maximum continuously accessible abscissa of the ROC, i.e., <span class="math inline">\(\text{FPF}_{\text{max}}\)</span>, is:</p>
<p><span class="math display" id="eq:rsm-pred-fpf-max">\[\begin{equation} 
\text{FPF}_{\text{max}} = 1 - \text{exp} \left ( -\lambda \right )
\tag{5.3}
\end{equation}\]</span></p>
</div>
<div id="rsm-pred-constrained-end-point-ordinate" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.4.2</span> The ordinate of the ROC end-point<a href="rsm-pred.html#rsm-pred-constrained-end-point-ordinate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A diseased case has no marks, even for very low <span class="math inline">\(\zeta\)</span>, if it has zero latent NLs, the probability of which is <span class="math inline">\(\text{exp}(-\lambda)\)</span>, and it has zero latent LLs, the probability of which is, see Eqn. <a href="rsm.html#eq:rsm-binomial-PMF">(4.4)</a>, <span class="math inline">\(\text{PMF}_{B} \left ( 0, L, \nu \right )= (1 - \nu)^L\)</span>.</p>
<p>Here <span class="math inline">\(L\)</span> is the number of lesions in each diseased case.</p>
<ul>
<li><p>Assumption 1: occurrences of latent LLs are independent of each other, i.e., the probability that a lesion is found is independent of whether other lesions are found on the same case.</p></li>
<li><p>Assumption 2: occurrences of latent NLs are independent of each other; i.e., the probability of a NL is independent of whether other NLs are found on the same case.</p></li>
<li><p>Assumption 3: occurrence of a latent NL is independent of the occurrence of a latent LL on the same case.</p></li>
</ul>
<p>By these assumptions the probability of zero latent NLs <em>and</em> zero latent LLs on a diseased case is the product of the two probabilities, namely</p>
<p><span class="math display">\[\text{exp}(-\lambda) (1 - \nu)^L\]</span>.</p>
<p>The probability that there exists <em>at least one</em> latent site is the complement of the above expression, which equals <span class="math inline">\(\text{TPF}_{\text{max}}\)</span>, i.e.,</p>
<p><span class="math display" id="eq:rsm-pred-tpf-max">\[\begin{equation}
\text{TPF}_{\text{max}} = 1 - \text{exp} \left ( - \lambda \right ) \left ( 1 - \nu \right )^L
\tag{5.4}
\end{equation}\]</span></p>
</div>
<div id="rsm-pred-end-point-variable-number-lesions" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.4.3</span> Variable number of lesions per case<a href="rsm-pred.html#rsm-pred-end-point-variable-number-lesions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Defining <span class="math inline">\(f_L\)</span> the fraction of diseased cases with <span class="math inline">\(L\)</span> lesions and <span class="math inline">\(L_{max}\)</span> the maximum number of lesions per diseased case in the dataset, then:</p>
<p><span class="math display" id="eq:rsm-pred-fl-sum">\[\begin{equation}
\sum_{L=1}^{{L_{max}}}  f_L = 1
\tag{5.5}
\end{equation}\]</span></p>
<p>By restricting attention to the set of diseased cases with <span class="math inline">\(L\)</span> lesions each, Eqn. <a href="rsm-pred.html#eq:rsm-pred-tpf-max">(5.4)</a> for <span class="math inline">\(\text{TPF}_{\text{max}}\)</span> applies. Since TPF is a probability and probabilities of independent processes add it follows that:</p>
<p><span class="math display" id="eq:rsm-pred-tpf-max-vary-l">\[\begin{equation}
\text{TPF}_{\text{max}} = 1 - \sum_{L=1}^{L_{max}}f_L\text{exp} \left ( - \lambda \right ) \left ( 1 - \nu \right )^L
\tag{5.6}
\end{equation}\]</span></p>
<p>The ordinate of the end-point is a <span class="math inline">\(f_L\)</span> weighted summation of <span class="math inline">\(\text{TPF}_{\text{max}}\)</span>. The expression for <span class="math inline">\(\text{FPF}_{\text{max}}\)</span> is unaffected.</p>
</div>
</div>
<div id="rsm-pred-roc-curve" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.5</span> ROC curve<a href="rsm-pred.html#rsm-pred-roc-curve" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>On the continuous ROC curve each case has at least one mark and the ROC decision variable is the rating of the highest rated mark <span class="math inline">\(h_t\)</span> on the case. Therefore Eqn. <a href="rsm-pred.html#eq:rsm-pred-fpf-def">(5.1)</a> and Eqn. <a href="rsm-pred.html#eq:rsm-pred-tpf-def">(5.2)</a> apply. Varying the threshold parameter <span class="math inline">\(\zeta\)</span> from <span class="math inline">\(\infty\)</span> to <span class="math inline">\(-\infty\)</span> sweeps out the continuous section of the predicted ROC curve from (0,0) to <span class="math inline">\(\left (\text{FPF}_{\text{max}}, \text{TPF}_{\text{max}} \right )\)</span>.</p>
<div id="rsm-pred-roc-curve-fpf" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.5.1</span> Derivation of FPF<a href="rsm-pred.html#rsm-pred-roc-curve-fpf" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Assumption 4: the z-samples of latent NLs on the same case are independent of each other.</li>
</ul>
<p>Consider the set of non-diseased cases with <span class="math inline">\(n\)</span> latent NLs each, where <span class="math inline">\(n &gt; 0\)</span>. According to <a href="rsm.html#rsm-assumptions">4.4</a> each latent NL yields a z sample from <span class="math inline">\(N(0,1)\)</span>. The probability that a z-sample from a latent NL is smaller than <span class="math inline">\(\zeta\)</span> is <span class="math inline">\(\Phi(\zeta)\)</span>. The probability that all <span class="math inline">\(n\)</span> z-samples are smaller than <span class="math inline">\(\zeta\)</span> is <span class="math inline">\((\Phi(\zeta))^n\)</span>. If all z-samples are smaller than <span class="math inline">\(\zeta\)</span>, then the highest z-sample <span class="math inline">\(h_t\)</span> must be smaller than <span class="math inline">\(\zeta\)</span>. Therefore, the probability that <span class="math inline">\(h_t\)</span> exceeds <span class="math inline">\(\zeta\)</span> is:</p>
<p><span class="math display" id="eq:rsm-pred-fpf-zeta-n">\[\begin{equation}
\left. 
\begin{aligned}
\text{FPF}\left (\zeta \mid n \right ) =&amp; P\left ( h_1 \geq  \zeta \mid n\right ) \\
=&amp; 1 - \left [ \Phi\left ( \zeta \right )  \right ]^n
\end{aligned}
\right \}
\tag{5.7}
\end{equation}\]</span></p>
<p>The conditioning notation in Eqn. <a href="rsm-pred.html#eq:rsm-pred-fpf-zeta-n">(5.7)</a> reflects the fact that this expression applies specifically to non-diseased cases each with <span class="math inline">\(n\)</span> latent NLs. To obtain <span class="math inline">\(\text{FPF}_{\text{max}}\)</span> one performs a Poissson PMF-weighted summation of <span class="math inline">\(\text{FPF}\left (\zeta \mid n \right )\)</span> over <span class="math inline">\(n\)</span> from 0 to <span class="math inline">\(\infty\)</span> (the inclusion of the <span class="math inline">\(n = 0\)</span> term is explained below):</p>
<p><span class="math display" id="eq:rsm-pred-fpf-zeta-before-maple">\[\begin{equation}
\text{FPF}\left (\zeta, \lambda \right ) = \sum_{n=0}^{\infty} \text{PMF}_{\text{Pois}} \left ( n, \lambda \right )\text{FPF}\left (\zeta \mid n \right )
\tag{5.8}
\end{equation}\]</span></p>
<p>The infinite summations, see below, are easier performed using symbolic algebra software such as <span class="math inline">\(\text{Maple}^{TM}\)</span>. Inclusion in the summation of <span class="math inline">\(n = 0\)</span>, which evaluates to zero, is done to make it easier for <span class="math inline">\(\text{Maple}^{TM}\)</span> to evaluate the summation in closed form. Otherwise one may need to simplify the <span class="math inline">\(\text{Maple}^{TM}\)</span>-generated result. The <span class="math inline">\(\text{Maple}^{TM}\)</span> code is shown below (Maple 17, Waterloo Maple Inc.).</p>
<pre><code># Maple Code
restart;
phi := proc (t, mu) exp(-(1/2)*(t-mu)^2)/sqrt(2*Pi) end: 
PHI := proc (c, mu) local t; int(phi(t, mu), t = -infinity .. c) end: 
Poissson := proc (n, lambda) lambda^n*exp(-lambda)/factorial(n) end: 
B := proc (l, L, nu) binomial(L, l)*nu^l*(1-nu)^(L-l) end:
FPF := proc(zeta,lambda) sum(Poissson(n,lambda)*
(1 - PHI(zeta,0)^n), n=0..infinity);end:
FPF(zeta, lambda);   </code></pre>
<p>The above code yields:</p>
<p><span class="math display" id="eq:rsm-pred-fpf-erf">\[\begin{equation}
\text{FPF}\left (\zeta , \lambda\right ) = 1 - \text{exp}\left ( -\frac{\lambda}{2} \left [ 1-\text{erf}\left ( \frac{\zeta}{\sqrt{2}} \right ) \right ]  \right ) 
\tag{5.9}
\end{equation}\]</span></p>
<p>The error function in Eqn. <a href="rsm-pred.html#eq:rsm-pred-fpf-erf">(5.9)</a> is related to the unit normal CDF function <span class="math inline">\(\Phi(x)\)</span> by:</p>
<p><span class="math display" id="eq:rsm-pred-erf-phi-relation">\[\begin{equation}
\text{erf} \left (x \right ) =  2\Phi \left ( \sqrt{2} x\right ) - 1
\tag{5.10}
\end{equation}\]</span></p>
<p>Using this transformation yields the following simpler expression for FPF:</p>
<p><span class="math display" id="eq:rsm-pred-fpf">\[\begin{equation}
\text{FPF}\left (\zeta , \lambda\right ) = 1 - \text{exp}\left ( -\lambda \Phi\left ( -\zeta \right )  \right )
\tag{5.11}
\end{equation}\]</span></p>
<p>The <code>R</code> implementation follows:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="rsm-pred.html#cb58-1"></a><span class="co"># lambda is the physical lambda&#39; parameter</span></span>
<span id="cb58-2"><a href="rsm-pred.html#cb58-2"></a>FPF &lt;-<span class="st"> </span><span class="cf">function</span> (zeta, lambda) {</span>
<span id="cb58-3"><a href="rsm-pred.html#cb58-3"></a>  x =<span class="st"> </span><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">exp</span>(<span class="op">-</span>lambda <span class="op">*</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="op">-</span>zeta))</span>
<span id="cb58-4"><a href="rsm-pred.html#cb58-4"></a>  <span class="kw">return</span>(x)</span>
<span id="cb58-5"><a href="rsm-pred.html#cb58-5"></a>}</span></code></pre></div>
<p>Because <span class="math inline">\(\Phi\)</span> ranges from 0 to 1, <span class="math inline">\(\text{FPF}\left (\zeta , \lambda\right )\)</span> ranges from 0 to <span class="math inline">\(\text{exp} \left ( -\lambda \right )\)</span>.</p>
</div>
<div id="rsm-pred-roc-curve-tpf" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.5.2</span> Derivation of TPF<a href="rsm-pred.html#rsm-pred-roc-curve-tpf" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The derivation of the true positive fraction <span class="math inline">\(\text{TPF}(\zeta)\)</span> follows a similar line of reasoning except this time one needs to consider the highest of the latent NLs and latent LL z-samples. Consider a diseased case with L lesions, <span class="math inline">\(n\)</span> latent NLs and <span class="math inline">\(l\)</span> latent LLs. Each latent NL yields a decision variable sample from <span class="math inline">\(N(0,1)\)</span> and each latent LL yields a sample from <span class="math inline">\(N(\mu,1)\)</span>. The probability that all <span class="math inline">\(n\)</span> latent NLs have z-samples less than <span class="math inline">\(\zeta\)</span> is <span class="math inline">\([\Phi(\zeta)]^n\)</span>. The probability that all <span class="math inline">\(l\)</span> latent LLs have z-samples less than <span class="math inline">\(\zeta\)</span> is <span class="math inline">\([\Phi(\zeta - \mu)]^l\)</span>. The probability that all latent marks have z-samples less than <span class="math inline">\(\zeta\)</span> is the product of these two probabilities. The probability that <span class="math inline">\(h_2\)</span> (the highest z-sample on a diseased case) is larger than <span class="math inline">\(\zeta\)</span> is the complement of the product probabilities, i.e.,</p>
<p><span class="math display" id="eq:rsm-pred-tpf-vary-nl">\[\begin{equation}
\left. 
\begin{aligned}
\text{TPF}\left ( \zeta, \mu, n, l, L \right ) =&amp; 
P\left ( h_2 \geq \zeta \mid \mu, n, l, L \right ) \\
=&amp; 1 - \left [ \Phi\left ( \zeta \right ) \right ]^n \left [ \Phi\left ( \zeta - \mu\right ) \right ]^l
\end{aligned}
\right \}
\tag{5.12}
\end{equation}\]</span></p>
<p>One averages over the distributions of <span class="math inline">\(n\)</span> and <span class="math inline">\(l\)</span> to obtain the desired ROC-ordinate:</p>
<p><span class="math display" id="eq:rsm-pred-tpf-double-summation">\[\begin{equation}
\left.
\begin{aligned}
\text{TPF}\left ( \zeta, \mu, \lambda, \nu \right ) =&amp; \sum_{n=0}^{\infty} \text{PMF}_{Pois}(n,\lambda) \\
&amp;\times \sum_{l=0}^{L} \text{PMF}_{B}(l,\nu,L) \text{TPF}_{n,l}\left ( \zeta, \mu, n, l \right )
\end{aligned}
\right \}
\tag{5.13}
\end{equation}\]</span></p>
<p>This can be evaluated using <span class="math inline">\(\text{Maple}^{TM}\)</span> yielding:</p>
<p><span class="math display" id="eq:rsm-pred-tpf">\[\begin{equation}
\left.
\begin{aligned}
&amp; \text{TPF}\left (\zeta , \mu, \lambda, \nu, L \right ) \\
&amp;= 1 - \text{exp}\left ( - \lambda \Phi \left ( - \zeta \right )\right )
\left ( 1 - \nu \Phi \left ( \mu - \zeta \right ) \right )^L
\end{aligned}
\right \}
\tag{5.14}
\end{equation}\]</span></p>
</div>
<div id="rsm-pred-tpf-varying-lesions" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.5.3</span> Variable number of lesions per case<a href="rsm-pred.html#rsm-pred-tpf-varying-lesions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To extend the results to varying numbers of lesions per diseased case, one averages the right hand side of <a href="rsm-pred.html#eq:rsm-pred-tpf">(5.14)</a> over the fraction of diseased cases with <span class="math inline">\(L\)</span> lesions:</p>
<p><span class="math display" id="eq:rsm-pred-tpf2">\[\begin{equation}
\left.
\begin{aligned}
&amp; \text{TPF}\left (\zeta , \mu, \lambda, \nu, \overrightarrow{f_L} \right ) =  \\
&amp; 1 - \text{exp}\left ( -\lambda \Phi \left ( -\zeta \right )\right ) 
\sum_{L=1}^{L_{max}} f_L  \left ( 1 - \nu \Phi \left ( \mu -\zeta \right ) \right )^L 
\end{aligned}
\right \}
\tag{5.15}
\end{equation}\]</span></p>
<p>Since <span class="math inline">\(\Phi \left ( -\zeta \right )\)</span> tends to unity as <span class="math inline">\(\zeta \rightarrow -\infty\)</span>, this expression reduces to Eqn. <a href="rsm-pred.html#eq:rsm-pred-tpf-max-vary-l">(5.6)</a> for the ROC end-point. The expression for FPF, Eqn. <a href="rsm-pred.html#eq:rsm-pred-fpf">(5.11)</a>, is unaffected.</p>
<p>The <code>R</code> implementation follows:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="rsm-pred.html#cb59-1"></a><span class="co"># lesDistr is the lesion distribution vector f_L</span></span>
<span id="cb59-2"><a href="rsm-pred.html#cb59-2"></a>TPF &lt;-<span class="st"> </span><span class="cf">function</span> (zeta, mu, lambda, nu, lesDistr){</span>
<span id="cb59-3"><a href="rsm-pred.html#cb59-3"></a>  Lmax &lt;-<span class="st"> </span><span class="kw">length</span>(lesDistr)</span>
<span id="cb59-4"><a href="rsm-pred.html#cb59-4"></a>  x &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb59-5"><a href="rsm-pred.html#cb59-5"></a>  <span class="cf">for</span> (L <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>Lmax ) {</span>
<span id="cb59-6"><a href="rsm-pred.html#cb59-6"></a>    x &lt;-<span class="st"> </span>x <span class="op">-</span><span class="st"> </span><span class="kw">exp</span>(<span class="op">-</span>lambda <span class="op">*</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="op">-</span>zeta)) <span class="op">*</span><span class="st"> </span></span>
<span id="cb59-7"><a href="rsm-pred.html#cb59-7"></a><span class="st">      </span>lesDistr[L] <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>nu <span class="op">*</span><span class="st"> </span><span class="kw">pnorm</span>(mu <span class="op">-</span><span class="st"> </span>zeta))<span class="op">^</span>L</span>
<span id="cb59-8"><a href="rsm-pred.html#cb59-8"></a>  }</span>
<span id="cb59-9"><a href="rsm-pred.html#cb59-9"></a>  <span class="kw">return</span>(x)</span>
<span id="cb59-10"><a href="rsm-pred.html#cb59-10"></a>}</span></code></pre></div>
</div>
<div id="rsm-pred-roc-curve-pdfs" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.5.4</span> ROC decision variable pdfs<a href="rsm-pred.html#rsm-pred-roc-curve-pdfs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the ROC <a href="https://dpc10ster.github.io/RJafrocRocBook/">book</a>, pdf functions were derived for non-diseased and diseased cases for the unequal variance binormal ROC model. The procedure was to take the derivative of the appropriate <em>cumulative distribution function</em> (CDF) with respect to <span class="math inline">\(\zeta\)</span>. An identical procedure is used for the RSM.</p>
<p>The CDF for non-diseased cases is the complement of FPF. The pdf for non-diseased cases is given by:</p>
<p><span class="math display" id="eq:rsm-pred-pdf-n">\[\begin{equation}
\text{pdf}_N\left ( \zeta \right ) = \frac{\partial }{\partial \zeta} \left ( 1-\text{FPF}\left (\zeta , \lambda\right ) \right ) 
\tag{5.16}
\end{equation}\]</span></p>
<p>For diseased cases,</p>
<p><span class="math display" id="eq:rsm-pred-pdf-d">\[\begin{equation}
\text{pdf}_D\left ( \zeta \right ) = \frac{\partial }{\partial \zeta} \left ( 1-\text{TPF}\left (\zeta , \mu, \lambda, \nu, \overrightarrow{f_L} \right ) \right ) 
\tag{5.17}
\end{equation}\]</span></p>
<p>Both expressions can be evaluated using <span class="math inline">\(\text{Maple}^{TM}\)</span>. The pdfs are implemented in the <code>RJafroc</code> function <code>PlotRsmOperatingCharacteristics()</code>.</p>
<p>The integrals of the pdfs (non-diseased followed by diseased) over the entire allowed range are given by (note the vertical bar notation, meaning the difference of two limiting values of <span class="math inline">\(\zeta\)</span>):</p>
<p><span class="math display" id="eq:rsm-pred-int-pdf-n">\[\begin{equation}
\left. 
\begin{aligned}
\int_{-\infty}^{\infty}\text{pdf}_N \left ( \zeta \right )d \zeta =&amp; \left ( 1-\text{FPF}\left (\zeta , \lambda\right ) \right ) \bigg \rvert_{-\infty}^{\infty}\\
=&amp; \text{FPF}_{\text{max}}
\end{aligned}
\right \}
\tag{5.18}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:rsm-pred-int-pdf-d">\[\begin{equation}
\left. 
\begin{aligned}
\int_{-\infty}^{\infty}\text{pdf}_D \left ( \zeta \right )d \zeta =&amp; \left ( 1-\text{TPF}\left (\zeta , \mu, \lambda, \nu, \overrightarrow{f_L} \right ) \right ) \bigg \rvert_{-\infty}^{\infty}\\
=&amp; \text{TPF}_{\text{max}}
\end{aligned}
\right \}
\tag{5.19}
\end{equation}\]</span></p>
<p>In other words, they evaluate to the coordinates of the predicted end-point, <em>each of which is less than unity</em>. The reason is that the integration is along the <em>continuous</em> section of the ROC curve and does not include the contribution along the dashed straight line extension from <span class="math inline">\(\left ( \text{FPF}_{\text{max}}, \text{TPF}_{\text{max}} \right )\)</span> to (1,1). The latter contributions correspond to cases with no marks, i.e., <span class="math inline">\(1 - \text{FPF}_{\text{max}}\)</span> for non-diseased cases and <span class="math inline">\(1 - \text{TPF}_{\text{max}}\)</span> for diseased cases. Adding these contributions to the integrals along the continuous section yields unity for both types of cases.<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a></p>
</div>
<div id="rsm-pred-roc-curve-auc" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.5.5</span> ROC AUC<a href="rsm-pred.html#rsm-pred-roc-curve-auc" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It is possible to numerically perform the integration under the RSM-ROC curve to get AUC:</p>
<p><span class="math display" id="eq:rsm-pred-auc">\[\begin{equation}
AUC_{RSM}^{ROC}\left ( \mu, \lambda, \nu,  \zeta, \overrightarrow{f_L} \right ) = \sum_{L=0}^{L_{max}} f_L \int_{0}^{1} \text{TPF}\left (\zeta,  \mu, \lambda, \nu, L \right ) d\left ( \text{FPF}\left (\zeta, \lambda \right ) \right )
\tag{5.20}
\end{equation}\]</span></p>
<p>The superscript <span class="math inline">\(ROC\)</span> is needed to keep track of the operating characteristic that is being predicted (for RSM other possibilities are AFROC, wAFROC, FROC) and the subscript <span class="math inline">\(RSM\)</span> keeps track of the predictive model that is being used (for ROC models - binormal, CBM or PROPROC - the superscript is always ROC).</p>
<p>The right hand side of Eqn. <a href="rsm-pred.html#eq:rsm-pred-auc">(5.20)</a> can be evaluated using a numerical integration function implemented in <code>R</code>, which is used in the <code>RJafroc</code> function <code>UtilAnalyticalAucsRSM()</code> whose help page follows:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rsm-pred-help"></span>
<img src="images/rsm-pred/util-analytical-aucs-rsm.png" alt="Help page for `RJafroc` function `UtilAnalyticalAucsRSM`." width="300pt" />
<p class="caption">
FIGURE 5.1: Help page for <code>RJafroc</code> function <code>UtilAnalyticalAucsRSM</code>.
</p>
</div>
<p>The arguments to <code>UtilAnalyticalAucsRSM()</code> are the intrinsic RSM parameters <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\lambda\)</span>, <span class="math inline">\(\nu\)</span> and <span class="math inline">\(\zeta\)</span>. The default value of <span class="math inline">\(\zeta\)</span> is <span class="math inline">\(\zeta = -\infty\)</span>. The remaining arguments <code>lesDistr</code> and <code>relWeights</code> are not RSM parameters per se, rather they specify the lesion-richness of the diseased cases and the relative lesion weights (not needed for computing ROC AUC). The dimensions of <code>lesDistr</code> and <code>relWeights</code> are each equal to the maximum number of lesions per case <span class="math inline">\(L_{max}\)</span>. In the following code <span class="math inline">\(L_{max} = 3\)</span> and <code>lesDistr &lt;- c(0.5, 0.3, 0.2)</code>, meaning 50 percent of diseased cases have one lesion per case, 30 percent have two lesions and 20 percent have three lesions.</p>
<p>The function returns a list containing the AUCs under the ROC and other operating characteristics.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="rsm-pred.html#cb60-1"></a>mu &lt;-<span class="st"> </span><span class="dv">1</span>; lambda &lt;-<span class="st"> </span><span class="dv">1</span>; nu &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb60-2"><a href="rsm-pred.html#cb60-2"></a>lesDistr &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.5</span>, <span class="fl">0.3</span>, <span class="fl">0.2</span>) <span class="co"># implies L_max = 3</span></span>
<span id="cb60-3"><a href="rsm-pred.html#cb60-3"></a>aucs &lt;-<span class="st"> </span><span class="kw">UtilAnalyticalAucsRSM</span>(<span class="dt">mu =</span> mu, </span>
<span id="cb60-4"><a href="rsm-pred.html#cb60-4"></a>                              <span class="dt">lambda =</span> lambda, </span>
<span id="cb60-5"><a href="rsm-pred.html#cb60-5"></a>                              <span class="dt">nu =</span> nu, </span>
<span id="cb60-6"><a href="rsm-pred.html#cb60-6"></a>                              <span class="dt">lesDistr =</span> lesDistr)</span>
<span id="cb60-7"><a href="rsm-pred.html#cb60-7"></a><span class="kw">cat</span>(<span class="st">&quot;mu = &quot;</span>, mu, </span>
<span id="cb60-8"><a href="rsm-pred.html#cb60-8"></a><span class="st">&quot;, lambda = &quot;</span>, lambda, </span>
<span id="cb60-9"><a href="rsm-pred.html#cb60-9"></a><span class="st">&quot;, nu = &quot;</span>, nu,  </span>
<span id="cb60-10"><a href="rsm-pred.html#cb60-10"></a><span class="st">&quot;, AUC ROC = &quot;</span>, aucs<span class="op">$</span>aucROC, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## mu =  1 , lambda =  1 , nu =  1 , AUC ROC =  0.8817798</code></pre>
<p>Experimenting with different parameter combinations reveals the following behavior for ROC AUC.</p>
<ul>
<li><p>AUC is an increasing functions of <span class="math inline">\(\mu\)</span>. Increasing perceptual signal-to-noise-ratio leads to improved performance: for background on this important dependence see <a href="froc-paradigm.html#froc-paradigm-solar-analogy">1.6</a>. Increasing <span class="math inline">\(\mu\)</span> increases the separation between the two pdfs defining the ROC curve, which increases AUC. Furthermore, the number of NLs decreases because <span class="math inline">\(\lambda = \lambda / \mu\)</span> decreases, which increases performance. Finally, <span class="math inline">\(\nu\)</span> increases approaching unity, which leads to more LLs and increased performance. <em>Because all three effects reinforce each other, a change in <span class="math inline">\(\mu\)</span> results in a large effect on performance.</em></p></li>
<li><p>AUC increases as <span class="math inline">\(\lambda\)</span> decreases. Decreasing <span class="math inline">\(\lambda\)</span> results in fewer NLs which results in increased performance. This is a relatively weak effect.</p></li>
<li><p>AUC increases as <span class="math inline">\(\nu\)</span> increases. Increasing <span class="math inline">\(\nu\)</span> results in more LLs being marked, which increases performance. This is a relatively strong effect.</p></li>
<li><p>AUC decreases as <span class="math inline">\(\zeta\)</span> increases. This important effect is discussed in the next section.</p></li>
<li><p>ROC AUC increases with <span class="math inline">\(L_{max}\)</span>. With more lesions per case, there is increased probability that that at least one of them will result in a LL, and the diseased case pdf moves to the right, both of which result in increased performance.</p></li>
<li><p>ROC AUC increases as <code>lesDistr</code> is weighted towards more lesions per case. For example, <code>lesDistr &lt;- c(0, 0, 1)</code> (all cases have 3 lesions per case) will yield higher performance than <code>lesDistr &lt;- c(1, 0, 0)</code> (all cases have one lesion per case).</p></li>
</ul>
</div>
<div id="comparing-tpf-formula-to-rjafroc-functions" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.5.6</span> Comparing TPF formula to <code>RJafroc</code> functions<a href="rsm-pred.html#comparing-tpf-formula-to-rjafroc-functions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A hand calculation is shown and compared to the value yielded by the function <code>RSM_yROC</code>. The RSM parameters and the value of <span class="math inline">\(\zeta\)</span> are:</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="rsm-pred.html#cb62-1"></a>zeta &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb62-2"><a href="rsm-pred.html#cb62-2"></a>mu &lt;-<span class="st"> </span><span class="dv">2</span></span>
<span id="cb62-3"><a href="rsm-pred.html#cb62-3"></a>lambda &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb62-4"><a href="rsm-pred.html#cb62-4"></a>nu &lt;-<span class="st"> </span><span class="fl">0.9</span></span>
<span id="cb62-5"><a href="rsm-pred.html#cb62-5"></a>lesDistr &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.5</span>,<span class="fl">0.5</span>)</span></code></pre></div>
<p>The <code>lesDistr</code> vector corresponds to <span class="math inline">\(f_L\)</span> and specifies <span class="math inline">\(L_{max} = 2\)</span> and 50 percent of diseased cases have one lesion per case and the rest have two lesions per case.</p>
<p>Direct implementation of Eqn. <a href="rsm-pred.html#eq:rsm-pred-tpf2">(5.15)</a> followed by usage of the function <code>RSM_yROC</code> follows:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="rsm-pred.html#cb63-1"></a><span class="kw">cat</span>(<span class="dv">1</span><span class="op">-</span></span>
<span id="cb63-2"><a href="rsm-pred.html#cb63-2"></a><span class="kw">exp</span>(<span class="op">-</span>lambda<span class="op">*</span><span class="kw">pnorm</span>(<span class="op">-</span>zeta))<span class="op">*</span></span>
<span id="cb63-3"><a href="rsm-pred.html#cb63-3"></a>(lesDistr[<span class="dv">1</span>]<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>nu<span class="op">*</span><span class="kw">pnorm</span>(mu<span class="op">-</span>zeta))<span class="op">+</span></span>
<span id="cb63-4"><a href="rsm-pred.html#cb63-4"></a>lesDistr[<span class="dv">2</span>]<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>nu<span class="op">*</span><span class="kw">pnorm</span>(mu<span class="op">-</span>zeta))<span class="op">^</span><span class="dv">2</span>))</span></code></pre></div>
<pre><code>## 0.8712655</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="rsm-pred.html#cb65-1"></a><span class="kw">cat</span>(<span class="kw">RSM_yROC</span>(zeta,mu,lambda,nu, <span class="dt">lesDistr =</span> lesDistr))</span></code></pre></div>
<pre><code>## 0.8712655</code></pre>
<p>The two values are identical.</p>
</div>
<div id="effect-on-operating-point-of-varying-rsm-parameters" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.5.7</span> Effect on operating point of varying RSM parameters<a href="rsm-pred.html#effect-on-operating-point-of-varying-rsm-parameters" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It is instructive to understand the effects of varying the RSM parameters on the operating point on the ROC curve.</p>
<div id="vary-mu" class="section level4 hasAnchor">
<h4><span class="header-section-number">5.5.7.1</span> Vary <span class="math inline">\(\mu\)</span><a href="rsm-pred.html#vary-mu" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## lesDistr =  0.1 0.9</code></pre>
<pre><code>## Varying mu only: 
## Other parameters are lambda =  2 , nu =  0.5 , zeta =  0</code></pre>
<pre><code>## mu = 0 , RSM-x = 0.6321 , RSM-y = 0.7862 
## mu = 0.5 , RSM-x = 0.6321 , RSM-y = 0.8342 
## mu = 1 , RSM-x = 0.6321 , RSM-y = 0.8676 
## mu = 1.5 , RSM-x = 0.6321 , RSM-y = 0.8862 
## mu = 2 , RSM-x = 0.6321 , RSM-y = 0.8946 
## mu = 2.5 , RSM-x = 0.6321 , RSM-y = 0.8977 
## mu = 3 , RSM-x = 0.6321 , RSM-y = 0.8986 
## mu = 3.5 , RSM-x = 0.6321 , RSM-y = 0.8988 
## mu = 4 , RSM-x = 0.6321 , RSM-y = 0.8988 
## mu = 4.5 , RSM-x = 0.6321 , RSM-y = 0.8988 
## mu = 5 , RSM-x = 0.6321 , RSM-y = 0.8988</code></pre>
<p>The abscissa is independent of <span class="math inline">\(\mu\)</span> (because this parameter has no effect on non-diseased cases) and the ordinate is an increasing function of <span class="math inline">\(\mu\)</span> (as expected for increasing separation of the LL and NL distributions; the LLs on diseased cases are rated higher causing the distribution of <span class="math inline">\(h_2\)</span> to shift to higher values).</p>
</div>
<div id="vary-lambda" class="section level4 hasAnchor">
<h4><span class="header-section-number">5.5.7.2</span> Vary <span class="math inline">\(\lambda\)</span><a href="rsm-pred.html#vary-lambda" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## lesDistr =  0.1 0.9</code></pre>
<pre><code>## Varying lambda only: 
## Other parameters are mu =  1 , nu =  0.5 , zeta =  0</code></pre>
<pre><code>## lambda = 0.5 , RSM-x = 0.2212 , RSM-y = 0.7196 
## lambda = 1 , RSM-x = 0.3935 , RSM-y = 0.7817 
## lambda = 1.5 , RSM-x = 0.5276 , RSM-y = 0.8300 
## lambda = 2 , RSM-x = 0.6321 , RSM-y = 0.8676 
## lambda = 2.5 , RSM-x = 0.7135 , RSM-y = 0.8969 
## lambda = 3 , RSM-x = 0.7769 , RSM-y = 0.9197 
## lambda = 3.5 , RSM-x = 0.8262 , RSM-y = 0.9374 
## lambda = 4 , RSM-x = 0.8647 , RSM-y = 0.9513 
## lambda = 4.5 , RSM-x = 0.8946 , RSM-y = 0.9621 
## lambda = 5 , RSM-x = 0.9179 , RSM-y = 0.9705</code></pre>
<p>The abscissa increases with <span class="math inline">\(\lambda\)</span> (more NLs on non-diseased cases are generated causing the distribution of <span class="math inline">\(h_1\)</span> to shift to higher values) and the ordinate also increases with <span class="math inline">\(\lambda\)</span> (more NLs on diseased cases are generated causing the distribution of <span class="math inline">\(h_2\)</span> to shift to higher values - recall that on diseased cases the highest z-sample is the maximum of NL and LL z-samples, whichever is highest).</p>
</div>
<div id="vary-nu" class="section level4 hasAnchor">
<h4><span class="header-section-number">5.5.7.3</span> Vary <span class="math inline">\(\nu\)</span><a href="rsm-pred.html#vary-nu" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## lesDistr =  0.1 0.9</code></pre>
<pre><code>## Varying nu only: 
## Other parameters are mu =  1 , lambda =  2 , zeta =  0</code></pre>
<pre><code>## nu = 0 , RSM-x = 0.6321 , RSM-y = 0.6321 
## nu = 0.1 , RSM-x = 0.6321 , RSM-y = 0.6886 
## nu = 0.2 , RSM-x = 0.6321 , RSM-y = 0.7404 
## nu = 0.3 , RSM-x = 0.6321 , RSM-y = 0.7875 
## nu = 0.4 , RSM-x = 0.6321 , RSM-y = 0.8299 
## nu = 0.5 , RSM-x = 0.6321 , RSM-y = 0.8676 
## nu = 0.6 , RSM-x = 0.6321 , RSM-y = 0.9006 
## nu = 0.7 , RSM-x = 0.6321 , RSM-y = 0.9289 
## nu = 0.8 , RSM-x = 0.6321 , RSM-y = 0.9526 
## nu = 0.9 , RSM-x = 0.6321 , RSM-y = 0.9716</code></pre>
<p>No effect on the abscissa as <span class="math inline">\(\nu\)</span> increases (this parameter has no effect on non-diseased case sampling) and the ordinate increases with <span class="math inline">\(\nu\)</span> (more LLs on diseased cases, as more lesions are localized, causing the distribution of <span class="math inline">\(h_2\)</span> to shift to higher values).</p>
</div>
<div id="vary-zeta" class="section level4 hasAnchor">
<h4><span class="header-section-number">5.5.7.4</span> Vary <span class="math inline">\(\zeta\)</span><a href="rsm-pred.html#vary-zeta" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## lesDistr =  0.1 0.9</code></pre>
<pre><code>## Varying zeta only: 
## Other parameters are mu =  1 , lambda =  2 , nu =  0.5</code></pre>
<pre><code>## zeta = -3 , RSM-x = 0.8643 , RSM-y = 0.9627 
## zeta = -2.5 , RSM-x = 0.8630 , RSM-y = 0.9623 
## zeta = -2 , RSM-x = 0.8584 , RSM-y = 0.9610 
## zeta = -1.5 , RSM-x = 0.8453 , RSM-y = 0.9570 
## zeta = -1 , RSM-x = 0.8141 , RSM-y = 0.9467 
## zeta = -0.5 , RSM-x = 0.7492 , RSM-y = 0.9224 
## zeta = 0 , RSM-x = 0.6321 , RSM-y = 0.8676 
## zeta = 0.5 , RSM-x = 0.4605 , RSM-y = 0.7568 
## zeta = 1 , RSM-x = 0.2719 , RSM-y = 0.5768 
## zeta = 1.5 , RSM-x = 0.1251 , RSM-y = 0.3628 
## zeta = 2 , RSM-x = 0.0445 , RSM-y = 0.1831 
## zeta = 2.5 , RSM-x = 0.0123 , RSM-y = 0.0740 
## zeta = 3 , RSM-x = 0.0027 , RSM-y = 0.0241</code></pre>
<p>Increasing <span class="math inline">\(\zeta\)</span> causes the operating point to move down the ROC.</p>
</div>
<div id="vary-f_l" class="section level4 hasAnchor">
<h4><span class="header-section-number">5.5.7.5</span> Vary <span class="math inline">\(f_L\)</span><a href="rsm-pred.html#vary-f_l" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <code>lesDist</code> vector is defined as <span class="math inline">\((f, (1-f))\)</span> where f is varied from 1 (only cases with one lesion per case) to 0 (only cases with two lesions per case):</p>
<pre><code>## lesDistr =  (f, 1-f)</code></pre>
<pre><code>## Varying f only: 
## Other parameters are mu =  1 , lambda =  2 , nu =  0.5 , zeta =  0</code></pre>
<pre><code>## f =  1 , RSM-x =  0.6321 , RSM-y =  0.7869 
## f =  0.9 , RSM-x =  0.6321 , RSM-y =  0.7958 
## f =  0.8 , RSM-x =  0.6321 , RSM-y =  0.8048 
## f =  0.7 , RSM-x =  0.6321 , RSM-y =  0.8138 
## f =  0.6 , RSM-x =  0.6321 , RSM-y =  0.8227 
## f =  0.5 , RSM-x =  0.6321 , RSM-y =  0.8317 
## f =  0.4 , RSM-x =  0.6321 , RSM-y =  0.8407 
## f =  0.3 , RSM-x =  0.6321 , RSM-y =  0.8496 
## f =  0.2 , RSM-x =  0.6321 , RSM-y =  0.8586 
## f =  0.1 , RSM-x =  0.6321 , RSM-y =  0.8676 
## f =  0 , RSM-x =  0.6321 , RSM-y =  0.8765</code></pre>
<p>No effect on FPF but TPF increases as more lesions per case means more LLs per case and the distribution of <span class="math inline">\(h_2\)</span> moves to higher values.</p>
</div>
</div>
<div id="rsm-pred-roc-curves" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.5.8</span> Sample ROC curves<a href="rsm-pred.html#rsm-pred-roc-curves" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="figure"><span style="display:block;" id="fig:rsm-pred-fig-auc-mu-plots"></span>
<img src="07-rsm-predictions_files/figure-html/rsm-pred-fig-auc-mu-plots-1.png" alt="ROC curves for indicated values of the $\mu$ parameter. Notice the transition, as $\mu$ increases, from near chance level performance to almost perfect performancea as the end-point moves from near (1,1) to near (0,1)." width="672" />
<p class="caption">
FIGURE 5.2: ROC curves for indicated values of the <span class="math inline">\(\mu\)</span> parameter. Notice the transition, as <span class="math inline">\(\mu\)</span> increases, from near chance level performance to almost perfect performancea as the end-point moves from near (1,1) to near (0,1).
</p>
</div>
<p>Fig. <a href="rsm-pred.html#fig:rsm-pred-fig-auc-mu-plots">5.2</a> displays ROC curves for indicated values of <span class="math inline">\(\mu\)</span>. The remaining RSM model parameters are <span class="math inline">\(\lambda = 1\)</span>, <span class="math inline">\(\nu = 1\)</span> and <span class="math inline">\(\zeta = -\infty\)</span> and there is one lesion per diseased case.</p>
<p>The following are evident from these figures:</p>
<ol style="list-style-type: decimal">
<li>As <span class="math inline">\(\mu\)</span> increases the ROC curve more closely approaches the upper-left corner of the ROC plot. This signifies increasing performance and the area under the ROC and AFROC curves approach unity. The end-point abscissa decreases, meaning increasing numbers of unmarked non-diseased cases, i.e., more perfect decisions on non-diseased cases. The end-point ordinate increases, meaning decreasing numbers of unmarked lesions, i.e., more good decisions on diseased cases.</li>
<li>For <span class="math inline">\(\mu\)</span> close to zero the operating characteristic approaches the chance diagonal and the area under the ROC curve approaches 0.5.</li>
<li>The area under the ROC increases monotonically from 0.5 to 1 as <span class="math inline">\(\mu\)</span> increases from zero to infinity.</li>
<li>For large <span class="math inline">\(\mu\)</span> the accessible portion of the operating characteristic approaches the vertical line connecting (0,0) to (0,1), the area under which is zero. The complete ROC curve is obtained by connecting this point to (1,1) by the dashed line and in this limit the area under the complete ROC curve approaches unity. Omitting the area under the dashed portion of the curve will result in a severe underestimate of true performance.</li>
<li>As <span class="math inline">\(L_{max}\)</span> increases (allowed values are 1, 2, 3, etc.) the area under the ROC curve increases, approaching unity and <span class="math inline">\(\text{TPF}_{\text{max}}\)</span> approaches unity. With more lesions per diseased case, the chances are higher that at least one of them will be found and marked. However, <span class="math inline">\(\text{FPF}_{\text{max}}\)</span> remains constant as determined by the constant value of <span class="math inline">\(\lambda = \frac{\lambda}{\mu}\)</span>, Eqn. <a href="rsm-pred.html#eq:rsm-pred-fpf-max">(5.3)</a></li>
<li>As <span class="math inline">\(\lambda\)</span> decreases <span class="math inline">\(\text{FPF}_{\text{max}}\)</span> decreases to zero and <span class="math inline">\(\text{TPF}_{\text{max}}\)</span> decreases. The decrease in <span class="math inline">\(\text{TPF}_{\text{max}}\)</span> is consistent with the fact that, with fewer NLs, there is less chance of a NL being rated higher than a LL, and one is completely dependent on at least one lesion being found.</li>
<li>As <span class="math inline">\(\nu\)</span> increases <span class="math inline">\(\text{FPF}_{\text{max}}\)</span> stays constant at the value determined by <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(\mu\)</span>, while <span class="math inline">\(\text{TPF}_{\text{max}}\)</span> approaches unity. The corresponding physical parameter <span class="math inline">\(\nu\)</span> increases approaching unity, guaranteeing every lesion will be found.</li>
</ol>
</div>
<div id="rsm-pred-pdf-curves" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.5.9</span> Sample RSM pdf curves<a href="rsm-pred.html#rsm-pred-pdf-curves" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="figure"><span style="display:block;" id="fig:rsm-pred-fig-pdf-mu-plots"></span>
<img src="07-rsm-predictions_files/figure-html/rsm-pred-fig-pdf-mu-plots-1.png" alt="RSM pdf curves for indicated values of the $\mu$ parameter. The solid curve corresponds to diseased cases and the dotted curve corresponds to non-diseased cases." width="672" />
<p class="caption">
FIGURE 5.3: RSM pdf curves for indicated values of the <span class="math inline">\(\mu\)</span> parameter. The solid curve corresponds to diseased cases and the dotted curve corresponds to non-diseased cases.
</p>
</div>
<p>Fig. <a href="rsm-pred.html#fig:rsm-pred-fig-pdf-mu-plots">5.3</a> shows pdf plots for the same values of parameters as in Fig. <a href="rsm-pred.html#fig:rsm-pred-fig-auc-mu-plots">5.2</a>.</p>
<p>Consider the plot of the pdfs for <span class="math inline">\(\mu = 1\)</span>. Since the integral of a pdf function over an interval amounts to counting the fraction of events occurring in the interval, it should be evident that the area under the non-diseased pdf equals <span class="math inline">\(\text{FPF}_{\text{max}}\)</span> and that under the diseased pdf equals <span class="math inline">\(\text{TPF}_{\text{max}}\)</span>. For the chosen value <span class="math inline">\(\lambda = 1\)</span> one has <span class="math inline">\(\text{FPF}_{\text{max}} = 1 - e^{-\lambda} = 0.632\)</span>. The area under the non-diseased pdf is less than unity because it is missing the contribution of non-diseased cases with no marks, the probability of which is <span class="math inline">\(e^{-\lambda} = e^{-1} = 0.368\)</span>. Equivalently, it is missing the area under the dashed straight line segment of the ROC curve. Likewise, the area under the diseased pdf equals <span class="math inline">\(\text{TPF}_{\text{max}}\)</span>, Eqn. <a href="rsm-pred.html#eq:rsm-pred-tpf-max">(5.4)</a>, which is also less than unity. For the chosen values of <span class="math inline">\(\mu = \lambda = \nu = L = 1\)</span> it equals <span class="math inline">\(\text{TPF}_{\text{max}} = 1 - e^{-\lambda} e^{-\nu} = 0.865\)</span>. This area is somewhat larger than that under the non-diseased pdf, as is evident from visual examination of the plot. A greater fraction of diseased cases generate marks than do non-diseased cases, consistent with the presence of lesions in diseased cases. The complement of 0.865 is due to diseased cases with no marks, which account for a fraction 0.135 of diseased cases. To summarize, the pdf’s do not integrate to unity for the reason that the integrals account only for the continuous section of the ROC curve and do not include cases with zero latent marks that do not generate z-samples. The effect becomes more exaggerated for higher values of <span class="math inline">\(\mu\)</span> as this causes <span class="math inline">\(\text{FPF}_{\text{max}}\)</span> to further decrease.</p>
<p>The plot in Fig. <a href="rsm-pred.html#fig:rsm-pred-fig-pdf-mu-plots">5.3</a> labeled <span class="math inline">\(\mu = 0.05\)</span> may be surprising. Since it corresponds to a small value of <span class="math inline">\(\mu\)</span>, one may expect both pdfs to overlap and be centered at zero. Instead, while they do overlap, the shape is distinctly non-Gaussian and centered at approximately 1.8. This is because the small value of <span class="math inline">\(\mu\)</span> results in a large value of the <span class="math inline">\(\lambda\)</span> parameter, since <span class="math inline">\(\lambda = \lambda / \mu = 20\)</span>. The highest of a large number of samples from the unit normal distribution is not normal and is peaked at a value above zero <span class="citation">(Fisher and Tippett <a href="#ref-fisher1928limiting" role="doc-biblioref">1928</a>)</span>.</p>
</div>
</div>
<div id="rsm-pred-roc-curve-proper" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.6</span> Proper ROC curve<a href="rsm-pred.html#rsm-pred-roc-curve-proper" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<blockquote>
<p>A proper ROC curve has the property that it never crosses the chance diagonal and its slope never increases as the operating point moves up the ROC curve <span class="citation">(Metz and Pan <a href="#ref-metz1999proper" role="doc-biblioref">1999</a>; Macmillan and Creelman <a href="#ref-macmillan2004detection" role="doc-biblioref">2004</a>)</span>. <em>It is shown below that the RSM predicted ROC curve, including the dashed straight line extension, is proper</em>.<a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a></p>
</blockquote>
<p>Consider first the continuous section which is below-left of the end-point. For convenience one abbreviates FPF and TPF to <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, respectively, and suppresses the dependence on model parameters. From Eqn. <a href="rsm-pred.html#eq:rsm-pred-fpf">(5.11)</a> and Eqn. <a href="rsm-pred.html#eq:rsm-pred-tpf2">(5.15)</a> one can express the ROC coordinates as:</p>
<p><span class="math display" id="eq:rsm-pred-f-g">\[\begin{equation}
\left. 
\begin{aligned}
x\left ( \zeta \right ) =&amp; 1 - G\left ( \zeta \right )\\
y\left ( \zeta \right ) =&amp; 1 - F\left ( \zeta \right ) G\left ( \zeta \right ) 
\end{aligned}
\right \}
\tag{5.21}
\end{equation}\]</span></p>
<p>where:</p>
<p><span class="math display" id="eq:rsm-pred-fg-defs">\[\begin{equation}
\left. 
\begin{aligned}
G\left ( \zeta \right ) =&amp; \text{exp}\left ( -\lambda \Phi \left ( -\zeta \right )\right )\\
F\left ( \zeta \right ) =&amp; \sum_{L=1}^{L_{max}} f_L  \left ( 1 - \nu \Phi \left ( \mu -\zeta \right ) \right )^L 
\end{aligned}
\right \}
\tag{5.22}
\end{equation}\]</span></p>
<blockquote>
<p>These equations have the same structure as <span class="citation">(Swensson <a href="#ref-swensson1996unified" role="doc-biblioref">1996</a>)</span> Eqns. 1 and 2 and the logic used there to demonstrate that ROC curves predicted by Swensson’s LROC model is proper also applies to the present situation.</p>
</blockquote>
<p>Specifically, since the <span class="math inline">\(\Phi\)</span> function ranges between 0 and 1 and <span class="math inline">\(0 \leq \nu \leq 1\)</span>, it follows that <span class="math inline">\(F\left ( \zeta \right ) \leq 1\)</span>. Therefore <span class="math inline">\(y\left ( \zeta \right ) \geq x\left ( \zeta \right )\)</span> and the ROC curve is constrained to the upper half of the ROC space, namely the portion above the chance diagonal. Additionally, the more general constraint shown by Swensson applies, namely the slope of the ROC curve at any operating point (x, y) cannot be less than the slope of the dashed straight line connecting (x, y) and <span class="math inline">\(\left (\text{FPF}_{\text{max}}, \text{TPF}_{\text{max}} \right )\)</span>, the coordinates of the RSM end-point. This implies that the slope decreases monotonically and also rules out curves with “hooks”.</p>
<blockquote>
<p>In Appendix 1 <a href="rsm-pred.html#rsm-pred-appendix1">5.9</a> it is shown analytically that the slope is continuous at the end-point transition from the continuous curve to the dashed straight line. In Appendix 2 <a href="rsm-pred.html#rsm-pred-appendix2">5.10</a> the slope near the end-point is examined numerically to resolve an apparent paradox, namely the ROC plot can appear discontinuous at the end-point when in fact no discontinuity exists.</p>
</blockquote>
</div>
<div id="rsm-pred-roc-curve-aucs-zeta1" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.7</span> <span class="math inline">\(\zeta\)</span> dependence of ROC AUC<a href="rsm-pred.html#rsm-pred-roc-curve-aucs-zeta1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When it comes to predicted ROC AUC there is an important difference between conventional ROC models and the RSM. The former has no dependence on <span class="math inline">\(\zeta\)</span>. This is because in the ROC model every case yields a rating, no matter how low the z-sample, implying that effectively <span class="math inline">\(\zeta = -\infty\)</span>. The lack of <span class="math inline">\(\zeta\)</span> dependence is demonstrated by the help page for function <code>UtilAucBormal</code>, shown below, which depends on only two parameters, <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> (the two-parameter dependence is also true for other ROC models implemented in <code>RJafroc</code>, e.g., <code>UtilAucCBM</code> and <code>UtilAucPROPROC</code>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rsm-pred-binorml-help"></span>
<img src="images/rsm-pred/util-aucs-binormal.png" alt="Help page for `RJafroc` function `UtilAucBormal`." width="300pt" />
<p class="caption">
FIGURE 5.4: Help page for <code>RJafroc</code> function <code>UtilAucBormal</code>.
</p>
</div>
<p>In contrast, in addition to the basic RSM parameters, i.e., <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(\nu\)</span>, the rsm-pred have an additional dependence on <span class="math inline">\(\zeta\)</span>. This is because the value of <span class="math inline">\(\zeta\)</span> determines the location of the end-point. The <span class="math inline">\(\zeta\)</span> dependence is demonstrated next for the ROC plots, but it is true for all RSM predictions.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rsm-pred-operating-characteristics-help"></span>
<img src="images/rsm-pred/PlotRsmOperatingCharacteristics.png" alt="Help page for `RJafroc` function `PlotRsmOperatingCharacteristics`." width="300pt" />
<p class="caption">
FIGURE 5.5: Help page for <code>RJafroc</code> function <code>PlotRsmOperatingCharacteristics</code>.
</p>
</div>
<p>The dependence is demonstrated next for two values: <span class="math inline">\(zeta = -10\)</span> and <span class="math inline">\(zeta = 1\)</span>. The common parameter values are <span class="math inline">\(\mu = 2\)</span>, <span class="math inline">\(\lambda = 1\)</span>, <span class="math inline">\(\nu = 1\)</span>, as shown in the following code-chunk.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="rsm-pred.html#cb82-1"></a>roc &lt;-<span class="st"> </span><span class="kw">PlotRsmOperatingCharacteristics</span>(</span>
<span id="cb82-2"><a href="rsm-pred.html#cb82-2"></a>     <span class="dt">mu =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>),</span>
<span id="cb82-3"><a href="rsm-pred.html#cb82-3"></a>     <span class="dt">lambda =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb82-4"><a href="rsm-pred.html#cb82-4"></a>     <span class="dt">nu =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb82-5"><a href="rsm-pred.html#cb82-5"></a>     <span class="dt">zeta1 =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">10</span>, <span class="dv">1</span>),</span>
<span id="cb82-6"><a href="rsm-pred.html#cb82-6"></a>     <span class="dt">lesDistr =</span> <span class="kw">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>),</span>
<span id="cb82-7"><a href="rsm-pred.html#cb82-7"></a>     <span class="dt">relWeights =</span> <span class="kw">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>),</span>
<span id="cb82-8"><a href="rsm-pred.html#cb82-8"></a>     <span class="dt">OpChType =</span> <span class="st">&quot;ROC&quot;</span>,</span>
<span id="cb82-9"><a href="rsm-pred.html#cb82-9"></a>     <span class="dt">legendPosition =</span> <span class="st">&quot;null&quot;</span></span>
<span id="cb82-10"><a href="rsm-pred.html#cb82-10"></a>)</span></code></pre></div>
<p>Clearly the red curve has higher AUC. The specific values are 0.9591597 for the red curve and 0.9337196 for the green curve.</p>
<div class="figure"><span style="display:block;" id="fig:rsm-pred-roc-zeta1"></span>
<img src="07-rsm-predictions_files/figure-html/rsm-pred-roc-zeta1-1.png" alt="ROC curves for two values of $\zeta$: both curves correspond to $\mu = 2$, $\nu = 1$ and $\lambda = 1$. The red curve corresponds to $\zeta = -10$ and the blue curve to $\zeta = 1$." width="672" />
<p class="caption">
FIGURE 5.6: ROC curves for two values of <span class="math inline">\(\zeta\)</span>: both curves correspond to <span class="math inline">\(\mu = 2\)</span>, <span class="math inline">\(\nu = 1\)</span> and <span class="math inline">\(\lambda = 1\)</span>. The red curve corresponds to <span class="math inline">\(\zeta = -10\)</span> and the blue curve to <span class="math inline">\(\zeta = 1\)</span>.
</p>
</div>
<p>A consequence of the <span class="math inline">\(\zeta\)</span> dependence is that if one uses ROC AUC as the measure of performance, the optimal threshold is <span class="math inline">\(\zeta = -\infty\)</span>. In particular, a CAD algorithm that generates FROC data should show all generated marks to the radiologist, which is clearly incorrect and is not adopted by any CAD designer. Selecting the optimal value of the reporting threshold is addressed in Chapter <a href="optim-op-point.html#optim-op-point">11</a>.</p>
</div>
<div id="rsm-pred-discussion-summary" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.8</span> TBA Discussion / Summary<a href="rsm-pred.html#rsm-pred-discussion-summary" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This chapter has detailed ROC, FROC and AFROC curves predicted by the radiological search model (RSM). All RSM curves share the constrained end-point property that is qualitatively different from previous ROC models. In my experience, it is a property that most researchers in this field have difficulty accepting. There is too much history going back to the early 1940s, of the ROC curve extending from (0,0) to (1,1) that one has to let go of, and this can be difficult.</p>
<p>I am not aware of any direct evidence that radiologists can move the operating point continuously in the range (0,0) to (1,1) in search tasks, so the existence of such an ROC is tantamount to an assumption. Algorithmic observers that do not involve the element of search can extend continuously to (1,1). An example of an algorithmic observer not involving search is a diagnostic test that rates the results of a laboratory measurement, e.g., the A1C measure of blood glucose for presence of a disease. If A1C ≥ 6.5% the patient is diagnosed as diabetic. By moving the threshold from infinity to –infinity, and assuming a large population of patients, one can trace out the entire ROC curve from the origin to (1,1). This is because every patient yields an A1C value. Now imagine that some finite fraction of the test results are “lost in the mail”; then the ROC curve, calculated over all patients, would have the constrained end-point property, albeit due to an unreasonable cause.</p>
<p>The situation in medical imaging involving search tasks is qualitatively different. Not every case yields a decision variable. There is a reasonable cause for this – to render a decision variable sample the radiologist must find something suspicious to report, and if none is found, there is no decision variable to report. The ROC curve calculated over all patients would exhibit the constrained end-point property, even in the limit of an infinite number of patients. If calculated over only those patients that yielded at least one mark, the ROC curve would extend from (0,0) to (1,1) but then one would be ignoring the cases with no marks, which represent valuable information: unmarked non-diseased cases represent perfect decisions and unmarked diseased cases represent worst-case decisions.</p>
<p>ROC, FROC and AFROC curves were derived (wAFROC is implemented in the Rjafroc). These were used to demonstrate that the FROC is a poor descriptor of performance. Since almost all work to date, including some by me TBA 47,48, has used FROC curves to measure performance, this is going to be difficulty for some to accept. The examples in Fig. 17.6 (A- F) and Fig. 17.7 (A-B) should convince one that the FROC curve is indeed a poor measure of performance. The only situation where one can safely use the FROC curve is if the two modalities produce curves extending over the same NLF range. This can happen with two variants of a CAD algorithm, but rarely with radiologist observers.</p>
<p>A unique feature is that the RSM provides measures of search and lesion-classification performance. It bears repeating that search performance is the ability to find lesions while avoiding finding non-lesions. Search performance can be determined from the position of the ROC end-point (which in turn is determined by RSM-based fitting of ROC data, Chapter 19). The perpendicular distance between the end-point and the chance diagonal is, apart from a factor of 1.414, a measure of search performance. All ROC models that predict continuous curves extending to (1,1), imply zero search performance.</p>
<p>Lesion-classification performance is measured by the AUC value corresponding to the parameter. Lesion-classification performance is the ability to discriminate between LLs and NLs, not between diseased and non-diseased cases: the latter is measured by RSM-AUC. There is a close analogy between the two ways of measuring lesion-classification performance and CAD used to find lesions in screening mammography vs. CAD used in the diagnostic context to determine if a lesion found at screening is actually malignant. The former is termed CADe, for CAD detection, which in my opinion, is slightly misleading as at screening lesions are found not detected (“detection” is “discover or identify the presence or existence of something”, correct localization is not necessarily implied; the more precise term is “localize”). In the diagnostic context one has CADx, for CAD diagnostic, i.e., given a specific region of the image, is the region malignant?</p>
<p>Search and lesion-classification performance can be used as “diagnostic aids” to optimize performance of a reader. For example, is search performance is low, then training using mainly non-diseased cases is called for, so the resident learns the different variants of non-diseased tissues that can appear to be true lesions. If lesion-classification performance is low then training with diseased cases only is called for, so the resident learns the distinguishing features characterizing true lesions from non-diseased tissues that fake true lesions.</p>
<p>Finally, evidence for the RSM is summarized. Its correspondence to the empirical Kundel-Nodine model of visual search that is grounded in eye-tracking measurements. It reduces in the limit of large , which guarantees that every case will yield a decision variable sample, to the binormal model; the predicted pdfs in this limit are not strictly normal, but deviations from normality would require very large sample size to demonstrate. Examples were given where even with 1200 cases the binormal model provides statistically good fits, as judged by the chi-square goodness of fit statistic, Table 17.2. Since the binormal model has proven quite successful in describing a large body of data, it satisfying that the RSM can mimic it in the limit of large . The RSM explains most empirical results regarding binormal model fits: the common finding that b &lt; 1; that b decreases with increasing lesion pSNR (large and / or ); and the finding that the difference in means divided by the difference in standard deviations is fairly constant for a fixed experimental situation, Table 17.3. The RSM explains data degeneracy, especially for radiologists with high expertise.</p>
<p>The contaminated binormal model2-4 (CBM), Chapter 20, which models the diseased distribution as having two peaks, one at zero and the other at a constrained value, also explains the empirical observation that b-parameter &lt; 1 and data degeneracy. Because it allows the ROC curve to go continuously to (1,1), CBM does not completely account for search performance – it accounts for search when it comes to finding lesions, but not for avoiding finding non-lesions.</p>
<p>I do not want to leave the impression that RSM is the ultimate model. The current model does not predict satisfaction of search (SOS) effects27-29. Attempts to incorporate SOS effects in the RSM are in the early research stage. As stated earlier, the RSM is a first-order model: a lot of interesting science remains to be uncovered.</p>
</div>
<div id="rsm-pred-appendix1" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.9</span> Appendix 1: Proof of continuity of slope at the end-point<a href="rsm-pred.html#rsm-pred-appendix1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The following proof is adapted from a document supplied by Dr. Xuetong Zhai, then ( ca. 2017) a graduate student working under the supervision of the author.</p>
<p>The end point coordinates of the continuous part of ROC curve was derived above, Eqn. <a href="rsm-pred.html#eq:rsm-pred-fpf-max">(5.3)</a> for <span class="math inline">\(\text{FPF}_{\text{max}}\)</span> and Eqn. <a href="rsm-pred.html#eq:rsm-pred-tpf-max-vary-l">(5.6)</a> for <span class="math inline">\(\text{TPF}_{\text{max}}\)</span>. Therefore, the slope <span class="math inline">\(m_{st}\)</span> of the dashed straight line is:</p>
<p><span class="math display" id="eq:rsm-slope-st-line">\[\begin{equation}
\left. 
\begin{aligned}
m_{st} =&amp; \frac{1-\text{TPF}_{\text{max}}}{1-\text{FPF}_{\text{max}}}\\
=&amp;\frac{\sum_{L=1}^{L_{max}} f_L \left ( 1 - \nu \right )^L
 \text{exp} \left ( - \lambda \right )} {\text{exp} \left ( - \lambda \right )} \\
=&amp; \sum_{L=1}^{L_{max}} f_L \left ( 1 - \nu \right )^L  \\
\end{aligned}
\right \}
\tag{5.23}
\end{equation}\]</span></p>
<p>On the continuous section, <span class="math inline">\(g\equiv\text{FPF}\)</span> and <span class="math inline">\(h\equiv\text{TPF}\)</span> are defined by <a href="rsm-pred.html#eq:rsm-pred-fpf">(5.11)</a> and <a href="rsm-pred.html#eq:rsm-pred-tpf2">(5.15)</a>, respectively. Therefore,</p>
<p><span class="math display" id="eq:rsm-pred-slope-eq3">\[\begin{equation}
\left. 
\begin{aligned}
g =&amp; 1-\text{exp} \left ( -\lambda \Phi\left ( -\zeta \right ) \right ) \\
h =&amp; 1-\text{exp} \left ( -\lambda \Phi\left ( -\zeta \right ) \right ) \sum_{L=1}^{L_{max}}f_L \left ( 1-\nu\Phi\left ( \mu - \zeta \right ) \right )^{L}
\end{aligned}
\right \}
\tag{5.24}
\end{equation}\]</span></p>
<p>Taking the differentials of these functions with respect to <span class="math inline">\(\zeta\)</span> it follows that the slope of the ROC is given by:</p>
<p><span class="math display" id="eq:rsm-pred-slope-eq4">\[\begin{equation}
\left. 
\begin{aligned}
\frac{dh}{dg} =&amp; \sum_{L=1}^{L_{max}}  f_L \left ( 1-\nu\Phi\left ( \mu-\zeta \right ) \right )^{L-1}  \times \\
&amp; \left [ \frac{L\nu\phi\left ( \mu-\zeta \right )}{\lambda\phi\left ( -\zeta \right )} + \left ( 1-\nu\Phi \left ( \mu-\zeta \right )\right ) \right ]\\ 
\end{aligned}
\right \} 
\tag{5.25}
\end{equation}\]</span></p>
<p>Using the following result:</p>
<p><span class="math display" id="eq:rsm-pred-slope-eq5">\[\begin{equation}
\left. 
\begin{aligned}
&amp; \lim_{\zeta \rightarrow -\infty} \frac{\phi \left ( \mu-\zeta \right )}{\phi\left ( -\zeta \right )} \\ 
=&amp;\lim_{\zeta \rightarrow -\infty} \frac{\text{exp}\left ( \frac{-\left (\mu-\zeta  \right )^2}{2} \right )}{\text{exp}\left ( \frac{-\zeta^2}{2} \right )} \\
=&amp; \lim_{\zeta \rightarrow -\infty} \text{exp}\left (-\frac{1}{2} \left( \mu^2 - 2\mu\zeta \right)  \right ) \\
=&amp; 0
\end{aligned}
\right \} 
\tag{5.26}
\end{equation}\]</span></p>
<p>it follows that:</p>
<p><span class="math display" id="eq:rsm-pred-slope-eq6">\[\begin{equation}
\left. 
\begin{aligned}
&amp; \lim_{\zeta \rightarrow -\infty} \frac{dh}{dg} \\ 
=&amp; \sum_{L=1}^{L_{max}} f_L \left ( 1-\nu \right )^{L-1} \left ( 1-\nu \right )\\
=&amp; \sum_{L=1}^{L_{max}} f_L \left ( 1-\nu \right )^{L} \\
=&amp; m_{st}
\end{aligned}
\right \} 
\tag{5.27}
\end{equation}\]</span></p>
<p>This proves that the limiting slope of the continuous section of the ROC curve equals that of the dashed straight line connecting the end-point to (1,1).</p>
</div>
<div id="rsm-pred-appendix2" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.10</span> Appendix 2: Numerical illustration of continuity<a href="rsm-pred.html#rsm-pred-appendix2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The code in this section examines the slope of the ROC curve as one approaches the end-point <span class="math inline">\(\zeta = -\infty\)</span>. The RSM parameter values are <span class="math inline">\(\mu = 0.5\)</span>, <span class="math inline">\(\lambda = 0.1\)</span> and <span class="math inline">\(\nu = 0.8\)</span>, and twenty percent of the diseased cases have one lesion and 80 percent have 2 lesions, i.e. <code>lesDistr</code> -&gt; c(0.2, 0.8).</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="rsm-pred.html#cb83-1"></a>mu &lt;-<span class="st"> </span><span class="fl">0.5</span></span>
<span id="cb83-2"><a href="rsm-pred.html#cb83-2"></a>lambda &lt;-<span class="st"> </span><span class="fl">0.2</span></span>
<span id="cb83-3"><a href="rsm-pred.html#cb83-3"></a>nu &lt;-<span class="st"> </span><span class="fl">0.8</span></span>
<span id="cb83-4"><a href="rsm-pred.html#cb83-4"></a>lesDistr &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.2</span>, <span class="fl">0.8</span>)</span></code></pre></div>
<p>One calculates the coordinates of the end-point and the slope of the line connecting it to (1,1).</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="rsm-pred.html#cb84-1"></a>maxFPF &lt;-<span class="st"> </span><span class="kw">FPF</span> (<span class="op">-</span><span class="ot">Inf</span>, lambda)</span>
<span id="cb84-2"><a href="rsm-pred.html#cb84-2"></a>maxTPF &lt;-<span class="st"> </span><span class="kw">TPF</span> (<span class="op">-</span><span class="ot">Inf</span>, mu, lambda, nu, lesDistr)</span>
<span id="cb84-3"><a href="rsm-pred.html#cb84-3"></a>mStLine &lt;-<span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>maxTPF) <span class="op">/</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>maxFPF)</span></code></pre></div>
<p>The end-point coordinates are (0.1812692, 0.9410514) and the slope is 0.072. Next one calculates and displays the ROC curve.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="rsm-pred.html#cb85-1"></a>ret &lt;-<span class="st"> </span><span class="kw">PlotRsmOperatingCharacteristics</span>(</span>
<span id="cb85-2"><a href="rsm-pred.html#cb85-2"></a>  mu,</span>
<span id="cb85-3"><a href="rsm-pred.html#cb85-3"></a>  lambda,</span>
<span id="cb85-4"><a href="rsm-pred.html#cb85-4"></a>  nu,</span>
<span id="cb85-5"><a href="rsm-pred.html#cb85-5"></a>  <span class="dt">zeta1 =</span> <span class="op">-</span><span class="ot">Inf</span>, </span>
<span id="cb85-6"><a href="rsm-pred.html#cb85-6"></a>  <span class="dt">OpChType =</span> <span class="st">&quot;ROC&quot;</span>,</span>
<span id="cb85-7"><a href="rsm-pred.html#cb85-7"></a>  <span class="dt">lesDistr =</span> lesDistr,</span>
<span id="cb85-8"><a href="rsm-pred.html#cb85-8"></a>  <span class="dt">legendPosition =</span> <span class="st">&quot;none&quot;</span></span>
<span id="cb85-9"><a href="rsm-pred.html#cb85-9"></a>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:rsm-pred-roc-plot"></span>
<img src="07-rsm-predictions_files/figure-html/rsm-pred-roc-plot-1.png" alt="ROC curve for selected RSM parameters. The slope of the dashed line is 0.4935272. " width="672" />
<p class="caption">
FIGURE 5.7: ROC curve for selected RSM parameters. The slope of the dashed line is 0.4935272.
</p>
</div>
<p>At first sight the slope appeared to me to be discontinuous at the end-point<a href="#fn27" class="footnote-ref" id="fnref27"><sup>27</sup></a> but this is not true. In fact the slope decreases as one approaches the end-point, and in the limit equals that of the dashed line. This is demonstrated by the next code section which creates a finely-spaced <span class="math inline">\(\zeta\)</span> array ranging from -3 to -20. These are the points at which the slope is evaluated numerically. Two types of calculations were performed - one using standard <code>R</code> double precision arithmetic and one using multiple precision arithmetic. The R-package <code>Rmpfr</code> was used for the latter. For example, the line <code>zeta_mpr -&gt; mpfr(zeta, 2000)</code> generates a 2000-bit representation of <span class="math inline">\(\zeta\)</span>. All subsequent computations using <code>zeta_mpr</code> uses multiple precision arithmetic. The computed slopes are saved in two arrays, <code>y1</code>, the standard precision arithmetic slope and <code>y2</code>, the multiple precision arithmetic slope.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="rsm-pred.html#cb86-1"></a>zeta_arr &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">seq</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">-5</span>, <span class="fl">-0.2</span>), <span class="kw">seq</span>(<span class="op">-</span><span class="dv">5</span>, <span class="dv">-20</span>, <span class="fl">-0.5</span>))</span>
<span id="cb86-2"><a href="rsm-pred.html#cb86-2"></a>y1 &lt;-<span class="st"> </span><span class="kw">array</span>(<span class="dv">0</span>, <span class="kw">length</span>(zeta_arr))</span>
<span id="cb86-3"><a href="rsm-pred.html#cb86-3"></a>y2 &lt;-<span class="st"> </span><span class="kw">array</span>(<span class="dv">0</span>, <span class="kw">length</span>(zeta_arr))</span>
<span id="cb86-4"><a href="rsm-pred.html#cb86-4"></a>i &lt;-<span class="st"> </span><span class="dv">0</span></span>
<span id="cb86-5"><a href="rsm-pred.html#cb86-5"></a><span class="cf">for</span> (zeta <span class="cf">in</span> zeta_arr) {</span>
<span id="cb86-6"><a href="rsm-pred.html#cb86-6"></a>  i &lt;-<span class="st"> </span>i <span class="op">+</span><span class="st"> </span><span class="dv">1</span></span>
<span id="cb86-7"><a href="rsm-pred.html#cb86-7"></a>  <span class="co"># normal precision arithmetic</span></span>
<span id="cb86-8"><a href="rsm-pred.html#cb86-8"></a>  zeta2 &lt;-<span class="st"> </span>zeta <span class="op">+</span><span class="st"> </span><span class="fl">1e-6</span></span>
<span id="cb86-9"><a href="rsm-pred.html#cb86-9"></a>  delta_FPF &lt;-<span class="st"> </span><span class="kw">FPF</span> (zeta, lambda) <span class="op">-</span><span class="st"> </span><span class="kw">FPF</span> (zeta2, lambda)</span>
<span id="cb86-10"><a href="rsm-pred.html#cb86-10"></a>  delta_TPF &lt;-<span class="st"> </span><span class="kw">TPF</span> (zeta, mu, lambda, nu, lesDistr) <span class="op">-</span><span class="st"> </span></span>
<span id="cb86-11"><a href="rsm-pred.html#cb86-11"></a><span class="st">    </span><span class="kw">TPF</span> (zeta2, mu, lambda, nu, lesDistr)</span>
<span id="cb86-12"><a href="rsm-pred.html#cb86-12"></a>  mAnal &lt;-<span class="st"> </span>delta_TPF <span class="op">/</span><span class="st"> </span>delta_FPF</span>
<span id="cb86-13"><a href="rsm-pred.html#cb86-13"></a>  y1[i] &lt;-<span class="st"> </span>mAnal</span>
<span id="cb86-14"><a href="rsm-pred.html#cb86-14"></a>  <span class="co"># end normal precision arithmetic</span></span>
<span id="cb86-15"><a href="rsm-pred.html#cb86-15"></a>  </span>
<span id="cb86-16"><a href="rsm-pred.html#cb86-16"></a>  <span class="co"># multiple precision arithmetic</span></span>
<span id="cb86-17"><a href="rsm-pred.html#cb86-17"></a>  zeta_mpr &lt;-<span class="st"> </span><span class="kw">mpfr</span>(zeta, <span class="dv">2000</span>) <span class="co"># 2000 digit precision</span></span>
<span id="cb86-18"><a href="rsm-pred.html#cb86-18"></a>  zeta2_mpr &lt;-<span class="st"> </span>zeta_mpr <span class="op">+</span><span class="st"> </span><span class="fl">1e-12</span> <span class="co"># small increment</span></span>
<span id="cb86-19"><a href="rsm-pred.html#cb86-19"></a>  delta_FPF &lt;-<span class="st"> </span><span class="kw">FPF</span> (zeta_mpr, lambda) <span class="op">-</span><span class="st"> </span><span class="kw">FPF</span> (zeta2_mpr, lambda)</span>
<span id="cb86-20"><a href="rsm-pred.html#cb86-20"></a>  delta_TPF &lt;-<span class="st"> </span><span class="kw">TPF</span> (zeta_mpr, mu, lambda, nu, lesDistr) <span class="op">-</span><span class="st"> </span></span>
<span id="cb86-21"><a href="rsm-pred.html#cb86-21"></a><span class="st">    </span><span class="kw">TPF</span> (zeta2_mpr, mu, lambda, nu, lesDistr)</span>
<span id="cb86-22"><a href="rsm-pred.html#cb86-22"></a>  mAnalRmpfr &lt;-<span class="st"> </span>delta_TPF <span class="op">/</span><span class="st"> </span>delta_FPF</span>
<span id="cb86-23"><a href="rsm-pred.html#cb86-23"></a>  temp &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(mAnalRmpfr)</span>
<span id="cb86-24"><a href="rsm-pred.html#cb86-24"></a>  <span class="cf">if</span> (<span class="kw">is.nan</span>(temp)){</span>
<span id="cb86-25"><a href="rsm-pred.html#cb86-25"></a>    y2[i] &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb86-26"><a href="rsm-pred.html#cb86-26"></a>  } <span class="cf">else</span> y2[i] &lt;-<span class="st"> </span>temp </span>
<span id="cb86-27"><a href="rsm-pred.html#cb86-27"></a>  <span class="co"># end multiple precision arithmetic</span></span>
<span id="cb86-28"><a href="rsm-pred.html#cb86-28"></a>}</span></code></pre></div>
<p>The next code section displays 3 plots.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="rsm-pred.html#cb87-1"></a>m1 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">z =</span> zeta_arr, <span class="dt">m =</span> y1)</span>
<span id="cb87-2"><a href="rsm-pred.html#cb87-2"></a>m2 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">z =</span> zeta_arr, <span class="dt">m =</span> y2)</span>
<span id="cb87-3"><a href="rsm-pred.html#cb87-3"></a>plots &lt;-<span class="st"> </span><span class="kw">ggplot</span>(</span>
<span id="cb87-4"><a href="rsm-pred.html#cb87-4"></a>  <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> z, <span class="dt">y =</span> m)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb87-5"><a href="rsm-pred.html#cb87-5"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data =</span> m1, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb87-6"><a href="rsm-pred.html#cb87-6"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data =</span> m2) <span class="op">+</span></span>
<span id="cb87-7"><a href="rsm-pred.html#cb87-7"></a><span class="st">  </span><span class="kw">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">xlim</span>(<span class="op">-</span><span class="dv">15</span>, <span class="dv">-3</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb87-8"><a href="rsm-pred.html#cb87-8"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> mStLine, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>,<span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb87-9"><a href="rsm-pred.html#cb87-9"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="dt">label =</span> <span class="st">&quot;zeta&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="dt">label =</span> <span class="st">&quot;slopes&quot;</span>)</span>
<span id="cb87-10"><a href="rsm-pred.html#cb87-10"></a><span class="kw">suppressWarnings</span>(<span class="kw">print</span>(plots))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:rsm-pred-plots1"></span>
<img src="07-rsm-predictions_files/figure-html/rsm-pred-plots1-1.png" alt="Horizontal dashed red line: the value of `mStLine`, the slope of the straight line connecting the ROC end-point to (1,1). Dashed blue line: slope using double precision arithmetic. Solid black line: slope using multiple precision arithmetic - this curve approaches the limiting value `mStLine`." width="672" />
<p class="caption">
FIGURE 5.8: Horizontal dashed red line: the value of <code>mStLine</code>, the slope of the straight line connecting the ROC end-point to (1,1). Dashed blue line: slope using double precision arithmetic. Solid black line: slope using multiple precision arithmetic - this curve approaches the limiting value <code>mStLine</code>.
</p>
</div>
<p>The solid black line is the plot, using multiple precision arithmetic, of slope of the ROC curve vs. <span class="math inline">\(\zeta\)</span>. The dashed blue line is the slope using standard precision arithmetic. The horizontal dashed red line is the slope of the straight line connecting the end-point to (1,1), i.e., 0.4935272. Standard precision arithmetic breaks down below <span class="math inline">\(\zeta \approx -6\)</span> rapidly falling to illegal values <code>Nan</code> (above <span class="math inline">\(\zeta \approx -5\)</span> there is little difference between standard and multiple precision). The multiple precision curve approaches the slope of the straight line as <span class="math inline">\(\zeta\)</span> approaches -20. This confirms numerically the continuity of the slope of the ROC at the end-point.</p>

</div>
</div>
<h3>REFERENCES<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references">
<div id="ref-chakraborty2006search">
<p>Chakraborty, Dev P. 2006. “A Search Model and Figure of Merit for Observer Data Acquired According to the Free-Response Paradigm.” <em>Physics in Medicine &amp; Biology</em> 51 (14): 3449.</p>
</div>
<div id="ref-chakraborty2006roc">
<p>Chakraborty, DP. 2006. “ROC Curves Predicted by a Model of Visual Search.” <em>Physics in Medicine &amp; Biology</em> 51 (14): 3463.</p>
</div>
<div id="ref-fisher1928limiting">
<p>Fisher, Ronald Aylmer, and Leonard Henry Caleb Tippett. 1928. “Limiting Forms of the Frequency Distribution of the Largest or Smallest Member of a Sample.” In <em>Mathematical Proceedings of the Cambridge Philosophical Society</em>, 24:180–90. Cambridge University Press.</p>
</div>
<div id="ref-macmillan2004detection">
<p>Macmillan, Neil A, and C Douglas Creelman. 2004. <em>Detection Theory: A User’s Guide</em>. Psychology press.</p>
</div>
<div id="ref-metz1999proper">
<p>Metz, Charles E, and Xiaochuan Pan. 1999. “‘Proper’ Binormal Roc Curves: Theory and Maximum-Likelihood Estimation.” <em>Journal of Mathematical Psychology</em> 43 (1): 1–33.</p>
</div>
<div id="ref-swensson1996unified">
<p>Swensson, Richard G. 1996. “Unified Measurement of Observer Performance in Detecting and Localizing Target Objects on Images.” <em>Medical Physics</em> 23 (10): 1709–25.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="25">
<li id="fn25"><p>The original RSM publications <span class="citation">(Dev P Chakraborty <a href="#ref-chakraborty2006search" role="doc-biblioref">2006</a>; DP Chakraborty <a href="#ref-chakraborty2006roc" role="doc-biblioref">2006</a>)</span> unnecessarily introduced Dirac delta functions to force the integrals to be unity. The explanation given here should clarify the issue.<a href="rsm-pred.html#fnref25" class="footnote-back">↩︎</a></p></li>
<li id="fn26"><p>The statement in the print book that the “proper” property only applies to the continuous section is incorrect.<a href="rsm-pred.html#fnref26" class="footnote-back">↩︎</a></p></li>
<li id="fn27"><p>Others have stated a different visual impression.<a href="rsm-pred.html#fnref27" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="rsm.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="rsm-pred2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["RJafrocFrocBook.pdf", "RJafrocFrocBook.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
