<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Three proper ROC fits | The RJafroc Froc Book</title>
  <meta name="description" content="Artificial intelligence and observer performance book based on RJafroc." />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Three proper ROC fits | The RJafroc Froc Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Artificial intelligence and observer performance book based on RJafroc." />
  <meta name="github-repo" content="dpc10ster/RJafrocFrocBook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Three proper ROC fits | The RJafroc Froc Book" />
  
  <meta name="twitter:description" content="Artificial intelligence and observer performance book based on RJafroc." />
  

<meta name="author" content="Dev P. Chakraborty, PhD" />


<meta name="date" content="2023-03-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="rsm-fitting.html"/>
<link rel="next" href="standalone-cad-radiologists.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">RJafroc documentation</a></li>

<li class="divider"></li>
<li class="part"><span><b>Preamble</b></span></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Please ignore preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#please-ignore-issues"><i class="fa fa-check"></i><b>1.1</b> Please ignore issues</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#please-ignore-following-sections"><i class="fa fa-check"></i><b>1.2</b> Please ignore following sections</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#tba-rationale-and-organization"><i class="fa fa-check"></i><b>1.3</b> TBA Rationale and Organization</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#tba-acknowledgements"><i class="fa fa-check"></i><b>1.4</b> TBA Acknowledgements</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#tba-nearly-finished-chapters"><i class="fa fa-check"></i><b>1.5</b> TBA Nearly finished chapters</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#the-pdf-file-of-the-book"><i class="fa fa-check"></i><b>1.6</b> The pdf file of the book</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#please-ignore-tba-how-much-finished-hmf"><i class="fa fa-check"></i><b>1.7</b> Please ignore: TBA How much finished HMF</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#please-ignore-a-note-on-the-online-distribution-mechanism-of-the-book"><i class="fa fa-check"></i><b>1.8</b> Please ignore: A note on the online distribution mechanism of the book</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#please-ignore-structure-of-the-book"><i class="fa fa-check"></i><b>1.9</b> Please ignore: Structure of the book</a></li>
<li class="chapter" data-level="1.10" data-path="index.html"><a href="index.html#please-ignore-contributing-to-this-book"><i class="fa fa-check"></i><b>1.10</b> Please ignore Contributing to this book</a></li>
<li class="chapter" data-level="1.11" data-path="index.html"><a href="index.html#please-ignore-is-this-book-relevant-to-you-and-what-are-the-alternatives"><i class="fa fa-check"></i><b>1.11</b> Please ignore: Is this book relevant to you and what are the alternatives?</a></li>
<li class="chapter" data-level="1.12" data-path="index.html"><a href="index.html#please-ignore-chapters-needing-heavy-edits"><i class="fa fa-check"></i><b>1.12</b> Please ignore: Chapters needing heavy edits</a></li>
<li class="chapter" data-level="1.13" data-path="index.html"><a href="index.html#please-ignore-shelved-vs.-removed-vs.-parked-folders-needing-heavy-edits"><i class="fa fa-check"></i><b>1.13</b> Please ignore: Shelved vs. removed vs. parked folders needing heavy edits</a></li>
<li class="chapter" data-level="1.14" data-path="index.html"><a href="index.html#please-ignore-coding-aids-for-me"><i class="fa fa-check"></i><b>1.14</b> Please ignore: Coding aids (for me)</a>
<ul>
<li class="chapter" data-level="1.14.1" data-path="index.html"><a href="index.html#formatting"><i class="fa fa-check"></i><b>1.14.1</b> formatting</a></li>
<li class="chapter" data-level="1.14.2" data-path="index.html"><a href="index.html#tables"><i class="fa fa-check"></i><b>1.14.2</b> tables</a></li>
<li class="chapter" data-level="1.14.3" data-path="index.html"><a href="index.html#tinytex-problems"><i class="fa fa-check"></i><b>1.14.3</b> tinytex problems</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>FROC paradigm</b></span></li>
<li class="chapter" data-level="2" data-path="froc-paradigm.html"><a href="froc-paradigm.html"><i class="fa fa-check"></i><b>2</b> The FROC paradigm and visual search</a>
<ul>
<li class="chapter" data-level="2.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-how-much-finished"><i class="fa fa-check"></i><b>2.1</b> How much finished</a></li>
<li class="chapter" data-level="2.2" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-intro"><i class="fa fa-check"></i><b>2.2</b> Introduction</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-outline"><i class="fa fa-check"></i><b>2.2.1</b> Chapter outline</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-location-specific-paradigms"><i class="fa fa-check"></i><b>2.3</b> Location specific paradigms</a></li>
<li class="chapter" data-level="2.4" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-vis-search"><i class="fa fa-check"></i><b>2.4</b> Visual search</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-scoring-the-data"><i class="fa fa-check"></i><b>2.4.1</b> Proximity criterion and scoring the data</a></li>
<li class="chapter" data-level="2.4.2" data-path="froc-paradigm.html"><a href="froc-paradigm.html#multiple-marks-in-the-same-vicinity"><i class="fa fa-check"></i><b>2.4.2</b> Multiple marks in the same vicinity</a></li>
<li class="chapter" data-level="2.4.3" data-path="froc-paradigm.html"><a href="froc-paradigm.html#historical-context"><i class="fa fa-check"></i><b>2.4.3</b> Historical context</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-froc-plot"><i class="fa fa-check"></i><b>2.5</b> The FROC plot</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-plot-illustration"><i class="fa fa-check"></i><b>2.5.1</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-solar-analogy"><i class="fa fa-check"></i><b>2.6</b> The “solar” analogy</a></li>
<li class="chapter" data-level="2.7" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-discussion"><i class="fa fa-check"></i><b>2.7</b> Discussion</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="empirical.html"><a href="empirical.html"><i class="fa fa-check"></i><b>3</b> Empirical plots from FROC data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="empirical.html"><a href="empirical.html#empirical-how-much-finished"><i class="fa fa-check"></i><b>3.1</b> How much finished</a></li>
<li class="chapter" data-level="3.2" data-path="empirical.html"><a href="empirical.html#empirical-intro"><i class="fa fa-check"></i><b>3.2</b> Introduction</a></li>
<li class="chapter" data-level="3.3" data-path="empirical.html"><a href="empirical.html#empirical-mark-rating-pairs"><i class="fa fa-check"></i><b>3.3</b> FROC data and notation</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="empirical.html"><a href="empirical.html#lls-vs.-nls"><i class="fa fa-check"></i><b>3.3.1</b> LLs vs. NLs</a></li>
<li class="chapter" data-level="3.3.2" data-path="empirical.html"><a href="empirical.html#latent-vs.-actual-marks"><i class="fa fa-check"></i><b>3.3.2</b> Latent vs. actual marks</a></li>
<li class="chapter" data-level="3.3.3" data-path="empirical.html"><a href="empirical.html#z-samples-vs.-ratings"><i class="fa fa-check"></i><b>3.3.3</b> z-samples vs. ratings</a></li>
<li class="chapter" data-level="3.3.4" data-path="empirical.html"><a href="empirical.html#binning-rule"><i class="fa fa-check"></i><b>3.3.4</b> Binning rule</a></li>
<li class="chapter" data-level="3.3.5" data-path="empirical.html"><a href="empirical.html#empirical-notation"><i class="fa fa-check"></i><b>3.3.5</b> Notation</a></li>
<li class="chapter" data-level="3.3.6" data-path="empirical.html"><a href="empirical.html#comments"><i class="fa fa-check"></i><b>3.3.6</b> Comments</a></li>
<li class="chapter" data-level="3.3.7" data-path="empirical.html"><a href="empirical.html#empirical-indexing-marks"><i class="fa fa-check"></i><b>3.3.7</b> A conceptual and notatonal issue</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="empirical.html"><a href="empirical.html#empirical-froc-plot-1"><i class="fa fa-check"></i><b>3.4</b> The FROC plot</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="empirical.html"><a href="empirical.html#empirical-end-point"><i class="fa fa-check"></i><b>3.4.1</b> The observed FROC end-point and its semi-constrained property</a></li>
<li class="chapter" data-level="3.4.2" data-path="empirical.html"><a href="empirical.html#empirical-froc-plot-futility-extrapolation"><i class="fa fa-check"></i><b>3.4.2</b> Futility of extrapolation outside the observed end-point</a></li>
<li class="chapter" data-level="3.4.3" data-path="empirical.html"><a href="empirical.html#empirical-froc-plot-illustration"><i class="fa fa-check"></i><b>3.4.3</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="empirical.html"><a href="empirical.html#empirical-ROC"><i class="fa fa-check"></i><b>3.5</b> The inferred-ROC plot</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="empirical.html"><a href="empirical.html#empirical-ROC-fpf"><i class="fa fa-check"></i><b>3.5.1</b> The inferred-ROC z-sample</a></li>
<li class="chapter" data-level="3.5.2" data-path="empirical.html"><a href="empirical.html#empirical-ROC-tpf"><i class="fa fa-check"></i><b>3.5.2</b> Inferred TPF</a></li>
<li class="chapter" data-level="3.5.3" data-path="empirical.html"><a href="empirical.html#empirical-definition-empirical-auc-roc"><i class="fa fa-check"></i><b>3.5.3</b> The empirical ROC plot and AUC</a></li>
<li class="chapter" data-level="3.5.4" data-path="empirical.html"><a href="empirical.html#empirical-ROC-constrained"><i class="fa fa-check"></i><b>3.5.4</b> The observed end-point of the ROC and its constrained property</a></li>
<li class="chapter" data-level="3.5.5" data-path="empirical.html"><a href="empirical.html#empirical-roc-plot-illustration"><i class="fa fa-check"></i><b>3.5.5</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="empirical.html"><a href="empirical.html#empirical-AFROC"><i class="fa fa-check"></i><b>3.6</b> The alternative FROC (AFROC) plot</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="empirical.html"><a href="empirical.html#empirical-definition-empirical-auc-afroc"><i class="fa fa-check"></i><b>3.6.1</b> Definition: empirical AFROC plot and AUC</a></li>
<li class="chapter" data-level="3.6.2" data-path="empirical.html"><a href="empirical.html#empirical-AFROC-constrained"><i class="fa fa-check"></i><b>3.6.2</b> The observed end-point of the AFROC and its constrained property</a></li>
<li class="chapter" data-level="3.6.3" data-path="empirical.html"><a href="empirical.html#empirical-afroc-plot-illustration"><i class="fa fa-check"></i><b>3.6.3</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="empirical.html"><a href="empirical.html#empirical-wAFROC"><i class="fa fa-check"></i><b>3.7</b> The weighted-AFROC plot (wAFROC) plot</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="empirical.html"><a href="empirical.html#empirical-definition-empirical-auc-wafroc"><i class="fa fa-check"></i><b>3.7.1</b> The empirical wAFROC plot and AUC</a></li>
<li class="chapter" data-level="3.7.2" data-path="empirical.html"><a href="empirical.html#empirical-wafroc-plot-illustration"><i class="fa fa-check"></i><b>3.7.2</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="empirical.html"><a href="empirical.html#empirical-numerical-understanding"><i class="fa fa-check"></i><b>3.8</b> AFROC vs. wAFROC</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="empirical.html"><a href="empirical.html#nl-and-ll-z-samples"><i class="fa fa-check"></i><b>3.8.1</b> NL and LL z-samples</a></li>
<li class="chapter" data-level="3.8.2" data-path="empirical.html"><a href="empirical.html#lesion-weights"><i class="fa fa-check"></i><b>3.8.2</b> Lesion weights</a></li>
<li class="chapter" data-level="3.8.3" data-path="empirical.html"><a href="empirical.html#fpf"><i class="fa fa-check"></i><b>3.8.3</b> FPF</a></li>
<li class="chapter" data-level="3.8.4" data-path="empirical.html"><a href="empirical.html#llf"><i class="fa fa-check"></i><b>3.8.4</b> LLF</a></li>
<li class="chapter" data-level="3.8.5" data-path="empirical.html"><a href="empirical.html#wllf"><i class="fa fa-check"></i><b>3.8.5</b> wLLF</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="empirical.html"><a href="empirical.html#empirical-meanings"><i class="fa fa-check"></i><b>3.9</b> Interpretation of AUCs</a></li>
<li class="chapter" data-level="3.10" data-path="empirical.html"><a href="empirical.html#empirical-instructive-cases"><i class="fa fa-check"></i><b>3.10</b> Instructive examples</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="empirical.html"><a href="empirical.html#empirical-instructive-cases-FROC"><i class="fa fa-check"></i><b>3.10.1</b> The FROC</a></li>
<li class="chapter" data-level="3.10.2" data-path="empirical.html"><a href="empirical.html#empirical-instructive-cases-ROC"><i class="fa fa-check"></i><b>3.10.2</b> The ROC</a></li>
<li class="chapter" data-level="3.10.3" data-path="empirical.html"><a href="empirical.html#empirical-instructive-cases-AFROC"><i class="fa fa-check"></i><b>3.10.3</b> The AFROC</a></li>
<li class="chapter" data-level="3.10.4" data-path="empirical.html"><a href="empirical.html#empirical-instructive-cases-wAFROC"><i class="fa fa-check"></i><b>3.10.4</b> The wAFROC</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="empirical.html"><a href="empirical.html#empirical-froc-auc-poor"><i class="fa fa-check"></i><b>3.11</b> FROC-AUC is a poor measure</a>
<ul>
<li class="chapter" data-level="3.11.1" data-path="empirical.html"><a href="empirical.html#plot-of-froc-auc-vs.-roc-auc"><i class="fa fa-check"></i><b>3.11.1</b> Plot of FROC AUC vs. ROC AUC</a></li>
<li class="chapter" data-level="3.11.2" data-path="empirical.html"><a href="empirical.html#plot-of-afroc-auc-vs.-roc-auc"><i class="fa fa-check"></i><b>3.11.2</b> Plot of AFROC AUC vs. ROC AUC</a></li>
<li class="chapter" data-level="3.11.3" data-path="empirical.html"><a href="empirical.html#plot-of-wafroc-auc-vs.-roc-auc"><i class="fa fa-check"></i><b>3.11.3</b> Plot of wAFROC AUC vs. ROC AUC</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="empirical.html"><a href="empirical.html#empirical-AFROC1"><i class="fa fa-check"></i><b>3.12</b> The AFROC1 plot</a>
<ul>
<li class="chapter" data-level="3.12.1" data-path="empirical.html"><a href="empirical.html#empirical-definition-empirical-auc-afroc1"><i class="fa fa-check"></i><b>3.12.1</b> Empirical AFROC1 plot and AUC</a></li>
<li class="chapter" data-level="3.12.2" data-path="empirical.html"><a href="empirical.html#empirical-afroc1-plot-illustration"><i class="fa fa-check"></i><b>3.12.2</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="3.13" data-path="empirical.html"><a href="empirical.html#empirical-wAFROC1"><i class="fa fa-check"></i><b>3.13</b> The weighted-AFROC1 (wAFROC1) plot</a>
<ul>
<li class="chapter" data-level="3.13.1" data-path="empirical.html"><a href="empirical.html#empirical-definition-empirical-auc-wafroc1"><i class="fa fa-check"></i><b>3.13.1</b> Empirical wAFROC1 plot and AUC</a></li>
<li class="chapter" data-level="3.13.2" data-path="empirical.html"><a href="empirical.html#empirical-wafroc1-plot-illustration"><i class="fa fa-check"></i><b>3.13.2</b> Illustration with a dataset</a></li>
</ul></li>
<li class="chapter" data-level="3.14" data-path="empirical.html"><a href="empirical.html#empirical-summary"><i class="fa fa-check"></i><b>3.14</b> Summary</a></li>
<li class="chapter" data-level="3.15" data-path="empirical.html"><a href="empirical.html#empirical-theorem-1"><i class="fa fa-check"></i><b>3.15</b> Appendix 1: Proof of formula for wAFROC-AUC</a></li>
<li class="chapter" data-level="3.16" data-path="empirical.html"><a href="empirical.html#empirical-theorem-2"><i class="fa fa-check"></i><b>3.16</b> Appendix 2: Interpretation of area under straight line extension of wAFROC</a></li>
<li class="chapter" data-level="3.17" data-path="empirical.html"><a href="empirical.html#empirical-summary-computational-formulae"><i class="fa fa-check"></i><b>3.17</b> Appendix 3: Summary of computational formulae</a>
<ul>
<li class="chapter" data-level="3.17.1" data-path="empirical.html"><a href="empirical.html#froc"><i class="fa fa-check"></i><b>3.17.1</b> FROC</a></li>
<li class="chapter" data-level="3.17.2" data-path="empirical.html"><a href="empirical.html#roc"><i class="fa fa-check"></i><b>3.17.2</b> ROC</a></li>
<li class="chapter" data-level="3.17.3" data-path="empirical.html"><a href="empirical.html#afroc"><i class="fa fa-check"></i><b>3.17.3</b> AFROC</a></li>
<li class="chapter" data-level="3.17.4" data-path="empirical.html"><a href="empirical.html#wafroc"><i class="fa fa-check"></i><b>3.17.4</b> wAFROC</a></li>
<li class="chapter" data-level="3.17.5" data-path="empirical.html"><a href="empirical.html#afroc1"><i class="fa fa-check"></i><b>3.17.5</b> AFROC1</a></li>
<li class="chapter" data-level="3.17.6" data-path="empirical.html"><a href="empirical.html#wafroc1"><i class="fa fa-check"></i><b>3.17.6</b> wAFROC1</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>The radiological search model (RSM)</b></span></li>
<li class="chapter" data-level="4" data-path="visual-search.html"><a href="visual-search.html"><i class="fa fa-check"></i><b>4</b> Visual Search</a>
<ul>
<li class="chapter" data-level="4.1" data-path="visual-search.html"><a href="visual-search.html#visual-search-how-much-finished"><i class="fa fa-check"></i><b>4.1</b> How much finished</a></li>
<li class="chapter" data-level="4.2" data-path="visual-search.html"><a href="visual-search.html#visual-search-intro"><i class="fa fa-check"></i><b>4.2</b> Introduction</a></li>
<li class="chapter" data-level="4.3" data-path="visual-search.html"><a href="visual-search.html#visual-search-grouping-labeling-rois"><i class="fa fa-check"></i><b>4.3</b> Grouping and labeling ROIs</a></li>
<li class="chapter" data-level="4.4" data-path="visual-search.html"><a href="visual-search.html#visual-search-recognition-detection"><i class="fa fa-check"></i><b>4.4</b> Lesion-localization vs. detection</a></li>
<li class="chapter" data-level="4.5" data-path="visual-search.html"><a href="visual-search.html#visual-search-search-classification"><i class="fa fa-check"></i><b>4.5</b> Lesion-localization vs. lesion-classification</a></li>
<li class="chapter" data-level="4.6" data-path="visual-search.html"><a href="visual-search.html#visual-search-kundel-nodine-model"><i class="fa fa-check"></i><b>4.6</b> The Kundel - Nodine search model</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="visual-search.html"><a href="visual-search.html#visual-search-glancing-global-impression"><i class="fa fa-check"></i><b>4.6.1</b> Lesion-localization</a></li>
<li class="chapter" data-level="4.6.2" data-path="visual-search.html"><a href="visual-search.html#visual-search-scanning-local-feature-analysis"><i class="fa fa-check"></i><b>4.6.2</b> Lesion-classification</a></li>
<li class="chapter" data-level="4.6.3" data-path="visual-search.html"><a href="visual-search.html#visual-search-example"><i class="fa fa-check"></i><b>4.6.3</b> Example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="rsm.html"><a href="rsm.html"><i class="fa fa-check"></i><b>5</b> The radiological search model (RSM)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="rsm.html"><a href="rsm.html#rsm-how-much-finished"><i class="fa fa-check"></i><b>5.1</b> How much finished</a></li>
<li class="chapter" data-level="5.2" data-path="rsm.html"><a href="rsm.html#rsm-intro"><i class="fa fa-check"></i><b>5.2</b> Introduction</a></li>
<li class="chapter" data-level="5.3" data-path="rsm.html"><a href="rsm.html#rsm-details"><i class="fa fa-check"></i><b>5.3</b> The radiological search model</a></li>
<li class="chapter" data-level="5.4" data-path="rsm.html"><a href="rsm.html#rsm-assumptions"><i class="fa fa-check"></i><b>5.4</b> RSM assumptions</a></li>
<li class="chapter" data-level="5.5" data-path="rsm.html"><a href="rsm.html#rsm-parameter-physical-meanings"><i class="fa fa-check"></i><b>5.5</b> Physical meanings of the RSM parameters</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="rsm.html"><a href="rsm.html#rsm-mu-parameter"><i class="fa fa-check"></i><b>5.5.1</b> The <span class="math inline">\(\mu\)</span> parameter</a></li>
<li class="chapter" data-level="5.5.2" data-path="rsm.html"><a href="rsm.html#rsm-summary-lambda-parameter"><i class="fa fa-check"></i><b>5.5.2</b> The <span class="math inline">\(\lambda\)</span> parameter</a></li>
<li class="chapter" data-level="5.5.3" data-path="rsm.html"><a href="rsm.html#rsm-summary-nu-parameter"><i class="fa fa-check"></i><b>5.5.3</b> The <span class="math inline">\(\nu\)</span> parameter</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="rsm.html"><a href="rsm.html#rsm-intrinsic-parameters"><i class="fa fa-check"></i><b>5.6</b> Intrinsic RSM parameters</a></li>
<li class="chapter" data-level="5.7" data-path="rsm.html"><a href="rsm.html#rsm-discussion-summary"><i class="fa fa-check"></i><b>5.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="rsm-predictions.html"><a href="rsm-predictions.html"><i class="fa fa-check"></i><b>6</b> ROC predictions of the RSM</a>
<ul>
<li class="chapter" data-level="6.1" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-how-much-finished"><i class="fa fa-check"></i><b>6.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="6.2" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-intro"><i class="fa fa-check"></i><b>6.2</b> TBA Introduction</a></li>
<li class="chapter" data-level="6.3" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-inferred-roc"><i class="fa fa-check"></i><b>6.3</b> Inferred ROC z-sample</a></li>
<li class="chapter" data-level="6.4" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-end-point"><i class="fa fa-check"></i><b>6.4</b> End-point of the ROC</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-constrained-end-point-abscissa"><i class="fa fa-check"></i><b>6.4.1</b> The abscissa of the ROC end-point</a></li>
<li class="chapter" data-level="6.4.2" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-constrained-end-point-ordinate"><i class="fa fa-check"></i><b>6.4.2</b> The ordinate of the ROC end-point</a></li>
<li class="chapter" data-level="6.4.3" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-end-point-variable-number-lesions"><i class="fa fa-check"></i><b>6.4.3</b> Variable number of lesions per case</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve"><i class="fa fa-check"></i><b>6.5</b> ROC curve</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-fpf"><i class="fa fa-check"></i><b>6.5.1</b> Derivation of FPF</a></li>
<li class="chapter" data-level="6.5.2" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-tpf"><i class="fa fa-check"></i><b>6.5.2</b> Derivation of TPF</a></li>
<li class="chapter" data-level="6.5.3" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-tpf-varying-lesions"><i class="fa fa-check"></i><b>6.5.3</b> Variable number of lesions per case</a></li>
<li class="chapter" data-level="6.5.4" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-pdfs"><i class="fa fa-check"></i><b>6.5.4</b> ROC decision variable pdfs</a></li>
<li class="chapter" data-level="6.5.5" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-auc"><i class="fa fa-check"></i><b>6.5.5</b> ROC AUC</a></li>
<li class="chapter" data-level="6.5.6" data-path="rsm-predictions.html"><a href="rsm-predictions.html#comparing-tpf-formula-to-rjafroc-functions"><i class="fa fa-check"></i><b>6.5.6</b> Comparing TPF formula to <code>RJafroc</code> functions</a></li>
<li class="chapter" data-level="6.5.7" data-path="rsm-predictions.html"><a href="rsm-predictions.html#effect-on-operating-point-of-varying-rsm-parameters"><i class="fa fa-check"></i><b>6.5.7</b> Effect on operating point of varying RSM parameters</a></li>
<li class="chapter" data-level="6.5.8" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curves"><i class="fa fa-check"></i><b>6.5.8</b> Sample ROC curves</a></li>
<li class="chapter" data-level="6.5.9" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-pdf-curves"><i class="fa fa-check"></i><b>6.5.9</b> Sample RSM pdf curves</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-proper"><i class="fa fa-check"></i><b>6.6</b> Proper ROC curve</a></li>
<li class="chapter" data-level="6.7" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-aucs-zeta1"><i class="fa fa-check"></i><b>6.7</b> <span class="math inline">\(\zeta\)</span> dependence of ROC AUC</a></li>
<li class="chapter" data-level="6.8" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-discussion-summary"><i class="fa fa-check"></i><b>6.8</b> TBA Discussion / Summary</a></li>
<li class="chapter" data-level="6.9" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-appendix1"><i class="fa fa-check"></i><b>6.9</b> Appendix 1: Proof of continuity of slope at the end-point</a></li>
<li class="chapter" data-level="6.10" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-appendix2"><i class="fa fa-check"></i><b>6.10</b> Appendix 2: Numerical illustration of continuity</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html"><i class="fa fa-check"></i><b>7</b> Other RSM predictions</a>
<ul>
<li class="chapter" data-level="7.1" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-how-much-finished"><i class="fa fa-check"></i><b>7.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="7.2" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-intro"><i class="fa fa-check"></i><b>7.2</b> TBA Introduction</a></li>
<li class="chapter" data-level="7.3" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-froc-curve"><i class="fa fa-check"></i><b>7.3</b> RSM-predicted FROC curve</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#froc-plots-lambda_i-nu_i-parameterization"><i class="fa fa-check"></i><b>7.3.1</b> FROC plots <span class="math inline">\(\lambda_i, \nu_i\)</span> parameterization</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-froc-afroc-curve"><i class="fa fa-check"></i><b>7.4</b> RSM-predicted AFROC curve</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#afroc-plots-lambda_i-nu_i-parameterization"><i class="fa fa-check"></i><b>7.4.1</b> AFROC plots <span class="math inline">\(\lambda_i, \nu_i\)</span> parameterization</a></li>
<li class="chapter" data-level="7.4.2" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-no-marks"><i class="fa fa-check"></i><b>7.4.2</b> Case of the reader who does not make any marks</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-wafroc-curve"><i class="fa fa-check"></i><b>7.5</b> RSM-predicted wAFROC curve</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#wafroc-plots-lambda_i-nu_i-parameterization"><i class="fa fa-check"></i><b>7.5.1</b> wAFROC plots <span class="math inline">\(\lambda_i, \nu_i\)</span> parameterization</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-comments"><i class="fa fa-check"></i><b>7.6</b> Comments on end-point-discontinuity property</a></li>
<li class="chapter" data-level="7.7" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-appendix"><i class="fa fa-check"></i><b>7.7</b> Appendix</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-froc-physical-parameters"><i class="fa fa-check"></i><b>7.7.1</b> Slope of the FROC curve</a></li>
<li class="chapter" data-level="7.7.2" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#froc-plots-lambda-nu-parameterization"><i class="fa fa-check"></i><b>7.7.2</b> FROC plots <span class="math inline">\(\lambda, \nu\)</span> parameterization</a></li>
<li class="chapter" data-level="7.7.3" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-afroc-physical-parameters"><i class="fa fa-check"></i><b>7.7.3</b> Slope of the AFROC curve</a></li>
<li class="chapter" data-level="7.7.4" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-wafroc-physical-parameters"><i class="fa fa-check"></i><b>7.7.4</b> wAFROC plots <span class="math inline">\(\lambda, \nu\)</span> parameterization</a></li>
<li class="chapter" data-level="7.7.5" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-roc-above-afroc"><i class="fa fa-check"></i><b>7.7.5</b> ROC curves are above AFROC curves</a></li>
<li class="chapter" data-level="7.7.6" data-path="rsm-other-predictions.html"><a href="rsm-other-predictions.html#rsm-other-predictions-wafroc-above-afroc"><i class="fa fa-check"></i><b>7.7.6</b> Are wAFROC curves above AFROC curves?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html"><i class="fa fa-check"></i><b>8</b> Lesion localization and classification performances</a>
<ul>
<li class="chapter" data-level="8.1" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-how-much-finished"><i class="fa fa-check"></i><b>8.1</b> How much finished</a></li>
<li class="chapter" data-level="8.2" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-intro"><i class="fa fa-check"></i><b>8.2</b> Introduction</a></li>
<li class="chapter" data-level="8.3" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-quantifying"><i class="fa fa-check"></i><b>8.3</b> Quantifying lesion-localization performance</a></li>
<li class="chapter" data-level="8.4" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-performance"><i class="fa fa-check"></i><b>8.4</b> Quantifying lesion-classification performance</a></li>
<li class="chapter" data-level="8.5" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-discussion"><i class="fa fa-check"></i><b>8.5</b> Discussion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="rsm-fitting.html"><a href="rsm-fitting.html"><i class="fa fa-check"></i><b>9</b> RSM fitting</a>
<ul>
<li class="chapter" data-level="9.1" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-how-much-finished"><i class="fa fa-check"></i><b>9.1</b> How much finished</a></li>
<li class="chapter" data-level="9.2" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-intro"><i class="fa fa-check"></i><b>9.2</b> TBA Introduction</a></li>
<li class="chapter" data-level="9.3" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-roc-likelihood"><i class="fa fa-check"></i><b>9.3</b> ROC Likelihood function</a></li>
<li class="chapter" data-level="9.4" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-fitrsmroc-implementation"><i class="fa fa-check"></i><b>9.4</b> Implementation</a></li>
<li class="chapter" data-level="9.5" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-fitrsmroc-usage-example"><i class="fa fa-check"></i><b>9.5</b> <code>FitRsmROC</code> usage example</a></li>
<li class="chapter" data-level="9.6" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-discussion-summary"><i class="fa fa-check"></i><b>9.6</b> Discussion / Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html"><i class="fa fa-check"></i><b>10</b> Three proper ROC fits</a>
<ul>
<li class="chapter" data-level="10.1" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-how-much-finished"><i class="fa fa-check"></i><b>10.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="10.2" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-intro"><i class="fa fa-check"></i><b>10.2</b> TBA Introduction</a></li>
<li class="chapter" data-level="10.3" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-applications"><i class="fa fa-check"></i><b>10.3</b> Application to datasets</a></li>
<li class="chapter" data-level="10.4" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-composite-plots"><i class="fa fa-check"></i><b>10.4</b> Composite plots</a></li>
<li class="chapter" data-level="10.5" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-rsm-parameters"><i class="fa fa-check"></i><b>10.5</b> RSM parameters</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-parameters-van-dyke-dataset-i-1-j-2"><i class="fa fa-check"></i><b>10.5.1</b> RSM parameters Van Dyke dataset i = 1, j= 2</a></li>
<li class="chapter" data-level="10.5.2" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-parameters-franken-dataset-i-2-j-3"><i class="fa fa-check"></i><b>10.5.2</b> RSM parameters Franken dataset i = 2, j= 3</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-cbm-parameters"><i class="fa fa-check"></i><b>10.6</b> CBM parameters</a></li>
<li class="chapter" data-level="10.7" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-proproc-parameters"><i class="fa fa-check"></i><b>10.7</b> PROPROC parameters</a></li>
<li class="chapter" data-level="10.8" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-overview"><i class="fa fa-check"></i><b>10.8</b> Overview of findings</a>
<ul>
<li class="chapter" data-level="10.8.1" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-slopes"><i class="fa fa-check"></i><b>10.8.1</b> Slopes</a></li>
<li class="chapter" data-level="10.8.2" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-confidence-intervals"><i class="fa fa-check"></i><b>10.8.2</b> Confidence intervals</a></li>
<li class="chapter" data-level="10.8.3" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-slopes-confidence-intervals-summary"><i class="fa fa-check"></i><b>10.8.3</b> Summary of slopes and confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-discussion-summary"><i class="fa fa-check"></i><b>10.9</b> Reason for equal AUCs / Summary</a></li>
<li class="chapter" data-level="10.10" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-appendices"><i class="fa fa-check"></i><b>10.10</b> Appendices</a>
<ul>
<li class="chapter" data-level="10.10.1" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-one-dataset-proproc"><i class="fa fa-check"></i><b>10.10.1</b> Location of PROPROC files</a></li>
<li class="chapter" data-level="10.10.2" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-pre-analyzed-results"><i class="fa fa-check"></i><b>10.10.2</b> Location of pre-analyzed results</a></li>
<li class="chapter" data-level="10.10.3" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-representative-plots-van-dyke"><i class="fa fa-check"></i><b>10.10.3</b> Plots for the Van Dyke dataset</a></li>
<li class="chapter" data-level="10.10.4" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-representative-plots-franken"><i class="fa fa-check"></i><b>10.10.4</b> Plots for the Franken dataset</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>CAD applications</b></span></li>
<li class="chapter" data-level="11" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html"><i class="fa fa-check"></i><b>11</b> Standalone CAD</a>
<ul>
<li class="chapter" data-level="11.1" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-how-much-finished"><i class="fa fa-check"></i><b>11.1</b> How much finished</a></li>
<li class="chapter" data-level="11.2" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-introduction"><i class="fa fa-check"></i><b>11.2</b> Introduction</a></li>
<li class="chapter" data-level="11.3" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-overview"><i class="fa fa-check"></i><b>11.3</b> Overview</a></li>
<li class="chapter" data-level="11.4" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-methods"><i class="fa fa-check"></i><b>11.4</b> Methods</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-two-previous-studies"><i class="fa fa-check"></i><b>11.4.1</b> Studies assessing performance of CAD vs. radiologists</a></li>
<li class="chapter" data-level="11.4.2" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#the-1t-rrfc-analysis-model"><i class="fa fa-check"></i><b>11.4.2</b> The 1T-RRFC analysis model</a></li>
<li class="chapter" data-level="11.4.3" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-2TRRRC-anlaysis"><i class="fa fa-check"></i><b>11.4.3</b> The 2T-RRRC analysis model</a></li>
<li class="chapter" data-level="11.4.4" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-1TRRRC-anlaysis"><i class="fa fa-check"></i><b>11.4.4</b> The 1T-RRRC analysis model</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-computational-details"><i class="fa fa-check"></i><b>11.5</b> Implementation</a></li>
<li class="chapter" data-level="11.6" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-results"><i class="fa fa-check"></i><b>11.6</b> Results</a></li>
<li class="chapter" data-level="11.7" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-discussion"><i class="fa fa-check"></i><b>11.7</b> Discussion</a></li>
<li class="chapter" data-level="11.8" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-appendix1"><i class="fa fa-check"></i><b>11.8</b> Appendix 1</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#example-1"><i class="fa fa-check"></i><b>11.8.1</b> Example 1</a></li>
<li class="chapter" data-level="11.8.2" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#example-2"><i class="fa fa-check"></i><b>11.8.2</b> Example 2</a></li>
<li class="chapter" data-level="11.8.3" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#example-3"><i class="fa fa-check"></i><b>11.8.3</b> Example 3</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-appendix2"><i class="fa fa-check"></i><b>11.9</b> Appendix 2</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="optim-op-point.html"><a href="optim-op-point.html"><i class="fa fa-check"></i><b>12</b> CAD optimal operating point</a>
<ul>
<li class="chapter" data-level="12.1" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-how-much-finished"><i class="fa fa-check"></i><b>12.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="12.2" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-intro"><i class="fa fa-check"></i><b>12.2</b> Introduction</a></li>
<li class="chapter" data-level="12.3" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-methods"><i class="fa fa-check"></i><b>12.3</b> Methods</a></li>
<li class="chapter" data-level="12.4" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-vary-lambda"><i class="fa fa-check"></i><b>12.4</b> Varying <span class="math inline">\(\lambda\)</span> optimizations</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="optim-op-point.html"><a href="optim-op-point.html#summary-table"><i class="fa fa-check"></i><b>12.4.1</b> Summary table</a></li>
<li class="chapter" data-level="12.4.2" data-path="optim-op-point.html"><a href="optim-op-point.html#froc-1"><i class="fa fa-check"></i><b>12.4.2</b> FROC</a></li>
<li class="chapter" data-level="12.4.3" data-path="optim-op-point.html"><a href="optim-op-point.html#wafroc-1"><i class="fa fa-check"></i><b>12.4.3</b> wAFROC</a></li>
<li class="chapter" data-level="12.4.4" data-path="optim-op-point.html"><a href="optim-op-point.html#roc-1"><i class="fa fa-check"></i><b>12.4.4</b> ROC</a></li>
<li class="chapter" data-level="12.4.5" data-path="optim-op-point.html"><a href="optim-op-point.html#why-not-maximize-roc-auc"><i class="fa fa-check"></i><b>12.4.5</b> Why not maximize ROC-AUC?</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-vary-nu-mu"><i class="fa fa-check"></i><b>12.5</b> Varying <span class="math inline">\(\nu\)</span> and <span class="math inline">\(\mu\)</span> optimizations</a></li>
<li class="chapter" data-level="12.6" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-vary-nu-limiting-situations"><i class="fa fa-check"></i><b>12.6</b> Limiting situations</a></li>
<li class="chapter" data-level="12.7" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-trends"><i class="fa fa-check"></i><b>12.7</b> Trends</a></li>
<li class="chapter" data-level="12.8" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-how-to-use-method"><i class="fa fa-check"></i><b>12.8</b> Applying the method</a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-application"><i class="fa fa-check"></i><b>12.8.1</b> A CAD application</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-discussion"><i class="fa fa-check"></i><b>12.9</b> TBA Discussion</a></li>
<li class="chapter" data-level="12.10" data-path="optim-op-point.html"><a href="optim-op-point.html#cad-optim-op-appendices"><i class="fa fa-check"></i><b>12.10</b> Appendices</a>
<ul>
<li class="chapter" data-level="12.10.1" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-vary-nu"><i class="fa fa-check"></i><b>12.10.1</b> Varying <span class="math inline">\(\nu\)</span> optimizations</a></li>
<li class="chapter" data-level="12.10.2" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-vary-mu"><i class="fa fa-check"></i><b>12.10.2</b> Varying <span class="math inline">\(\mu\)</span> optimizations</a></li>
<li class="chapter" data-level="12.10.3" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-limiting-situations"><i class="fa fa-check"></i><b>12.10.3</b> Limiting cases</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analyze-diseased-only-dataset.html"><a href="analyze-diseased-only-dataset.html"><i class="fa fa-check"></i><b>13</b> Analyzing a dataset with only diseased cases</a>
<ul>
<li class="chapter" data-level="13.1" data-path="analyze-diseased-only-dataset.html"><a href="analyze-diseased-only-dataset.html#analyze-diseased-only-dataset-how-much-finished"><i class="fa fa-check"></i><b>13.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="13.2" data-path="analyze-diseased-only-dataset.html"><a href="analyze-diseased-only-dataset.html#analyze-diseased-only-dataset-methods"><i class="fa fa-check"></i><b>13.2</b> The problem</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="analyze-diseased-only-dataset.html"><a href="analyze-diseased-only-dataset.html#analyze-diseased-only-dataset-step-1"><i class="fa fa-check"></i><b>13.2.1</b> Step 1: Create a test (diseased cases only) dataset</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>DATASETS</b></span></li>
<li class="chapter" data-level="14" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>14</b> Datasets</a>
<ul>
<li class="chapter" data-level="14.1" data-path="datasets.html"><a href="datasets.html#datasets-datasetsdd"><i class="fa fa-check"></i><b>14.1</b> Datasets embedded in <code>RJafroc</code></a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="datasets.html"><a href="datasets.html#datasets-dataset01"><i class="fa fa-check"></i><b>14.1.1</b> Dataset01</a></li>
<li class="chapter" data-level="14.1.2" data-path="datasets.html"><a href="datasets.html#datasets-dataset02"><i class="fa fa-check"></i><b>14.1.2</b> Dataset02</a></li>
<li class="chapter" data-level="14.1.3" data-path="datasets.html"><a href="datasets.html#datasets-dataset03"><i class="fa fa-check"></i><b>14.1.3</b> Dataset03</a></li>
<li class="chapter" data-level="14.1.4" data-path="datasets.html"><a href="datasets.html#datasets-dataset04"><i class="fa fa-check"></i><b>14.1.4</b> Dataset04</a></li>
<li class="chapter" data-level="14.1.5" data-path="datasets.html"><a href="datasets.html#datasets-dataset05"><i class="fa fa-check"></i><b>14.1.5</b> Dataset05</a></li>
<li class="chapter" data-level="14.1.6" data-path="datasets.html"><a href="datasets.html#datasets-dataset06"><i class="fa fa-check"></i><b>14.1.6</b> Dataset06</a></li>
<li class="chapter" data-level="14.1.7" data-path="datasets.html"><a href="datasets.html#datasets-dataset07"><i class="fa fa-check"></i><b>14.1.7</b> Dataset07</a></li>
<li class="chapter" data-level="14.1.8" data-path="datasets.html"><a href="datasets.html#datasets-dataset08"><i class="fa fa-check"></i><b>14.1.8</b> Dataset08</a></li>
<li class="chapter" data-level="14.1.9" data-path="datasets.html"><a href="datasets.html#datasets-dataset09"><i class="fa fa-check"></i><b>14.1.9</b> Dataset09</a></li>
<li class="chapter" data-level="14.1.10" data-path="datasets.html"><a href="datasets.html#datasets-dataset10"><i class="fa fa-check"></i><b>14.1.10</b> Dataset10</a></li>
<li class="chapter" data-level="14.1.11" data-path="datasets.html"><a href="datasets.html#datasets-dataset11"><i class="fa fa-check"></i><b>14.1.11</b> Dataset11</a></li>
<li class="chapter" data-level="14.1.12" data-path="datasets.html"><a href="datasets.html#datasets-dataset12"><i class="fa fa-check"></i><b>14.1.12</b> Dataset12</a></li>
<li class="chapter" data-level="14.1.13" data-path="datasets.html"><a href="datasets.html#datasets-dataset13"><i class="fa fa-check"></i><b>14.1.13</b> Dataset13</a></li>
<li class="chapter" data-level="14.1.14" data-path="datasets.html"><a href="datasets.html#datasets-dataset14"><i class="fa fa-check"></i><b>14.1.14</b> Dataset14</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="datasets.html"><a href="datasets.html#other-datasets"><i class="fa fa-check"></i><b>14.2</b> Other datasets</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="datasets.html"><a href="datasets.html#datasets-datasetCadLroc"><i class="fa fa-check"></i><b>14.2.1</b> DatasetCadLroc</a></li>
<li class="chapter" data-level="14.2.2" data-path="datasets.html"><a href="datasets.html#datasets-datasetCadSimuFroc"><i class="fa fa-check"></i><b>14.2.2</b> datasetCadSimuFroc</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>REFERENCES</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The RJafroc Froc Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="rsm-3-fits" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter 10</span> Three proper ROC fits<a href="rsm-3-fits.html#rsm-3-fits" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="rsm-3-fits-how-much-finished" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> TBA How much finished<a href="rsm-3-fits.html#rsm-3-fits-how-much-finished" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>99%</p>
</div>
<div id="rsm-3-fits-intro" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> TBA Introduction<a href="rsm-3-fits.html#rsm-3-fits-intro" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A proper ROC curve is one whose slope decreases monotonically as the operating point moves up the curve, a consequence of which is that a proper ROC does not display an inappropriate chance line crossing followed by a sharp upward turn, i.e., a “hook”, usually near the (1,1) upper right corner.</p>
<p>There are three methods for fitting proper curves to ROC datasets:</p>
<ul>
<li>The radiological search model (RSM) described in Chapter <a href="rsm-fitting.html#rsm-fitting">9</a>,</li>
<li>The PROPROC (proper ROC) model described in TBA Chapter 20.</li>
<li>The CBM (contaminated binormal model) described in TBA Chapter 20.</li>
</ul>
<p>This chapter compares these methods by fitting them to 14 multiple-treatment multiple-reader datasets described in Chapter <a href="datasets.html#datasets">14</a>. <a href="#fn33" class="footnote-ref" id="fnref33"><sup>33</sup></a></p>
<p>The motivation for this work was a serendipitous finding <span class="citation">(<a href="#ref-chakraborty2011estimating" role="doc-biblioref">DP Chakraborty and Svahn 2011</a>)</span> that PROPROC fitted ROC AUCs and RSM fitted ROC AUCs were identical for some datasets. This led to extending that work to include CBM and more datasets.</p>
</div>
<div id="rsm-3-fits-applications" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Application to datasets<a href="rsm-3-fits.html#rsm-3-fits-applications" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Both RSM and CBM are implemented in <code>RJafroc</code>. <code>PROPROC</code> is implemented in Windows software OR DBM-MRMC 2.5 <a href="#fn34" class="footnote-ref" id="fnref34"><sup>34</sup></a> that was available <a href="https://perception.lab.uiowa.edu/software">here</a>, last accessed 1/4/21.</p>
<p>The RSM, PROPROC and CBM algorithms were applied to datasets described in Chapter <a href="datasets.html#datasets">14</a>.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="rsm-3-fits.html#cb105-1" aria-hidden="true" tabindex="-1"></a>datasetNames <span class="ot">&lt;-</span>  </span>
<span id="cb105-2"><a href="rsm-3-fits.html#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;TONY&quot;</span>, <span class="st">&quot;VD&quot;</span>, <span class="st">&quot;FR&quot;</span>, </span>
<span id="cb105-3"><a href="rsm-3-fits.html#cb105-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;FED&quot;</span>, <span class="st">&quot;JT&quot;</span>, <span class="st">&quot;MAG&quot;</span>, </span>
<span id="cb105-4"><a href="rsm-3-fits.html#cb105-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;OPT&quot;</span>, <span class="st">&quot;PEN&quot;</span>, <span class="st">&quot;NICO&quot;</span>,</span>
<span id="cb105-5"><a href="rsm-3-fits.html#cb105-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;RUS&quot;</span>, <span class="st">&quot;DOB1&quot;</span>, <span class="st">&quot;DOB2&quot;</span>, </span>
<span id="cb105-6"><a href="rsm-3-fits.html#cb105-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;DOB3&quot;</span>, <span class="st">&quot;FZR&quot;</span>)</span></code></pre></div>
<p>These are abbreviations for “TONY”, “Van Dyke”, “Franken”, “Federica”, “Thompson”, “Magnus”, “Lucy Warren”, “Penedo”, “Nico-CAD-ROC”, “Ruschin”, “Dobbins-1”, “Dobbins-2”, “Dobbins-3”, “Federica Real Roc”. These datasets are included with <code>RJafroc</code> and the corresponding objects are named <code>datasetXX</code>, where XX is an integer ranging from 1 to 14.</p>
<p>In the following we focus, for now, on just two ROC datasets (these have been widely used in the literature to illustrate ROC analysis methodology advances) namely the Van Dyke (VD) and the Franken (FR) datasets. Illustrative examples are shown for treatment 1 and reader 2 for the Van Dyke dataset and for treatment 2 and reader 3 for the Franken dataset. Plots for all treatment-reader combinations for these two datasets are in Appendix <a href="rsm-3-fits.html#rsm-3-fits-representative-plots-van-dyke">10.10.3</a> and Appendix <a href="rsm-3-fits.html#rsm-3-fits-representative-plots-franken">10.10.4</a>.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="rsm-3-fits.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># VD dataset</span></span>
<span id="cb106-2"><a href="rsm-3-fits.html#cb106-2" aria-hidden="true" tabindex="-1"></a>ret <span class="ot">&lt;-</span> <span class="fu">Compare3ProperRocFits</span>(datasetNames, <span class="fu">which</span>(datasetNames <span class="sc">==</span> <span class="st">&quot;VD&quot;</span>))</span>
<span id="cb106-3"><a href="rsm-3-fits.html#cb106-3" aria-hidden="true" tabindex="-1"></a>resultsVD <span class="ot">&lt;-</span> ret<span class="sc">$</span>allResults</span>
<span id="cb106-4"><a href="rsm-3-fits.html#cb106-4" aria-hidden="true" tabindex="-1"></a>plotsVD <span class="ot">&lt;-</span> ret<span class="sc">$</span>allPlots</span>
<span id="cb106-5"><a href="rsm-3-fits.html#cb106-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-6"><a href="rsm-3-fits.html#cb106-6" aria-hidden="true" tabindex="-1"></a><span class="co"># FR dataset</span></span>
<span id="cb106-7"><a href="rsm-3-fits.html#cb106-7" aria-hidden="true" tabindex="-1"></a>ret <span class="ot">&lt;-</span> <span class="fu">Compare3ProperRocFits</span>(datasetNames, <span class="fu">which</span>(datasetNames <span class="sc">==</span> <span class="st">&quot;FR&quot;</span>))</span>
<span id="cb106-8"><a href="rsm-3-fits.html#cb106-8" aria-hidden="true" tabindex="-1"></a>resultsFR <span class="ot">&lt;-</span> ret<span class="sc">$</span>allResults</span>
<span id="cb106-9"><a href="rsm-3-fits.html#cb106-9" aria-hidden="true" tabindex="-1"></a>plotsFR <span class="ot">&lt;-</span> ret<span class="sc">$</span>allPlots</span></code></pre></div>
<ul>
<li>The supporting code is in the function <code>Compare3ProperRocFits()</code> located at <code>R/compare-3-fits/Compare3ProperRocFits.R</code>.</li>
<li>The analyzed results file locations are shown in Section <a href="rsm-3-fits.html#rsm-3-fits-pre-analyzed-results">10.10.2</a>.</li>
<li>The fitted parameters are contained in <code>resultsVD</code> and <code>resultsFR; the composite plots (i.e., 3 overlaid plots corresponding to the three proper ROC fitting algorithms) for each treatment and reader, are contained in</code>plotsVD<code>and</code>plotsFR`.</li>
</ul>
</div>
<div id="rsm-3-fits-composite-plots" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Composite plots<a href="rsm-3-fits.html#rsm-3-fits-composite-plots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>The <code>plotArr</code> list contains plots for the two datasets. The Van Dyke plots are in <code>plotsVD</code> and the Franken in <code>plotsFR</code>.</li>
<li>The Van Dyke dataset contains <span class="math inline">\(I \times J = 2 \times 5 = 10\)</span> composite plots.</li>
<li>The Franken dataset contains <span class="math inline">\(I \times J = 2 \times 4 = 8\)</span> composite plots.</li>
</ul>
<p>The following code shows how to display the composite plot for the Van Dyke dataset for treatment 1 and reader 2, i.e., i = 1 and j = 2.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="rsm-3-fits.html#cb107-1" aria-hidden="true" tabindex="-1"></a>plotsVD[[<span class="dv">1</span>,<span class="dv">2</span>]]</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-vd-12"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-vd-12-1.png" alt="Composite plots for Van Dyke dataset for treatment = 1, reader 2." width="672" />
<p class="caption">
FIGURE 10.1: Composite plots for Van Dyke dataset for treatment = 1, reader 2.
</p>
</div>
<p>It contains 3 fitted curves:</p>
<ul>
<li>The RSM fitted curve is in black.</li>
<li>The PROPROC fitted curve is in red.</li>
<li>The CBM fitted curve is in blue.</li>
</ul>
<p>Three operating points from the binned data are shown as well as exact 95% confidence intervals for the lowest and uppermost operating points.</p>
<p>All 10 composite plots for the Van Dyke dataset are shown in Appendix <a href="rsm-3-fits.html#rsm-3-fits-representative-plots-van-dyke">10.10.3</a>.</p>
<p>The next example shows composite plots for the Franken dataset for treatment = 2 and reader = 3.</p>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-fr-23"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-fr-23-1.png" alt="Composite plots for Franken dataset for treatment = 2, reader 3." width="672" />
<p class="caption">
FIGURE 10.2: Composite plots for Franken dataset for treatment = 2, reader 3.
</p>
</div>
<p>Note that the RSM end-point is almost at the upper right corner, implying lower lesion-localization performance.</p>
<p>All 10 composite plots for the Franken dataset are shown in Appendix <a href="rsm-3-fits.html#rsm-3-fits-representative-plots-franken">10.10.4</a>.</p>
</div>
<div id="rsm-3-fits-rsm-parameters" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> RSM parameters<a href="rsm-3-fits.html#rsm-3-fits-rsm-parameters" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The parameters corresponding to the RSM plots for the Van Dyke dataset are accessed as shown next.</p>
<ul>
<li><code>resultsVD[[i,j]]$retRsm$mu</code> is the RSM <span class="math inline">\(\mu\)</span> parameter for the Van Dyke dataset for treatment i and reader j;</li>
<li><code>resultsVD[[i,j]]$retRsm$lambda</code> is the RSM <span class="math inline">\(\lambda\)</span> parameter;<br />
</li>
<li><code>resultsVD[[i,j]]$retRsm$nu</code> is the RSM <span class="math inline">\(\nu\)</span> parameter;</li>
<li><code>resultsVD[[i,j]]$retRsm$zeta1</code> is the RSM <span class="math inline">\(\zeta_1\)</span> parameter;</li>
</ul>
<div id="rsm-parameters-van-dyke-dataset-i-1-j-2" class="section level3 hasAnchor" number="10.5.1">
<h3><span class="header-section-number">10.5.1</span> RSM parameters Van Dyke dataset i = 1, j= 2<a href="rsm-3-fits.html#rsm-parameters-van-dyke-dataset-i-1-j-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following displays RSM parameters for the Van Dyke dataset, treatment 1 and reader 2:</p>
<pre><code>## RSM parameters, Van Dyke Dataset, i=1, j=2: 
## mu =  2.201413 
## lambda =  0.2569453 
## nu =  0.7524016 
## zeta_1 =  -0.1097901 
## AUC =  0.8653694 
## sigma_AUC =  0.04740562 
## NLLini =  96.48516 
## NLLfin =  85.86244</code></pre>
<p>The first four values are the fitted values for the RSM parameters <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\lambda\)</span>, <span class="math inline">\(\nu\)</span> and <span class="math inline">\(\zeta_1\)</span>. The next value is the AUC under the fitted RSM curve followed by its standard error. The last two values are the initial and final values of negative log-likelihood <a href="#fn35" class="footnote-ref" id="fnref35"><sup>35</sup></a>.</p>
<p>From the previous chapter the RSM parameters can be used to calculate lesion-localization and lesion-classification performances, namely <span class="math inline">\(L_L\)</span> and <span class="math inline">\(L_C\)</span> respectively. The following function calculates these values:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="rsm-3-fits.html#cb109-1" aria-hidden="true" tabindex="-1"></a>LesionLocLesionCls <span class="ot">&lt;-</span> <span class="cf">function</span>(mu, lambda, nu, lesDistr) {</span>
<span id="cb109-2"><a href="rsm-3-fits.html#cb109-2" aria-hidden="true" tabindex="-1"></a>  temp <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb109-3"><a href="rsm-3-fits.html#cb109-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (L <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(lesDistr)) {</span>
<span id="cb109-4"><a href="rsm-3-fits.html#cb109-4" aria-hidden="true" tabindex="-1"></a>    temp <span class="ot">&lt;-</span> temp <span class="sc">+</span> lesDistr[L] <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> nu)<span class="sc">^</span>L</span>
<span id="cb109-5"><a href="rsm-3-fits.html#cb109-5" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb109-6"><a href="rsm-3-fits.html#cb109-6" aria-hidden="true" tabindex="-1"></a>  L_L <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="sc">-</span>lambda) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> temp)</span>
<span id="cb109-7"><a href="rsm-3-fits.html#cb109-7" aria-hidden="true" tabindex="-1"></a>  L_C <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(mu<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">2</span>))</span>
<span id="cb109-8"><a href="rsm-3-fits.html#cb109-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">list</span>(</span>
<span id="cb109-9"><a href="rsm-3-fits.html#cb109-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">L_L =</span> L_L,</span>
<span id="cb109-10"><a href="rsm-3-fits.html#cb109-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">L_C =</span> L_C</span>
<span id="cb109-11"><a href="rsm-3-fits.html#cb109-11" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb109-12"><a href="rsm-3-fits.html#cb109-12" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>The function is used as follows:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="rsm-3-fits.html#cb110-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> resultsVD[[<span class="dv">1</span>,<span class="dv">2</span>]]<span class="sc">$</span>retRsm<span class="sc">$</span>mu</span>
<span id="cb110-2"><a href="rsm-3-fits.html#cb110-2" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> resultsVD[[<span class="dv">1</span>,<span class="dv">2</span>]]<span class="sc">$</span>retRsm<span class="sc">$</span>lambda</span>
<span id="cb110-3"><a href="rsm-3-fits.html#cb110-3" aria-hidden="true" tabindex="-1"></a>nu <span class="ot">&lt;-</span> resultsVD[[<span class="dv">1</span>,<span class="dv">2</span>]]<span class="sc">$</span>retRsm<span class="sc">$</span>nu</span>
<span id="cb110-4"><a href="rsm-3-fits.html#cb110-4" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">which</span>(datasetNames <span class="sc">==</span> <span class="st">&quot;VD&quot;</span>)</span>
<span id="cb110-5"><a href="rsm-3-fits.html#cb110-5" aria-hidden="true" tabindex="-1"></a>fileName <span class="ot">&lt;-</span> datasetNames[f]</span>
<span id="cb110-6"><a href="rsm-3-fits.html#cb110-6" aria-hidden="true" tabindex="-1"></a>theData <span class="ot">&lt;-</span> <span class="fu">get</span>(<span class="fu">sprintf</span>(<span class="st">&quot;dataset%02d&quot;</span>, f)) <span class="co"># the datasets already exist as R objects</span></span>
<span id="cb110-7"><a href="rsm-3-fits.html#cb110-7" aria-hidden="true" tabindex="-1"></a>lesDistr <span class="ot">&lt;-</span> <span class="fu">UtilLesionDistrVector</span>(theData) <span class="co"># RSM ROC fitting needs to know lesDistr</span></span>
<span id="cb110-8"><a href="rsm-3-fits.html#cb110-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-9"><a href="rsm-3-fits.html#cb110-9" aria-hidden="true" tabindex="-1"></a>ret <span class="ot">&lt;-</span> <span class="fu">LesionLocLesionCls</span>(mu, lambda, nu, lesDistr)</span>
<span id="cb110-10"><a href="rsm-3-fits.html#cb110-10" aria-hidden="true" tabindex="-1"></a>L_L <span class="ot">&lt;-</span> ret<span class="sc">$</span>L_L</span>
<span id="cb110-11"><a href="rsm-3-fits.html#cb110-11" aria-hidden="true" tabindex="-1"></a>L_C <span class="ot">&lt;-</span> ret<span class="sc">$</span>L_C</span>
<span id="cb110-12"><a href="rsm-3-fits.html#cb110-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb110-13"><a href="rsm-3-fits.html#cb110-13" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">&quot;VD data i=1 j=2:  L_L = %7.3f, L_C = %7.3f&quot;</span>, L_L, L_C), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## VD data i=1 j=2:  L_L =   0.582, L_C =   0.940</code></pre>
</div>
<div id="rsm-parameters-franken-dataset-i-2-j-3" class="section level3 hasAnchor" number="10.5.2">
<h3><span class="header-section-number">10.5.2</span> RSM parameters Franken dataset i = 2, j= 3<a href="rsm-3-fits.html#rsm-parameters-franken-dataset-i-2-j-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For the Franken dataset the values are accessed as <code>resultsFR[[i,j]]</code>.</p>
<p>Displayed next are RSM parameters for the Franken dataset, treatment 2 and reader 3:</p>
<pre><code>## RSM parameters, Franken dataset, i=2, j=3: 
## mu =  2.641412 
## lambda =  2.137379 
## nu =  0.784759 
## zeta_1 =  -1.858565 
## AUC =  0.8552573 
## sigma_AUC =  0.03809136 
## NLLini =  132.6265 
## NLLfin =  127.9418</code></pre>
<p>Shown next are the lesion-localization and lesion-classification performances for this dataset.</p>
<pre><code>## FR data i=2, j=3:  L_L =   0.093, L_C =   0.969</code></pre>
<p>While the lesion-classification performances are similar for the two examples, the lesion-localization performances are different, with the Van Dyke dataset showing a greater value. This is evident from the location of the end-points in the two plots shown in Fig. <a href="rsm-3-fits.html#fig:rsm-3-fits-plots-vd-12">10.1</a> and Fig. <a href="rsm-3-fits.html#fig:rsm-3-fits-plots-fr-23">10.2</a> (an end-point closer to the top-left corner implies greater lesion-localization performance).</p>
</div>
</div>
<div id="rsm-3-fits-cbm-parameters" class="section level2 hasAnchor" number="10.6">
<h2><span class="header-section-number">10.6</span> CBM parameters<a href="rsm-3-fits.html#rsm-3-fits-cbm-parameters" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The parameters of the CBM plots are accessed as shown next.</p>
<ul>
<li><code>results[[i,j]]$retCbm$mu</code> is the CBM <span class="math inline">\(\mu\)</span> parameter for treatment i and reader j;</li>
<li><code>results[[i,j]]$retCbm$alpha</code> is the CBM <span class="math inline">\(\alpha\)</span> parameter;<br />
</li>
<li><code>as.numeric(results[[i,j]]$retCbm$zetas[1])</code> is the CBM <span class="math inline">\(\zeta_1\)</span> parameter, the threshold corresponding to the highest non-trivial operating point;</li>
<li><code>results[[i,j]]$retCbm$AUC</code> is the CBM AUC;</li>
<li><code>as.numeric(results[[i,j]]$retCbm$StdAUC)</code> is the standard deviation of the CBM AUC;</li>
<li><code>results[[i,j]]$retCbm$NLLIni</code> is the initial negative log-likelihood value;</li>
<li><code>results[[i,j]]$retCbm$NLLFin)</code> is the final negative log-likelihood value.</li>
</ul>
<p>The next example displays CBM parameters and AUC etc. for the Van Dyke dataset, treatment 1 and reader 2:</p>
<pre><code>## CBM parameters, Van Dyke Dataset, i=1, j=2: 
## mu =  2.745791 
## alpha =  0.7931264 
## zeta_1 =  1.125028 
## AUC =  0.8758668 
## sigma_AUC =  0.03964492 
## NLLini =  86.23289 
## NLLfin =  85.88459</code></pre>
<p>The next example displays CBM parameters for the Franken dataset, treatment 2 and reader 3:</p>
<pre><code>## CBM parameters, Franken dataset, i=2, j=3: 
## mu =  2.324116 
## alpha =  0.8796571 
## zeta_1 =  -0.5599662 
## AUC =  0.8957135 
## sigma_AUC =  0.03223745 
## NLLini =  98.30823 
## NLLfin =  97.82786</code></pre>
<p>The first three values are the fitted values for the CBM parameters <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\zeta_1\)</span>. The next value is the AUC under the fitted CBM curve followed by its standard error. The last two values are the initial and final values of negative log-likelihood.</p>
</div>
<div id="rsm-3-fits-proproc-parameters" class="section level2 hasAnchor" number="10.7">
<h2><span class="header-section-number">10.7</span> PROPROC parameters<a href="rsm-3-fits.html#rsm-3-fits-proproc-parameters" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For the VD dataet the <code>PROPROC</code> displayed parameters are accessed as follows:</p>
<ul>
<li><code>resultsVD[[i,j]]$c1</code> is the PROPROC <span class="math inline">\(c\)</span> parameter for treatment i and reader j;</li>
<li><code>resultsVD[[i,j]]$da</code> is the PROPROC <span class="math inline">\(d_a\)</span> parameter;<br />
</li>
<li><code>resultsVD[[i,j]]$aucProp</code> is the PROPROC AUC;</li>
</ul>
<p>Other statistics, such as standard error of AUC, are not provided by PROPROC software.</p>
<p>The next example displays PROPROC parameters for the Van Dyke dataset, treatment 1 and reader 2:</p>
<pre><code>## PROPROC parameters, Van Dyke Dataset, i=1, j=2: 
## c =  -0.2809004 
## d_a =  1.731472 
## AUC =  0.8910714</code></pre>
<p>The values are identical to those listed for treatment 1 and reader 2 in Fig. <a href="rsm-3-fits.html#fig:rsm-3-fits-proproc-output-van-dyke">10.8</a>.</p>
<p>The next example displays PROPROC parameters for the Franken dataset, treatment 2 and reader 3:</p>
<pre><code>## PROPROC parameters, Franken dataset, i=2, j=3: 
## c =  -0.3299822 
## d_a =  2.078543 
## AUC =  0.9304317</code></pre>
<p>The next section provides an overview of the most salient findings from analyzing the datasets.</p>
</div>
<div id="rsm-3-fits-overview" class="section level2 hasAnchor" number="10.8">
<h2><span class="header-section-number">10.8</span> Overview of findings<a href="rsm-3-fits.html#rsm-3-fits-overview" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With 14 datasets the total number of individual modality-reader combinations is 236: in other words, there are 236 datasets to <em>each</em> of which the three fitting algorithms were applied.</p>
<p>It is easy to be overwhelmed by the numbers so this section summarizes an important conclusion: <strong>The three fitting algorithms are consistent with a single algorithm-independent AUC</strong>.</p>
<p>If the AUCs of the three methods are identical the following relations hold with each slope <span class="math inline">\(\text{m}_{PR}\)</span> and <span class="math inline">\(\text{m}_{CR}\)</span> equal to unity:</p>
<p><span class="math display" id="eq:rsm-3-fits-slopes-equation1">\[\begin{equation}
\left.
\begin{aligned}
\text{AUC}_{\text{PRO}} =&amp; \text{m}_{PR} \text{AUC}_{\text{PRO}}  \\
\text{AUC}_{\text{CBM}} =&amp; \text{m}_{CR} \text{AUC}_{\text{PRO}}
\end{aligned}
\right \}
\tag{10.1}
\end{equation}\]</span></p>
<p>The abbreviations are as follows:</p>
<ul>
<li>PRO = PROPROC</li>
<li>PR = PROPROC vs. RSM</li>
<li>CR = CBM vs. RSM.</li>
</ul>
<p>For each dataset the plot of PROPROC AUC vs. RSM AUC should be linear with zero intercept and slope <span class="math inline">\(\text{m}_{PR}\)</span>, and likewise for the plots of CBM AUC vs. RSM AUC. The reason for the <em>zero intercept</em> is that if the AUCs are identical one cannot have an offset (i.e., intercept) term.</p>
<div id="rsm-3-fits-slopes" class="section level3 hasAnchor" number="10.8.1">
<h3><span class="header-section-number">10.8.1</span> Slopes<a href="rsm-3-fits.html#rsm-3-fits-slopes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Denote PROPROC AUC for dataset <span class="math inline">\(f\)</span>, where <span class="math inline">\(f=1,2,...,14\)</span>, treatment <span class="math inline">\(i\)</span> and reader <span class="math inline">\(j\)</span> by <span class="math inline">\(\text{AUC}^{\text{PRO}}_{fij}\)</span>. Likewise, the corresponding RSM and CBM values are denoted by <span class="math inline">\(\text{AUC}^{\text{RSM}}_{fij}\)</span> and <span class="math inline">\(\text{AUC}^{\text{CBM}}_{fij}\)</span>, respectively.</p></li>
<li><p>For a given dataset the slope of the PROPROC values vs. the RSM values is denoted <span class="math inline">\(\text{m}_{\text{PR},f}\)</span>.</p></li>
<li><p>The (grand) average over all datasets is denoted <span class="math inline">\(\text{m}^{\text{PR}}_\bullet\)</span>. Likewise, the (grand) average of the CBM AUC vs. the RSM slopes is denoted <span class="math inline">\(\text{m}^{\text{CR}}_\bullet\)</span>.</p></li>
</ul>
<p>An analysis was conducted to determine the average slopes and bootstrap confidence intervals.</p>
<p>The code for calculating the average slopes is in <code>R/compare-3-fits/slopesConvVsRsm.R</code> and that for the bootstrap confidence intervals is in <code>R/compare-3-fits/slopesAucsConvVsRsmCI.R</code>.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="rsm-3-fits.html#cb118-1" aria-hidden="true" tabindex="-1"></a>slopes <span class="ot">&lt;-</span> <span class="fu">slopesConvVsRsm</span>(datasetNames)</span>
<span id="cb118-2"><a href="rsm-3-fits.html#cb118-2" aria-hidden="true" tabindex="-1"></a>slopeCI <span class="ot">&lt;-</span> <span class="fu">slopesAucsConvVsRsmCI</span>(datasetNames)</span></code></pre></div>
<p>The call to function <code>slopesConvVsRsm()</code> returns <code>slopes</code>, which contains, for each of 14 datasets, four <code>lists</code>: two plots and two slopes. For example:</p>
<ul>
<li>PRO vs. RSM: <code>slopes$p1[[2]]</code> is the plot of <span class="math inline">\(\text{AUC}^{\text{PRO}}_{2 \bullet \bullet}\)</span> vs. <span class="math inline">\(\text{AUC}^{RSM}_{2 \bullet \bullet}\)</span> for all treatments and readers in the Van Dyke dataset. The plot for dataset <span class="math inline">\(f, f = 1, 2, ...14\)</span> is accessed as <code>slopes$p1[[f]]</code> which yields the plot of <span class="math inline">\(\text{AUC}^{\text{PRO}}_{f \bullet \bullet}\)</span> vs. <span class="math inline">\(\text{AUC}^{RSM}_{f \bullet \bullet}\)</span>.</li>
<li>CBM vs. RSM: <code>slopes$p2[[2]]</code> is the plot of <span class="math inline">\(\text{AUC}^{\text{CBM}}_{2 \bullet \bullet}\)</span> vs. <span class="math inline">\(\text{AUC}^{RSM}_{2 \bullet \bullet}\)</span> for for all treatments and readers in the Van Dyke dataset. The plot for dataset <span class="math inline">\(f\)</span> is accessed as <code>slopes$p2[[f]]</code>.</li>
<li>PRO vs. RSM: <code>slopes$m_pro_rsm</code> has two columns, each of length 14, the slopes <span class="math inline">\(\text{m}_{PR,f}\)</span> for the datasets (indexed by <span class="math inline">\(f\)</span>) and the corresponding <span class="math inline">\(R^2\)</span> values, where <span class="math inline">\(R^2\)</span> is the fraction of variance explained by the zero-intercept straight line fit. The first column is <code>slopes$m_pro_rsm[[1]]</code> and the second column is <code>slopes$m_pro_rsm[[2]]</code>.</li>
<li>CBM vs. RSM: <code>slopes$m_cbm_rsm</code> has two columns, each of length 14, the slopes <span class="math inline">\(\text{m}_{CR,f}\)</span> for the datasets and the corresponding <span class="math inline">\(R^2\)</span> values. The first column is <code>slopes$m_cbm_rsm[[1]]</code> and the second column is <code>slopes$m_cbm_rsm[[2]]</code>.</li>
</ul>
<p>As an example, for the Van Dyke dataset, <code>slopes$p1[[2]]</code> which is shown in the left in Fig. <a href="rsm-3-fits.html#fig:rsm-3-fits-plots-2">10.3</a>, is the plot of <span class="math inline">\(\text{AUC}^{\text{PRO}}_{2 \bullet \bullet}\)</span> vs. <span class="math inline">\(\text{AUC}^{RSM}_{2 \bullet \bullet}\)</span>. Shown in the right is <code>slopes$p2[[2]]</code>, the plot of <span class="math inline">\(\text{AUC}^{\text{CBM}}_{2 \bullet \bullet}\)</span> vs. <span class="math inline">\(\text{AUC}^{RSM}_{2 \bullet \bullet}\)</span>. Each plot has the zero-intercept linear fit superposed on the <span class="math inline">\(2\times5 = 10\)</span> data points; each data point represents a distinct modality-reader combination.</p>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-2"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-2-1.png" alt="Van Dyke dataset: Left plot is PROPROC-AUC vs. RSM-AUC with the superposed zero-intercept linear fit. The number of data points is `nPts` = 10. Right plot is CBM-AUC vs. RSM-AUC." width="672" />
<p class="caption">
FIGURE 10.3: Van Dyke dataset: Left plot is PROPROC-AUC vs. RSM-AUC with the superposed zero-intercept linear fit. The number of data points is <code>nPts</code> = 10. Right plot is CBM-AUC vs. RSM-AUC.
</p>
</div>
<p>The next plot shows corresponding plots for the Franken dataset in which there are <span class="math inline">\(2\times 4 = 8\)</span> points in each plot.</p>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-3"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-3-1.png" alt="Similar to previous plot, for Franken dataset." width="672" />
<p class="caption">
FIGURE 10.4: Similar to previous plot, for Franken dataset.
</p>
</div>
</div>
<div id="rsm-3-fits-confidence-intervals" class="section level3 hasAnchor" number="10.8.2">
<h3><span class="header-section-number">10.8.2</span> Confidence intervals<a href="rsm-3-fits.html#rsm-3-fits-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The call to <code>slopesAucsConvVsRsmCI</code> returns <code>slopeCI</code>, containing the results of the bootstrap analysis (the bullet symbols <span class="math inline">\(\bullet\)</span> denote grand averages over 14 datasets):</p>
<ul>
<li><code>slopeCI$cislopeProRsm</code> 95-percent confidence interval for <span class="math inline">\(\text{m}_{\text{PR} \bullet}\)</span></li>
<li><code>slopeCI$cislopeCbmRsm</code> 95-percent confidence interval for <span class="math inline">\(\text{m}_{\text{CR} \bullet}\)</span></li>
<li><code>slopeCI$histSlopeProRsm</code> histogram of 200 bootstrap values of <span class="math inline">\(\text{m}_{\text{PR} \bullet}\)</span></li>
<li><code>slopeCI$histSlopeCbmRsm</code> histogram of 200 bootstrap values of <span class="math inline">\(\text{m}_{\text{CR} \bullet}\)</span></li>
<li><code>slopeCI$ciAvgAucRsm</code> confidence interval from 200 bootstrap values of <span class="math inline">\(\text{AUC}^{\text{RSM}}_\bullet\)</span></li>
<li><code>slopeCI$ciAvgAucPro</code> confidence interval for 200 bootstrap values of <span class="math inline">\(\text{AUC}^{\text{PRO}}_\bullet\)</span></li>
<li><code>slopeCI$ciAvgAucCbm</code> confidence interval for 200 bootstrap values of <span class="math inline">\(\text{AUC}^{\text{CBM}}_\bullet\)</span></li>
</ul>
<p>As examples,</p>
<pre><code>##           m-PR      m-CR
## 2.5%  1.005092 0.9919886
## 97.5% 1.012285 0.9966149</code></pre>
<p>The CI for <span class="math inline">\(\text{m}_{\text{PR} \bullet}\)</span> is slightly above unity, while that for <span class="math inline">\(\text{m}_{\text{CR} \bullet}\)</span> is slightly below. Shown next is the histogram plot for <span class="math inline">\(\text{m}_{\text{PR} \bullet}\)</span> (left plot) and <span class="math inline">\(\text{m}_{\text{CR} \bullet}\)</span> (right plot). Quantiles of these histograms were used to compute the previously cited confidence intervals.</p>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-histo-slopes"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-histo-slopes-1.png" alt="Histograms of slope PROPROC AUC vs. RSM AUC (left) and slope CBM AUC vs. RSM AUC (right)." width="672" />
<p class="caption">
FIGURE 10.5: Histograms of slope PROPROC AUC vs. RSM AUC (left) and slope CBM AUC vs. RSM AUC (right).
</p>
</div>
</div>
<div id="rsm-3-fits-slopes-confidence-intervals-summary" class="section level3 hasAnchor" number="10.8.3">
<h3><span class="header-section-number">10.8.3</span> Summary of slopes and confidence intervals<a href="rsm-3-fits.html#rsm-3-fits-slopes-confidence-intervals-summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:rsm-3-fits-slopes-table1">TABLE 10.1: </span>Summary of slopes and correlations for the two zero-intercept fits: PROPROC AUC vs. RSM AUC and CBM AUC vs. RSM AUC. The average of each slope equals unity to within 0.6 percent.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
<span class="math inline">\(\text{m}_{PR}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(R^2_{PR}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\text{m}_{CR}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(R^2_{CR}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
TONY
</td>
<td style="text-align:left;">
1.0002
</td>
<td style="text-align:left;">
0.9997
</td>
<td style="text-align:left;">
0.9933
</td>
<td style="text-align:left;">
0.9997
</td>
</tr>
<tr>
<td style="text-align:left;">
VD
</td>
<td style="text-align:left;">
1.0061
</td>
<td style="text-align:left;">
0.9998
</td>
<td style="text-align:left;">
1.0007
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
FR
</td>
<td style="text-align:left;">
0.9995
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
0.9977
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
FED
</td>
<td style="text-align:left;">
1.0146
</td>
<td style="text-align:left;">
0.9998
</td>
<td style="text-align:left;">
0.9999
</td>
<td style="text-align:left;">
0.9999
</td>
</tr>
<tr>
<td style="text-align:left;">
JT
</td>
<td style="text-align:left;">
0.9964
</td>
<td style="text-align:left;">
0.9995
</td>
<td style="text-align:left;">
0.9972
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
MAG
</td>
<td style="text-align:left;">
1.036
</td>
<td style="text-align:left;">
0.9983
</td>
<td style="text-align:left;">
0.9953
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
OPT
</td>
<td style="text-align:left;">
1.0184
</td>
<td style="text-align:left;">
0.9997
</td>
<td style="text-align:left;">
1.0059
</td>
<td style="text-align:left;">
0.9997
</td>
</tr>
<tr>
<td style="text-align:left;">
PEN
</td>
<td style="text-align:left;">
1.0081
</td>
<td style="text-align:left;">
0.9996
</td>
<td style="text-align:left;">
0.9976
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
NICO
</td>
<td style="text-align:left;">
0.9843
</td>
<td style="text-align:left;">
0.9998
</td>
<td style="text-align:left;">
0.997
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
RUS
</td>
<td style="text-align:left;">
0.9989
</td>
<td style="text-align:left;">
0.9999
</td>
<td style="text-align:left;">
0.9921
</td>
<td style="text-align:left;">
0.9999
</td>
</tr>
<tr>
<td style="text-align:left;">
DOB1
</td>
<td style="text-align:left;">
1.0262
</td>
<td style="text-align:left;">
0.9963
</td>
<td style="text-align:left;">
0.9886
</td>
<td style="text-align:left;">
0.9962
</td>
</tr>
<tr>
<td style="text-align:left;">
DOB2
</td>
<td style="text-align:left;">
1.0056
</td>
<td style="text-align:left;">
0.9987
</td>
<td style="text-align:left;">
0.971
</td>
<td style="text-align:left;">
0.9978
</td>
</tr>
<tr>
<td style="text-align:left;">
DOB3
</td>
<td style="text-align:left;">
1.0211
</td>
<td style="text-align:left;">
0.998
</td>
<td style="text-align:left;">
0.9847
</td>
<td style="text-align:left;">
0.9986
</td>
</tr>
<tr>
<td style="text-align:left;">
FZR
</td>
<td style="text-align:left;">
1.0027
</td>
<td style="text-align:left;">
0.9999
</td>
<td style="text-align:left;">
0.9996
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
AVG
</td>
<td style="text-align:left;">
1.0084
</td>
<td style="text-align:left;">
0.9992
</td>
<td style="text-align:left;">
0.9943
</td>
<td style="text-align:left;">
0.9994
</td>
</tr>
<tr>
<td style="text-align:left;">
CI
</td>
<td style="text-align:left;">
(1.005, 1.012)
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
(0.992, 0.997)
</td>
<td style="text-align:left;">
NA
</td>
</tr>
</tbody>
</table>
<p>In Table <a href="rsm-3-fits.html#tab:rsm-3-fits-slopes-table1">10.1</a> the second column, labeled <span class="math inline">\(\text{m}_{PR}\)</span>, shows slopes of straight lines, zero-intercept to go through the origin, to PROPROC AUC vs. RSM AUC values, for each of the 14 datasets, as labeled in the fits column. The third column, labeled <span class="math inline">\(R^2_{PR}\)</span>, lists the square of the correlation coefficient for each fit. The fourth and fifth columns list the corresponding values for the CBM AUC vs. RSM AUC fits. The second last row lists the grand averages (AVG) and the last row lists the 95 percent confidence intervals.</p>
</div>
</div>
<div id="rsm-3-fits-discussion-summary" class="section level2 hasAnchor" number="10.9">
<h2><span class="header-section-number">10.9</span> Reason for equal AUCs / Summary<a href="rsm-3-fits.html#rsm-3-fits-discussion-summary" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We find that all three proper ROC methods yield almost the same AUC. The reason is that the proper ROC is a consequence of using a decision variable that is equivalent (in the arbitrary monotonic increasing transformations sense, see below) to a likelihood ratio. Proper ROC fitting is discussed in <a href="https://dpc10ster.github.io/RJafrocRocBook/proper-roc-models.html#proper-roc-models-likelihood-ratio-theorem1">RJafrocRocBook</a>. The likelihood ratio <span class="math inline">\(l(z)\)</span> is defined as the ratio of the diseased pdf to the non-diseased pdf:</p>
<p><span class="math display" id="eq:rsm-3-fits-l-z">\[\begin{equation}    
l(z) \equiv \frac{\text{pdf}_D(z)}{\text{pdf}_N(z)}
\tag{10.2}
\end{equation}\]</span></p>
<p>There is a theorem <span class="citation">(<a href="#ref-barrett2013foundations" role="doc-biblioref">Barrett and Myers 2013</a>)</span> that an observer who uses the likelihood ratio <span class="math inline">\(l(z)\)</span> or any monotone increasing transformation of it as the decision variable, has optimal performance, i.e., maximum ROC-AUC. To use the terminology of <span class="citation">(<a href="#ref-barrett2013foundations" role="doc-biblioref">Barrett and Myers 2013</a>)</span> any observer using the likelihood ratio as the decision variable is an ideal observer (Section 13.2.6 ibid). However, <strong>different ideal observers must yield the same AUC as otherwise one observer would be “more ideal” than another</strong>. Different models of fitting proper ROCs represent different approaches to modeling the decision variable and the likelihood ratio, but while the curves can have different shapes (the slope of the ROC curve at a given point equals the likelihood ratio calculated at that point) their AUCs must agree. This explains the empirical observation of this chapter that RSM, PROPROC and CBM all yield the same AUCs as summarized in Table <a href="rsm-3-fits.html#tab:rsm-3-fits-slopes-table1">10.1</a>.</p>
</div>
<div id="rsm-3-fits-appendices" class="section level2 hasAnchor" number="10.10">
<h2><span class="header-section-number">10.10</span> Appendices<a href="rsm-3-fits.html#rsm-3-fits-appendices" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="rsm-3-fits-one-dataset-proproc" class="section level3 hasAnchor" number="10.10.1">
<h3><span class="header-section-number">10.10.1</span> Location of PROPROC files<a href="rsm-3-fits.html#rsm-3-fits-one-dataset-proproc" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For each dataset PROPROC parameters were obtained by running the Windows software with PROPROC selected as the curve-fitting method. The results are saved to files that end with <code>proprocnormareapooled.csv</code> <a href="#fn36" class="footnote-ref" id="fnref36"><sup>36</sup></a> contained in “R/compare-3-fits/MRMCRuns/C/”, where <code>C</code> denotes the name of the dataset (for example, for the Van Dyke dataset, <code>C</code> = “VD”). Examples are shown in the next two screen-shots.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rsm-3-fits-mrmc-runs"></span>
<img src="images/compare-3-fits/MRMCRuns.png" alt="Screen shot (1 of 2) of `R/compare-3-fits/MRMCRuns` showing the folders containing the results of PROPROC analysis on 14 datasets." width="300pt" />
<p class="caption">
FIGURE 10.6: Screen shot (1 of 2) of <code>R/compare-3-fits/MRMCRuns</code> showing the folders containing the results of PROPROC analysis on 14 datasets.
</p>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rsm-3-fits-mrmc-runs-vd"></span>
<img src="images/compare-3-fits/MRMCRuns-VD.png" alt="Screen shot (2 of 2) of `R/compare-3-fits/MRMCRuns/VD` showing files containing the results of PROPROC analysis for the Van Dyke dataset." width="300pt" />
<p class="caption">
FIGURE 10.7: Screen shot (2 of 2) of <code>R/compare-3-fits/MRMCRuns/VD</code> showing files containing the results of PROPROC analysis for the Van Dyke dataset.
</p>
</div>
<p>The contents of <code>R/compare-3-fits/MRMCRuns/VD/VDproprocnormareapooled.csv</code> are shown next, see Fig. <a href="rsm-3-fits.html#fig:rsm-3-fits-proproc-output-van-dyke">10.8</a>. <a href="#fn37" class="footnote-ref" id="fnref37"><sup>37</sup></a> The PROPROC parameters <span class="math inline">\(c\)</span> and <span class="math inline">\(d_a\)</span> are in the last two columns. The column names are <code>T</code> = treatment; <code>R</code> = reader; <code>return-code</code> = undocumented value, <code>area</code> = PROPROC AUC; <code>numCAT</code> = number of ROC bins; <code>adjPMean</code> = undocumented value; <code>c</code> = <span class="math inline">\(c\)</span> and <code>d_a</code> = <span class="math inline">\(d_a\)</span>, are the PROPROC parameters defined in <span class="citation">(<a href="#ref-metz1999proper" role="doc-biblioref">Charles E. Metz and Pan 1999</a>)</span>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rsm-3-fits-proproc-output-van-dyke"></span>
<img src="images/compare-3-fits/vanDyke.png" alt="PROPROC output for the Van Dyke ROC data set. The first column is the treatment, the second is the reader, the fourth is the AUC and the last two columns are the c and $d_a$ parameters." width="50%" height="20%" />
<p class="caption">
FIGURE 10.8: PROPROC output for the Van Dyke ROC data set. The first column is the treatment, the second is the reader, the fourth is the AUC and the last two columns are the c and <span class="math inline">\(d_a\)</span> parameters.
</p>
</div>
</div>
<div id="rsm-3-fits-pre-analyzed-results" class="section level3 hasAnchor" number="10.10.2">
<h3><span class="header-section-number">10.10.2</span> Location of pre-analyzed results<a href="rsm-3-fits.html#rsm-3-fits-pre-analyzed-results" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following screen shot shows the pre-analyzed files created by the function <code>Compare3ProperRocFits()</code> described below. Each file is named <code>allResultsC</code>, where <code>C</code> is the abbreviated name of the dataset (uppercase C denotes one or more uppercase characters; for example, <code>C</code> = <code>VD</code> denotes the Van Dyke dataset.).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rsm-3-fits-all-results-rsm6"></span>
<img src="images/compare-3-fits/RSM6.png" alt="Screen shot of `R/compare-3-fits/RSM6` showing the results files created by  `Compare3ProperRocFits()`." width="300pt" />
<p class="caption">
FIGURE 10.9: Screen shot of <code>R/compare-3-fits/RSM6</code> showing the results files created by <code>Compare3ProperRocFits()</code>.
</p>
</div>
</div>
<div id="rsm-3-fits-representative-plots-van-dyke" class="section level3 hasAnchor" number="10.10.3">
<h3><span class="header-section-number">10.10.3</span> Plots for the Van Dyke dataset<a href="rsm-3-fits.html#rsm-3-fits-representative-plots-van-dyke" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following plots are arranged in pairs, with the left plot corresponding to treatment 1 and the right to treatment 2.</p>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-vd-1-1"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-vd-1-1-1.png" alt="Composite plots in both treatments for the Van Dyke dataset, reader 1." width="672" />
<p class="caption">
FIGURE 10.10: Composite plots in both treatments for the Van Dyke dataset, reader 1.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-vd-1-2"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-vd-1-2-1.png" alt="Composite plots in both treatments for the Van Dyke dataset, reader 2. For treatment 2 the RSM and PROPROC fits are indistinguishable." width="672" />
<p class="caption">
FIGURE 10.11: Composite plots in both treatments for the Van Dyke dataset, reader 2. For treatment 2 the RSM and PROPROC fits are indistinguishable.
</p>
</div>
<p>The RSM parameter values for the treatment 2 plot are: <span class="math inline">\(\mu\)</span> = 5.767237, <span class="math inline">\(\lambda\)</span> = 2.7212621, <span class="math inline">\(\nu\)</span> = 0.8021718, <span class="math inline">\(\zeta_1\)</span> = -1.5717303. The corresponding CBM values are <span class="math inline">\(\mu\)</span> = 5.4464738, <span class="math inline">\(\alpha\)</span> = 0.8023609, <span class="math inline">\(\zeta_1\)</span> = -1.4253826. The RSM and CBM <span class="math inline">\(\mu\)</span> parameters are close and likewise the RSM <span class="math inline">\(\nu\)</span> and CBM <span class="math inline">\(\alpha\)</span> parameters are close - this is because they have similar physical meanings, which is investigated later in this chapter TBA. [The CBM does not have a parameter analogous to the RSM <span class="math inline">\(\lambda\)</span> parameter.]</p>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-vd-1-3"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-vd-1-3-1.png" alt="Composite plots in both treatments for the Van Dyke dataset, reader 3." width="672" />
<p class="caption">
FIGURE 10.12: Composite plots in both treatments for the Van Dyke dataset, reader 3.
</p>
</div>
<p>The RSM parameters for the treatment 1 plot are: <span class="math inline">\(\mu\)</span> = 3.1527627, <span class="math inline">\(\lambda\)</span> = 9.9986154, <span class="math inline">\(\nu\)</span> = 0.9899933, <span class="math inline">\(\zeta_1\)</span> = 1.1733988. The corresponding CBM values are <span class="math inline">\(\mu\)</span> = 2.1927712, <span class="math inline">\(\alpha\)</span> = 0.98, <span class="math inline">\(\zeta_1\)</span> = -0.5168848.</p>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-vd-1-4"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-vd-1-4-1.png" alt="Composite plots in both treatments for the Van Dyke dataset, reader 4. For treatment 2 the 3 plots are indistinguishable and each one has AUC = 1. The degeneracy is due to all operating points being on the axes of the unit square." width="672" />
<p class="caption">
FIGURE 10.13: Composite plots in both treatments for the Van Dyke dataset, reader 4. For treatment 2 the 3 plots are indistinguishable and each one has AUC = 1. The degeneracy is due to all operating points being on the axes of the unit square.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-vd-1-5"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-vd-1-5-1.png" alt="Composite plots in both treatments for the Van Dyke dataset, reader 5." width="672" />
<p class="caption">
FIGURE 10.14: Composite plots in both treatments for the Van Dyke dataset, reader 5.
</p>
</div>
</div>
<div id="rsm-3-fits-representative-plots-franken" class="section level3 hasAnchor" number="10.10.4">
<h3><span class="header-section-number">10.10.4</span> Plots for the Franken dataset<a href="rsm-3-fits.html#rsm-3-fits-representative-plots-franken" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following plots are arranged in pairs, with the left plot corresponding to treatment 1 and the right to treatment 2. These plots apply to the Franken dataset.</p>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-fr-1-1"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-fr-1-1-1.png" alt="Composite plots in both treatments for the Franken dataset, reader 1." width="672" />
<p class="caption">
FIGURE 10.15: Composite plots in both treatments for the Franken dataset, reader 1.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-fr-1-2"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-fr-1-2-1.png" alt="Composite plots in both treatments for the Franken dataset, reader 2." width="672" />
<p class="caption">
FIGURE 10.16: Composite plots in both treatments for the Franken dataset, reader 2.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-fr-1-3"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-fr-1-3-1.png" alt="Composite plots in both treatments for the Franken dataset, reader 3." width="672" />
<p class="caption">
FIGURE 10.17: Composite plots in both treatments for the Franken dataset, reader 3.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:rsm-3-fits-plots-fr-1-4"></span>
<img src="12-rsm-3-fits_files/figure-html/rsm-3-fits-plots-fr-1-4-1.png" alt="Composite plots in both treatments for the Franken dataset, reader 4." width="672" />
<p class="caption">
FIGURE 10.18: Composite plots in both treatments for the Franken dataset, reader 4.
</p>
</div>

</div>
</div>
</div>



<h3>REFERENCES<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-barrett2013foundations" class="csl-entry">
Barrett, Harrison H, and Kyle J Myers. 2013. <em>Foundations of Image Science</em>. John Wiley &amp; Sons.
</div>
<div id="ref-chakraborty2011estimating" class="csl-entry">
Chakraborty, DP, and Tony Svahn. 2011. <span>“Estimating the Parameters of a Model of Visual Search from ROC Data: An Alternate Method for Fitting Proper ROC Curves.”</span> In <em>Medical Imaging 2011: Image Perception, Observer Performance, and Technology Assessment</em>, 7966:189–97. SPIE.
</div>
<div id="ref-metz1999proper" class="csl-entry">
Metz, Charles E, and Xiaochuan Pan. 1999. <span>“<span>‘Proper’</span> Binormal ROC Curves: Theory and Maximum-Likelihood Estimation.”</span> <em>Journal of Mathematical Psychology</em> 43 (1): 1–33.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="33">
<li id="fn33"><p>Comparing the RSM to the binormal model would be inappropriate, as the latter does not predict proper ROCs.<a href="rsm-3-fits.html#fnref33" class="footnote-back">↩︎</a></p></li>
<li id="fn34"><p>Sept. 04, 2014; the version used in this chapter is no longer distributed.<a href="rsm-3-fits.html#fnref34" class="footnote-back">↩︎</a></p></li>
<li id="fn35"><p>The initial value is calculated using initial estimates of parameters and the final value is that resulting from the log-likelihood maximization procedure. Since in fact negative log-likelihood is being <em>minimized</em>, the final value is smaller than the initial value.<a href="rsm-3-fits.html#fnref35" class="footnote-back">↩︎</a></p></li>
<li id="fn36"><p>In accordance with R-package policies white-spaces in the original <code>PROPROC</code> output file names have been removed.<a href="rsm-3-fits.html#fnref36" class="footnote-back">↩︎</a></p></li>
<li id="fn37"><p>The <code>VD.lrc</code> file in this directory is the Van Dyke data formatted for input to OR DBM-MRMC 2.5.<a href="rsm-3-fits.html#fnref37" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="rsm-fitting.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="standalone-cad-radiologists.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["RJafrocFrocBook.pdf", "RJafrocFrocBook.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
