# Low performance vary nu  {#optim-op-point-low-performance-vary-nu}

---
output:
  rmarkdown::pdf_document:
    fig_caption: yes        
    includes:  
      in_header: R/learn/my_header.tex
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval.after = "fig.cap"
)

library(RJafroc)
library(ggplot2)
library(kableExtra)
library(gridExtra)
library(abind)
library(dplyr)
library(mvtnorm)
```



```{r, echo=FALSE}
OpPtStr <- function(x,y) {
  y <- paste0("(", sprintf("%.3f", x), ", ", sprintf("%.3f", y), ")")
  return(y)
}

simplePrint <- function(x) {
  sprintf("%.3f", x)
}
```



## Methods {#optim-op-point-low-performance-vary-nu-methods}

```{r foms_2be_maximized, echo=FALSE}

wAFROC <- function (
  zeta1, mu, lambdaP, nuP, 
  lesDistr, 
  relWeights) {
  # return negative of aucwAFROC 
  # (as optimize finds minimum of function)
  return(-UtilAnalyticalAucsRSM(mu, lambdaP = lambdaP, nuP = nuP, zeta1, lesDistr, relWeights)$aucwAFROC)
}


Youden <- function (zeta1, mu, lambdaP, nuP, lesDistr) {
  # add sensitivity and specificity 
  # and subtract 1, i.e., Youden's index
  x <- RSM_yROC(zeta1, mu, lambdaP, nuP, lesDistr) + 
    (1 - RSM_xROC(zeta1, lambdaP)) - 1
  # return negative of Youden-index 
  # (as optimize finds minimum of function)
  return(-x)
}
```


## Appendix 3: Operating point on ROC {#optim-op-point-low-performance-vary-nu-on-roc}


```{r}
muArr <- c(1)
lambdaPArr <- c(1)
nuPArr <- c(0.2, 0.5, 0.7, 0.9)
lesDistr <- c(0.5, 0.5)
relWeights <- c(0.5, 0.5)
```



```{r cache = FALSE, echo=FALSE}
wAfrocArr <- array(dim = c(2,length(muArr), length(lambdaPArr), length(nuPArr)))
zetaOptArr <- array(dim = c(2,length(muArr), length(lambdaPArr), length(nuPArr)))
rocArr <- array(dim = c(2,length(muArr), length(lambdaPArr), length(nuPArr)))
fpfOptArr <- array(dim = c(2,length(muArr), length(lambdaPArr), length(nuPArr)))
tpfOptArr <- array(dim = c(2,length(muArr), length(lambdaPArr), length(nuPArr)))
nlfOptArr <- array(dim = c(2,length(muArr), length(lambdaPArr), length(nuPArr)))
llfOptArr <- array(dim = c(2,length(muArr), length(lambdaPArr), length(nuPArr)))
for (i1 in 1:length(muArr)) {
  for (i2 in 1:length(lambdaPArr)) {
    for (i3 in 1:length(nuPArr)) {
      mu <- muArr[i1]
      lambdaP <- lambdaPArr[i2]
      nuP <- nuPArr[i3]
      for (y in 1:2) {
        if (y == 1) {
          x <- optimize(wAFROC, 
                        interval = c(-5,5), 
                        mu, 
                        lambdaP = lambdaP, 
                        nuP = nuP, 
                        lesDistr, 
                        relWeights)
          zetaOptArr[y,i1,i2,i3] <- x$minimum
          wAfrocArr[y,i1,i2,i3] <- -x$objective # safe to use objective here
          rocArr[y,i1,i2,i3] <- UtilAnalyticalAucsRSM(
            mu, 
            lambdaP = lambdaP, 
            nuP = nuP, 
            zeta1 = x$minimum, 
            lesDistr, 
            relWeights)$aucROC
          fpfOptArr[y,i1,i2,i3] <- RSM_xROC(
            z = x$minimum, 
            lambdaP = lambdaP)
          tpfOptArr[y,i1,i2,i3] <- RSM_yROC(
            z = x$minimum, 
            mu, 
            lambdaP = lambdaP,
            nuP = nuP,
            lesDistr = lesDistr)
          nlfOptArr[y,i1,i2,i3] <- RSM_xFROC(
            z = x$minimum, 
            lambdaP = lambdaP)
          llfOptArr[y,i1,i2,i3] <- RSM_yFROC(
            z = x$minimum, 
            mu, 
            nuP = nuP)
        } else if (y == 2) {
          x <- optimize(Youden, 
                        interval = c(-5,5), 
                        mu, 
                        lambdaP = lambdaP, 
                        nuP = nuP, 
                        lesDistr)
          zetaOptArr[y,i1,i2,i3] <- x$minimum
          wAfrocArr[y,i1,i2,i3] <- UtilAnalyticalAucsRSM(
            mu, 
            lambdaP = lambdaP, 
            nuP = nuP, 
            zeta1 = x$minimum, 
            lesDistr, 
            relWeights)$aucwAFROC
          rocArr[y,i1,i2,i3] <- UtilAnalyticalAucsRSM(
            mu, 
            lambdaP = lambdaP, 
            nuP = nuP, 
            zeta1 = x$minimum, 
            lesDistr, 
            relWeights)$aucROC
          fpfOptArr[y,i1,i2,i3] <- RSM_xROC(
            z = x$minimum, 
            lambdaP = lambdaP)
          tpfOptArr[y,i1,i2,i3] <- RSM_yROC(
            z = x$minimum, 
            mu, 
            lambdaP = lambdaP,
            nuP = nuP,
            lesDistr = lesDistr)
          nlfOptArr[y,i1,i2,i3] <- RSM_xFROC(
            z = x$minimum, 
            lambdaP = lambdaP)
          llfOptArr[y,i1,i2,i3] <- RSM_yFROC(
            z = x$minimum, mu, nuP)
        } else stop("incorrect y")
      }
    }
  }
}
```





```{r optim-op-point-low-performance-vary-nu-table-vary-all-contents, echo=FALSE}
x1 <- expand.grid(FOM = c("wAFROC", "Youden"), mu = muArr, lambda = lambdaPArr, nu = nuPArr)
x1 <- cbind(x1, zeta1 = simplePrint(zetaOptArr), wAFROC = simplePrint(wAfrocArr), AUC = simplePrint(rocArr), Sp = simplePrint(1-fpfOptArr), Se = simplePrint(tpfOptArr))
colnames(x1) <- c("FOM", "$\\mu$", "$\\lambda$", "$\\nu$", "$\\zeta_1$", "wAFROC", "ROC", "Sp", "Se")
```



```{r optim-op-point-low-performance-vary-nu-table-vary-all, echo=FALSE}
kbl(x1, caption = "Summary of optimizations for combinations of levels of $\\mu$, $\\lambda$ and $\\nu$ parameters. FOM = figure of merit, $\\zeta_1$ = threshold that optimizes FOM, wAFROC = wAFROC-AUC, ROC = ROC-AUC, Sp = specificity and Se = sensitivity.", booktabs = TRUE, escape = FALSE) %>% kable_styling(latex_options = c("basic", "scale_down", "HOLD_position"), row_label_position = "c") 
```





```{r, echo=FALSE}
plotArr <- array(list(), dim = 8)
i <- 1
for (i1 in 1:length(muArr)) {
  for (i2 in 1:length(lambdaPArr)) {
    for (i3 in 1:length(nuPArr)) {
      mu <- muArr[i1]
      lambdaP <- lambdaPArr[i2]
      nuP <- nuPArr[i3]
      z <- seq(-5,mu+5,0.1)
      xFROC <- RSM_xFROC(z, lambdaP)
      yFROC <- RSM_yFROC(z, mu, nuP)
      df_froc <- data.frame(
        NLF = xFROC, 
        LLF = yFROC)
      plotArr[[i]] <- ggplot2::ggplot(
        df_froc, 
        aes(x = NLF, y = LLF)) + 
        geom_line() +
        scale_x_continuous(limits = c(0,lambdaP)) + 
        scale_y_continuous(limits = c(0,1)) +
        ggtitle(paste0("mu = ", mu, ", nu = ", nuP, ", lambda = ", lambdaP))
      for (y in 1:2) {
        optPt <- data.frame(
          NLF = nlfOptArr[y,i1,i2,i3], 
          LLF = llfOptArr[y,i1,i2,i3])
        plotArr[[i]] <- plotArr[[i]] + 
          geom_point(data = optPt, color = y) 
      }
      i <- i + 1
    }
  }
}
```




```{r optim-op-point-low-performance-vary-nu-vary-all-froc, fig.cap = "FROC plots with superimposed operating points for varying $\\nu$. The black dot corresponds to wAFROC AUC optimization and the red dot to Youden-index optimization.", fig.show='hold', echo=FALSE}
grid.arrange(plotArr[[1]], plotArr[[2]], plotArr[[3]], plotArr[[4]], nrow = 2, ncol = 2)
#grid.arrange(plotArr[[5]], plotArr[[6]], plotArr[[7]], plotArr[[8]], nrow = 2, ncol = 2)
```



```{r, echo=FALSE}
plotArr <- array(list(), dim = 8)
i <- 1
for (i1 in 1:length(muArr)) {
  for (i2 in 1:length(lambdaPArr)) {
    for (i3 in 1:length(nuPArr)) {
      mu <- muArr[i1]
      lambdaP <- lambdaPArr[i2]
      nuP <- nuPArr[i3]
      x <- UtilPhysical2IntrinsicRSM(mu, lambdaP = lambdaP, nuP = nuP)
      lambda <- x$lambda
      nu <- x$nu
      plotArr[[i]] <- PlotRsmOperatingCharacteristics(
        c(mu,mu),
        c(lambda,lambda),
        c(nu,nu),
        c(zetaOptArr[1,i1,i2,i3], zetaOptArr[2,i1,i2,i3]),
        lesDistr,
        relWeights,
        OpChType = "wAFROC",
        legendPosition = "null"
      )$wAFROCPlot +
        ggtitle(paste0("mu = ", mu, ", nu = ", nuP, ", lambda = ", lambdaP))
      i <- i + 1
    }
  }
}
```







```{r optim-op-point-low-performance-vary-nu-vary-all-wafroc, fig.cap="wAFROC plots for the two optimization methods. The color coding is as in previous figures.", fig.show='hold', echo=FALSE}
grid.arrange(plotArr[[1]], plotArr[[2]], plotArr[[3]], plotArr[[4]], nrow = 2, ncol = 2)
#grid.arrange(plotArr[[5]], plotArr[[6]], plotArr[[7]], plotArr[[8]], nrow = 2, ncol = 2)
```





```{r, echo=FALSE}
plotArr <- array(list(), dim = 8)
i <- 1
for (i1 in 1:length(muArr)) {
  for (i2 in 1:length(lambdaPArr)) {
    for (i3 in 1:length(nuPArr)) {
      mu <- muArr[i1]
      lambdaP <- lambdaPArr[i2]
      nuP <- nuPArr[i3]
      x <- UtilPhysical2IntrinsicRSM(mu, lambdaP = lambdaP, nuP = nuP)
      lambda <- x$lambda
      nu <- x$nu
      plotArr[[i]] <- PlotRsmOperatingCharacteristics(
        c(mu,mu),
        c(lambda,lambda),
        c(nu,nu),
        c(zetaOptArr[1,i1,i2,i3], zetaOptArr[2,i1,i2,i3]),
        lesDistr,
        relWeights,
        OpChType = "ROC",
        legendPosition = "null"
      )$ROCPlot +
        ggtitle(paste0("mu = ", mu, ", nu = ", nuP, ", lambda = ", lambdaP))
      i <- i + 1
    }
  }
}
```





```{r optim-op-point-low-performance-vary-nu-vary-all-roc, fig.cap="ROC plots for the two optimization methods. The color coding is as in previous figures.", fig.show='hold', echo=FALSE}
grid.arrange(plotArr[[1]], plotArr[[2]], plotArr[[3]], plotArr[[4]], nrow = 2, ncol = 2)
#grid.arrange(plotArr[[5]], plotArr[[6]], plotArr[[7]], plotArr[[8]], nrow = 2, ncol = 2)
```

## References {#optim-op-point-low-performance-vary-nu-references}
