on:
  push:
     branches:
       - main


name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Install rmarkdown
        run: > 
            Rscript -e 'install.packages(c("foreach","doRNG","doParallel",
            "rmarkdown","bookdown","here","remotes","exactci",
            "ggplot2","kableExtra","abind","dplyr","grid","png",
            "gridExtra","pBrackets","seqinr","mvtnorm","Rmpfr"))'
      - name: Install Rjafroc
        run: Rscript -e 'remotes::install_github("dpc10ster/RJafroc")'
      - name: Render PDF Book
        run: Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: docs/
      - name: Render HTML Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/
  

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          # Artifact name
          name: docs # optional
          # Destination path
          path: docs # optional
      - name: Deploy to GitHub Pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: book-output
      - name: Upload artifact
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          # git clone -b gh-pages book-output
          cd book-output
          cp -r ../docs/* ./
          git add --all *
          git commit -m "Update the book" || true
          git push -q origin gh-pages